### ISSUE TITLE
How `git-filter-repo` work on most recent commits that still contain large files?

### ISSUE THREAD

**Issue by WindingWinter** [newren/git-filter-repo#105]
My current repo consists of a lot of binary files (`*.dll`, `*.msm`)and they have eaten up a large chunk of the repo size. A Bitbucket repo has a limit of 2GB. So my BIG repo is now running at 1.99GB, dangerously close to the upper limit allowed. 

As of writing the binary files are still inside the repo, and I'm now thinking of get rid of them in order to shrink the repo size. I don't mind deleting the binary files from my bitbucket git repo and from all the history, as Iong as they are still in my hard disk (ie: any git operation shouldn't remove them from hard disk, only from git repo). 

I've evaluated BFG and probably I can use `$ bfg --delete-files "*.{dll, msm}"  BIG.git` to delete them from history, but from [what I can tell](https://rtyley.github.io/bfg-repo-cleaner/)

> BFG doesn't modify the contents of your latest commit on your master (or 'HEAD') branch, even though it will clean all the commits before it.

Which means I have to manually delete those binary files first via `git rm -cached`.

So essentially if I use BFG, then I need to do:

1. `git clone --mirror git@bitbucket.org:<username>/BIG.git` to mirror the repo even though I already have a clean repo on my hard disk.
1. `git rm -cached` and set the `.gitignore` file to ignore `.dll` and `.msm`.
2. `$ bfg --delete-files "*.{dll, msm}"  my-repo.git`
3. `git push`

Am I right?

By contrast, `git-filter-repo` works more simply, assuming that I'm the only author of the repo, and I've no uncommitted/no unpushed changes, I just need one single command to do all of the job ( Since I already have the local repo, there is no need to `clone` it separately, with or without `mirror` like the first step in BFG) :

1. `git filter-repo --path "*.dll" --path "*.msm" --invert-path` 
2. `git push`

That's it.

Please confirm whether my understanding of filter-repo and BFG are correct or not?

**Comment by newren** [comment]
You have the basic idea correct, but there are lots of little details that I'm concerned you may have missed:
* Your command for filter-repo isn't going to do anything.  `--path` takes exact pathnames, so unless you have a file named exactly `*.dll` or `*.msm` in the toplevel of your repository, that command won't remove anything.  You probably meant to use `--path-glob`.
* Your step 2 for BFG preserves a bunch of dll and msm files as untracked files in your working directory.  You provided no equivalent with your filter-repo command; with it the dll and msm files will be nuked from both the history and the working directory.  If you're relying on the versions that exist in the working copy to be your backup, you'll be sadly surprised unless you made a copy first.  If you already have a copy of them somewhere else, then of course no extra work is necessary.
* `git push` tends to default to only push a single branch, rather than pushing all branches and tags, but to get rid of the history you need to push all the branches and tags that had the big files.
* `git push` will likely fail because you aren't pushing additions to the existing history, but a rewrite of the existing history; --force is required in such cases.
* `git push` is not sufficient for either command if the server has additional references to the old commits anywhere, such as code reviews or whatnot.  You may want to read through the [DISCUSSION section of the manual](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION) which talks about this in more detail.
* The filter-repo manual does not provide details about how to remove those commits on the server side, because the mechanism depends on what kind of access you have to the server.  In the case of GitLab, GitLab provides a special service you can use to tell it that you've done a local rewrite and upload information it can use to update those other references on the server.  See https://gitlab.com/help/user/project/repository/reducing_the_repo_size_using_git.md.  You'll note there are no filter-repo specific instructions on that page -- yet.  That's being addressed over in #98.  There are probably similar pages that exist for BitBucket, but I haven't gone looking.  (I know of the GitLab one because they contacted me recently with that other ticket I linked.)

Does that help?

**Comment by WindingWinter** [comment]
Thank you for your helpful comments:

1. Because my `DLLs` and `MSMs` are scattered in different directories and subdirectories, I think that using `--path-regex "*.dll" --path-regex "*.msm"` would be the way to go in order to filter off all the .dll and msm file, does `git-filter-repo` work that way?
2. You are right that I want to preserve the binary files on my local hard disk as untracked files. Is there any command in `git-filter-repo` that does that?
3. Using `git push --force` can only push to current branch, but let's say if I want to push to all branch ( as I want to rewrite all histories in all branches), how to do that?
4. Because I'm the sole author of the repo, and there is no code reviews and nothing else ( I just use it to store my build scripts and binaries, with occasional branching), I believe that the caveats in [DISCUSSION section of the manual ](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION) needn't apply, am I right?
5. As on the bitbucket server side, isn't it as simple as just running the [garbage collection](https://confluence.atlassian.com/bitbucketserverkb/how-to-perform-a-manual-garbage-collection-on-a-repository-867194296.html)? the equivalent page you link in gitlab doesn't seem to mention any extra steps beyond `gc`.

**Comment by newren** [comment]
Hi,

1. `--path-regex` requires that you pass a regex, not a glob, so the arguments you specify wouldn't work.  Either use globs e.g. `--path-glob "*.dll" --path-glob "*.msm"` or use regexes `--path-regex ".*\.dll" --path-regex ".*\.msm"`.  Either of those will match the .dll and .msm files in any directory.
2. Nope.  git-filter-repo pushes hard for people to only run on a new fresh clone so that if any filtering goes awry you can simply delete that copy and return to your other copies of the repository. 
 So, I'd suggest just having another clone around.  If you only want to have one clone with no backups, then you're running kind of risky.  But you could copy the .dll and .msm files somewhere else on your own pretty easily; something like `git ls-files "*.dll" "*.msm" | xargs cp -t /PATH/TO/BACKUP/DIR/` should do it.
3. git-filter-repo deletes origin as a remote, in part because of all the caveats and to remind you the history is no longer compatible.  So you can't push to "origin" after a filter-repo run, without re-introducing what origin means.  You could run `git remote add origin <url>` before running `git push --force --all origin`.
4. If you don't have code reviews or other developers, then yeah, the usual caveats probably won't apply.  I say probably because it's still possible the server decided for other reasons to create extra references (maybe someone has a fork of the repo and the server is sharing the history?  maybe it keeps extra references if comments in issue trackers refer to commits?).  A `git ls-remote` might help you verify, though the server doesn't have to advertise all its references (it most likely wouldn't in the case of a fork).
5. Yeah, it's basically just a garbage collection, after making sure that no old refs OR reflogs stick around anymore.  As to whether bitbucket gives you access to trigger that, I don't know.  It looks like you know more than me on that side of things for bitbucket.

**Comment by WindingWinter** [comment]
Thanks for the help.

> git-filter-repo deletes origin as a remote, in part because of all the caveats and to remind you the history is no longer compatible. 

Does this mean that git-filter-repo is very risky to proceed when the repo still has multiple active branches? 

> So you can't push to "origin" after a filter-repo run, without re-introducing what origin means. You could run git remote add origin <url> before running git push --force --all origin.

So effectively I would need to (re)add origin <url> all the time after I run filter-repo, for every use case? Because the origin won't be available anyway...

**Comment by newren** [comment]
git-filter-repo checks if your repo looks like a fresh clone and bails if it doesn't.  And if your repo is a fresh clone, then you obviously have a backup.  So, sure, it's risky, as mentioned upfront and center in the documentation, but it prevents most accidental usage from either brand new users trying it out without taking any safety precautions or more experienced users accidentally running from the wrong repository (as happened to me once -- I was grateful I had that guard rail in place).

The manual starts off with `This is a destructive operation which should not be used lightly`, and in the [Discussion Section](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION) adds `When you rewrite history, the old and new histories are no longer compatible; if you push this history somewhere for others to view, it will look as though you’ve done a rebase of all branches and tags. Make sure you are familiar with the "RECOVERING FROM UPSTREAM REBASE" section of git-rebase(1) (and in particular, "The hard case") before proceeding`.  If you are re-running filter-repo all the time, there's probably something wrong; why would you do that all the time?

Also, the discussion section of the manual lists a bunch of reasons why pushing back to the original repo after filtering is often a bad idea and repeatedly recommends pushing to a new, different repo.  It was you who mentioned you had a special case -- you're the only author, there are no other references in the central repo, etc, so I provided some tips for you to go down a path different than the documentation recommends.  I'm not going to document re-adding the origin url because that'd undercut the whole idea that the rewritten history is fundamentally different from and incompatible with the original.  There are so many cases where people try to rewrite all history, push it back to their original repository, and then someone else merges the rewritten branches with one of the original branches and ends up with two copies of all commits, and then you've got a much larger mess to try to clean up.

However, all that said, if you do have a special case where you want to repeatedly run filter-branch and don't like origin being removed, then read up more on the manual, specifically on the [Internals](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#INTERNALS) and notes on the `--partial` (and/or `--refs`) options.

Hope that all helps.
