### ISSUE TITLE
Issues with lock files on Windows

### ISSUE THREAD

**Issue by craigb** [newren/git-filter-repo#112]
```cmd
>git --version
git version 2.25.0.windows.1

>python -V
Python 3.8.3

>pip -V
pip 20.1.1

>pip list
Package         Version
--------------- -------
git-filter-repo 2.27.1
pip             20.1.1
setuptools      41.2.0
```
I'm running on Win 10, and I keep running into strange errors about being unable to create lock files.

> Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git update-ref failed; see above

Each time I try, it complains about a different lock file. When the command finishes, a grep in the .git directory shows no .lock files. Is this an issue you've seen before?

**Comment by newren** [comment]
Yep, almost certainly you have refs that differ in case only, e.g. one branch named 'release' and another one named 'Release'.  Your filesystem is unable to record both when both are updated.  In order to support rewriting history and preserving the ref names, you need to run the history rewriting on a filesystem that can record them.  Either that, or rename the refs before rewriting, or rename the refs as part of the rewriting.  Anyway, see issue #48 .

**Comment by craigb** [comment]
Thanks so much! I just used WSL to rerun the tool and it worked great.
