### ISSUE TITLE
Question : How to delete a directory at any path

### ISSUE THREAD

**Issue by SatyamBansal** [newren/git-filter-repo#114]
I want to delete "bin" directory available at any path inside my project. I have success in deleting files by specifying the exact path, but since I want to delete "bin" directory at any path, I just can't provide it. So i have tried using wild card with --path-glob as shown in examples, but no success. I have tried different matchers like "\*/bin" , "\*/bin/" etc with --path-glob and --path but nothing seems to work.
 
I have created a [test repo](https://github.com/SatyamBansal/bin-test) to specify my use case. I want to delete "bin" directory from "app" and "src" folders, and from history too.

Plz help , i just cant seem to figure it out.

**Comment by newren** [comment]
Yeah, the combination of the fact that filter-repo _only_ works on files, and the fact that fnmatch.fnmatch (the glob matcher in python) won't match unless you match the whole string combine to be slightly counter-intuitive.

In more detail, for your test repository, you have to specify matchers that match the subset of files you are interested in from the following:
```
app/app.txt
app/bin/bin.txt
main.txt
src/bin/bin.txt
src/test.txt
```

Also, in python,
  fnmatch.fnmatch('app/bin/bin.txt', '*/bin')
is False, but if you add an extra '/*' in there it matches.  So, you'd need a command like:
```
   git filter-repo --path-glob '*/bin/*' --invert-paths
```

If you also had a directory named 'bin' at the toplevel, then you'd need to extend this to
```
git filter-repo --path-glob '*/bin/*' --path bin --invert-paths
```
since the leading slash in '*/bin/*' will cause it to not match e.g. 'bin/fooey'.  The --path flag has special logic to allow it to match leading paths, but --path-glob does not.

**Comment by newren** [comment]
The previous comment explains how to do this with previously released versions of git-filter-repo.  I just pushed up commit 771404d656 (filter-repo: allow globs to match file or directory names, 2020-06-20) so that your `*/bin` will also work.

**Comment by SatyamBansal** [comment]
Thanks for the reply, it works just as you said. Since --path matches directories without any trailing slash, I thought it would work with --path-glob too, but since you specified that its special case, It all makes sense now. 
Thanks for the commit, I would definitely like to try it out but am not sure how to try it. I installed git-filter-repo via pip.
 Do I just need to upgrade the package via "pip3 install --upgrade git-filter-repo"?

**Comment by newren** [comment]
pip won't have a new version until the next time I make a release, which currently is scheduled for end of July.  Just use the trailing `/*` workaround until that time.

**Comment by SatyamBansal** [comment]
Ok, thanks for all the support
