### ISSUE TITLE
Unable to run "make snag_docs"

### ISSUE THREAD

**Issue by malkavsheir** [newren/git-filter-repo#152]
On my machine, i am unable to run "make snag_docs" nor am I finding any other alternatives to this. Can someone please post the .html file for Windows documentation as my ability to install some things is limited by my employer.

**Comment by malkavsheir** [comment]
This is similar to the issue in #140 except that I cannot follow the instructions to resolve.

**Comment by roccomoretti** [comment]
For some strange and inexplicable reason, the html and manpage docs are stored in a different branch in git: https://github.com/newren/git-filter-repo/tree/docs  -- The `make snag_docs` simply copies them from the other branch.

If you don't have git information ... say because you're using the released version ... then that won't work.

**Comment by newren** [comment]
How did you install/download git-filter-repo?

If you're using a released version, the documentation files are already included.  (e.g. https://github.com/newren/git-filter-repo/releases/download/v2.28.0/git-filter-repo-2.28.0.tar.xz already has the documentation in git-filter-repo-2.28.0/Documentation/html/git-filter-repo.html and git-filter-repo-2.28.0/Documentation/man1/git-filter-repo.1 when you unpack the tarball.)

If you cloned a copy of the repo, you can get the files from the docs branch as @roccomoretti explained.  (Thanks @roccomoretti!)  

One little note, though: placing the _generated_ html and manpage docs in a different branch is not inexplicable, and in fact has a clear precedent in that git.git does the exact same thing.  It would be weird to place sources together with the built version of the code, and so clearly I'm not going to do that.  Someone could build the manual pages from the sources under Documentation/ much as I do, but since most folks don't want to fight with installing asciidoc[tor] and whatnot, I build them as a convenience and place them in another branch.

**Comment by newren** [comment]
Oh, also worth noting is that the user manual is available by going to https://github.com/newren/git-filter-repo and clicking on "user manual" from "See the user manual."
