### ISSUE TITLE
--blob-callback won't let me include a newline in replacement text

### ISSUE THREAD

**Issue by larsks** [newren/git-filter-repo#153]
I want to transform this:

```
this is a test
```

Into this:

```
this is
a test
```

I couldn't get `--replace-text` to do it, so I thought maybe I could do it using `--blob-callback`, but this fails:

```
git filter-repo --blob-callback '
blob.data = blob.data.replace(b"this is a test", b"this is\na test")
'
```

That's perfectly fine Python, but in the context of `filter-repo` this results in the modified file containing a literal `\n`:

```
this is\na test
```

That was unexpected. Is there any way to make this work?

**Comment by newren** [comment]
Oh, boy, backslash interpretation...

What you are seeing is similar to the difference between the following two python commands:
   `print('this is\na test')`
and
   `print(r'this is\na test')`
The former has a newline in the middle while the latter has a backslash-n in the middle.  You specify the string to the shell, and it is passed along as a raw string to python.

So, you need to get a raw string with a newline in it, which is slightly painful.  Because it has an embedded newline, you also need to handle it slightly differently so that python compiles okay.  Something like the following gets close:

```
git filter-repo --blob-callback '
blob.data = blob.data.replace(b"this is a test", b"""this is
a test""")
'
```

I'll get back to the problem in a second.  If your shell is weird and doesn't like this, you might need to use other shell trickery to get the embedded newline, e.g.
```
git filter-repo --blob-callback "$(echo -e blob.data = blob.data.replace\(b'this is a test', b'''this is\na test'''\))"
```

In either case, though, git-filter-repo has to take some arbitrary string and insert it into a function and compile it.  Python will choke without proper indentation, so git-filter-repo takes anything you provide and inserts some spaces after every newline (see the make_callback() function), which will muck with your newline embedded within a string.

All of that basically means you should not use a command-line flag if you want to muck with newlines; you should write a little script instead like the ones in contrib/filter-repo-demos.  I know it's annoying to have to do that when you almost have a one-liner, but I can't think of how to make the --blob-callback do what you want otherwise here.  Sorry.

**Comment by newren** [comment]
I'll assume that answered the question and close this out; let me know if you still have questions about this.
