### ISSUE TITLE
How to modify a blob considering both its file path and data?

### ISSUE THREAD

**Issue by cirosantilli** [newren/git-filter-repo#158]
Full question at: https://stackoverflow.com/questions/64170064/how-to-modify-a-blob-considering-both-its-file-path-and-data-with-git-filter-rep

**Comment by newren** [comment]
Yeah, fast-export by its nature sends things in a stream, and blobs are sent without filenames.  When editing a commit object, you get filenames and sha1sums, but no contents of the file.  We do not store everything in memory simultaneously because the point is that the sheer number of files and file versions are likely to exceed available memory unless you have a small repository.  So, this kind of thing isn't naturally expressed in fast-export/fast-import (and thus filter-repo) syntax.

However, [contrib/filter-repo-demos/lint-history](../blob/main/contrib/filter-repo-demos/lint-history#L96) does precisely this in its lint_with_real_filenames() commit_callback.  It works based off filenames, then reads the contents via its hash using a separate cat_file_process, then modifies the contents, then creates a new blob using the modified contents and sets change.blob_id to the id of the new blob.

**Comment by cirosantilli** [comment]
Thanks for the reply, my question is answered.

Shame it has to be so ugly, I would guess that linting would be a major use case of this repo. But I understand why it's hard.

I wonder if it wouldn't be worth it to link only the newly added blobs to the commit object (supposing that they are adjacent on the stream, I'm not sure). This could be an optimization case for the lint script or for users that don't care about exact matches with old blobs.

Or even better, maybe we should patch git fast-export with a flag to always output blobs even if repeated.

Feel free to close this as you see better.

**Comment by newren** [comment]
Yeah, I know it's not the prettiest; sorry.  Your suggested idea is similar to one from @totph in #74 ; I can't quite do what you suggest here, but I may be able to tweak the idea -- create a convenience function the user can call to get the blob.  That's worth considering.

To address a couple of your other comments in case it's helpful...

As you note, making blob data adjacent would often require repeating blob data, possibly many times.  That's a bit wasteful.  Without repeating, blobs cannot be assumed to be adjacent at all; in fact, the fast-export stream is free to list all blobs before any commits are shown (and fast-import even suggests doing so when it's simpler for stream writers).  Even if we could assume blobs are repeated as necessary to enforce adjacency of blobs to commits that contain them, automatically loading all the new blobs for a given commit isn't necessarily a wise choice since even though any given file should fit in memory (or so I've assumed in git-filter-repo), we should not assume the combination of all new files within a commit simultaneously fit within memory.

Also, linting is certainly an understandable usecase as you mention, but that's precisely why I wrote contrib/filter-repo-demos/lint-history; people can just use it as-is.  (In fact, I've added features to it, unlike other contrib scripts, because many people have requested ways to do additional things.  And several others have contributed examples based on various versions of lint-history for doing extra stuff; links can be found by looking over the script).  I know that doesn't solve everything; however, if you need something more complex that's a mix of linting and something else, then that script at least provides example code for how to do that kind of task.

Anyway, since #74 already is open and discusses making it easier for scripts to access blobs, I'll go ahead and close this one out.

**Comment by cirosantilli** [comment]
Thanks for the info again. One thing that comes to mind is that maybe an optional convenient libgit2-based helper in the main library might be less scary than a separate git process ;-)
