### ISSUE TITLE
already_run skipping sanity_check is dangerous for the lint/refactor use case, destroys uncommitted/unstaged changes

### ISSUE THREAD

**Issue by cirosantilli** [newren/git-filter-repo#159]
As of 7b3e714b94a6e5b9f478cb981c7f560ef3f36506 , it seems that the following sequence of events could happen:

- use it for the first time for linting commits before pull request e.g. something along `git filter-repo --replace-text <(echo 'aaa==>bbb') --refs HEAD~..HEAD`. Refuses to run if you have any uncommitted changes. Good. Creates `.git/filter-repo/already_ran`.
- use it again on another pull request in the same repo. `already_ran` exists, so skips checks. Uncommitted changes are destroyed. Bad.

I wonder why not just just always run the sanity checks, would the performance hit be that big for any use case?

A related question: do we really need the check:

```
expected at most one entry in the reflog for
```

when using `--refs` for refactor/lint?

Because now I have to `--force` to get rid of that, but force would as expected also ignore uncommited/unstaged change checks, which I still want to run.

**Comment by newren** [comment]
Yeah, the sanity checks were written with full history rewrites in mind, and were written as check-if-this-is-a-fresh-clone type of checks, so anything that happened to be true of fresh clones were the things we wanted to check.  The already_run was needed because after any operation, the repository is clearly no longer a fresh clone but that shouldn't prevent people from doing their rewrite in multiple runs of filter-repo with different flags.

Partial history rewrites are a different beast, and it's not entirely sure what is correct there.  I'd probably have to think through the dozen or so checks and decide which to keep, though I worry the answer for many of them would be case dependent.  I could also avoid writing the already_run flag for a partial history rewrite, though that might make things infuriating for folks who want to do a rewrite in multiple steps as the changes they make in the first step could trigger the warnings/errors of subsequent steps and forcing them to always specify --force is annoying.

Maybe I should just add a suggestion to the documentation that you should not use the same repository for rewriting that you do for ongoing work; once you've done a rewrite, you should push your work somewhere and use a different clone for ongoing work.  That'd avoid this kind of problem, but I'm not sure those who do partial history rewrites want to work with different clones.

It's a bit of a sticky problem.

**Comment by cirosantilli** [comment]
Thanks for looking into this, Elijah.

I understand that error checking and catering for several different use cases is a complicated problem.

Feel free to do as you with with this ticket.

For me, the intended use case is refactoring of pull requests (copyright headers), which often include several commits and several files. I tend to leave copyright update to the last minute in case the review gets rejected/different files are changed so I don't waste time, and intend to use git filter-repo to do this last minute update in one go.

So using a separate repo for that would not be great :-)

For now I'm likely just going to add the unstaged change checks to my own script and always `.force = True`.

**Comment by newren** [comment]
So, I modified how the already_ran stuff works.  Not sure it actually solves your problem, but if the already_ran file is older than 24h, then a prompt is given to the user to ask whether to consider the rewrite a continuation of the previous one or a new rewrite.  That helps in the case that someone does a rewrite, goes on and does other work and forgets their previous rewrite, then goes to run the tool again.  It also allows people to do their rewrite in multiple steps as they are likely to run each of those steps within 24h.  Not sure if it helps you, but after a few years, that's the best I've come up with, so I'll go ahead and close out.  Glad that either way, you've found a workaround that works for you.

**Comment by cirosantilli** [comment]
Hi. Yes, feel free to close this, I managed what I wanted with `.force = True`.

A quick thought without looking into it, I would avoid having such opinionated defaults such as a 24h thing as a default safety timer on a low level tool like this. I'd do either full safety unless user specifies something, or no safety at all.  But I'm not looking into the details so might not be an useful idea.

And thanks for maintaining `git filter-repo`!
