### ISSUE TITLE
git-filter-repo freezes

### ISSUE THREAD

**Issue by grwkremilek** [newren/git-filter-repo#160]
I installed git-filter-repo on Win10 but when I try to run  "git filter-repo --path pom.xml --replace-text expression.txt", it freezes. Where is the problem?

**Comment by newren** [comment]
No idea; that's not enough information to pinpoint it.

Let's try to narrow it down.  First, the command you gave will likely be somewhat slow; --replace-text operates on all files (when blobs are provided in the stream there is no filename associated with them), and then --path will end up only picking the file named pom.xml.  So it'd be faster to do this operation as two separate invocations:
```
   git filter-repo --path pom.xml
   git filter-repo --replace-text expression.txt
```
Also, it might help us narrow down the freezing slightly by seeing which of the two above separated commands freeze.

Second, after you wait a while and it seems frozen, can you interrupt it (traditionally Ctrl-C from unix shells, or otherwise just delivering it a SIGINT), and see if it shows a python backtrace?  If so, can you paste that backtrace which may show where it got stuck?

Do you happen to have access to a Mac or Linux system where you can run this?  It might be interesting to learn whether this is operating system specific.

Also, is there a repository that someone else can run to reproduce this with and can you provide your expression.txt file?  I don't have access to any windows systems for testing, but if I can reproduce on another system or even be able to look at what might be special about a repository that triggers it or anything special in the expression.txt file I might be able to get some ideas.

**Comment by newren** [comment]
I'll go ahead and close out as there's been no answer in over a year.  I will state based on some other reports that I suspect usage of a bad python version, and that you may have needed to install python from the microsoft windows store.
