### ISSUE TITLE
Empty path component found in input

### ISSUE THREAD

**Issue by brainstorm** [newren/git-filter-repo#168]
```
% git filter-repo --path parallel_cluster --path-rename parallel_cluster: --force
Parsed 306 commitsfatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_25571
Traceback (most recent call last):
  File "/Users/rvalls/bin/git-filter-repo", line 3950, in <module>
    filter.run()
  File "/Users/rvalls/bin/git-filter-repo", line 3886, in run
    self._parser.run(self._input, self._output)
  File "/Users/rvalls/bin/git-filter-repo", line 1409, in run
    self._parse_commit()
  File "/Users/rvalls/bin/git-filter-repo", line 1260, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/Users/rvalls/bin/git-filter-repo", line 3439, in _tweak_commit
    aux_info['had_file_changes'], orig_parents):
  File "/Users/rvalls/bin/git-filter-repo", line 3201, in _prunable
    self._output.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by evazorro** [comment]
I just ran into this message as well, running `git filter-repo --paths-from-file ../files-to-rename.txt`. The problem turned out to be that one of my file renames accidentally started with a slash, e.g.:

```
some-directory/file.md==>/new-directory/better-file-name.md
```

This looks related to some other tickets I looked at, but in my case I was doing a rename and not trying to filter the repo to put a subdirectory at the root. Perhaps you could add an error message here that suggests checking for a leading slash?

**Comment by newren** [comment]
Not sure how this issue slipped through the cracks for so long; sorry about that.

>```
> % git filter-repo --path parallel_cluster --path-rename parallel_cluster: --force
>```

Right, so I'm assuming `parallel_cluster` is the name of a directory, and thus you might have paths like `parallel_cluster/src/main.c` in your repo (hypothetical example).  You want to have those translated to names like `src/main.c`, but your rename would instead give you `/src/main.c`, which git-fast-import will choke on because git only records things with paths relative to the root of the repository and so the leading slash looks like a leading subdirectory named '' (the empty string).

You need to instead use `--path-rename parallel_cluster/:`; note the slash before the colon.

However, there is a shorthand for this case that you might find simpler: --subdirectory-filter.  That'd simplify your command line down to
```
% git filter-repo --subdirectory-filter parallel_cluster --force`
```

because, as the docs say, `--subdirectory-filter FOO` is equivalent to `--path FOO/ --path-rename FOO/:`.

**Comment by newren** [comment]
> I just ran into this message as well, running `git filter-repo --paths-from-file ../files-to-rename.txt`. The problem turned out to be that one of my file renames accidentally started with a slash, e.g.:
> 
> ```
> some-directory/file.md==>/new-directory/better-file-name.md
> ```
> 
> This looks related to some other tickets I looked at, but in my case I was doing a rename and not trying to filter the repo to put a subdirectory at the root. Perhaps you could add an error message here that suggests checking for a leading slash?

Great suggestion, and I indeed added such an error message in commit 2833ef275f52 (filter-repo: throw an error if user specifies any path starting with a slash, 2020-05-16).  That should have been there about 6 months before your usage, but I understand that distros lag and you could easily have been on an older distro.  Sorry about that.

Anyway, as you probably already found out, you were really close, you just needed to remove the leading slash to make this be:
```
some-directory/file.md==>new-directory/better-file-name.md
```

**Comment by newren** [comment]
Looks like I answered this about a year ago but forgot to close; closing now.
