### ISSUE TITLE
Moving files from super-repo to submodule

### ISSUE THREAD

**Issue by mo2men1** [newren/git-filter-repo#17]
Hi,

I have a scenario were i've used this tool to separate a part of my project into a separate repo that's now included into my main project repo as a submodule.

Now sometimes i need to move files from the super-repo into the submodule including history related to these files. Along with all branches information and tags related to the files history.

What's the best approach to do this using this tool?

Right now my approach is the following:
1. Filter the files i want to move.
2. Add prefix to all tags.
3. Add the submodule's repo as a remote repo.
4. Sync all branches with the submodule remote repo.
5. Push all tags to the remote repo (which leads to some duplicated tags).

Thanks in advance.

**Comment by newren** [comment]
So...if I understand correctly, you had a repo with various disparate collections of files (perhaps which grow or are generated over time).  Since you had to repeatedly do this filtering operation, that kind of rules out the original files having been a subdirectory that you just split off and included as a submodule at the same path.  So, I presume you now have different paths for these files relative to the super-module since they are prefixed by the location of the submodule.

Further, you didn't just do one filtering operation, but did one to create a new repo (likely also doing another to remove those files from the original repo?), waited a while, did a new filtering operation to generate a new repo that you then merged (probably using --allow-unrelated-histories) with the first created repo (and maybe doing another at the same time to remove the second set of files from the main repo), etc.  

Am I getting this right so far?

I'm not sure why you need to do multiple distinct filtering operations and include all branches and tags each time, but presuming you really do want to do this, can you just use a different prefix for the branches and tags each time?  Then you don't run into duplicate tags.

I feel like there's a good chance I'm misunderstanding what you are trying to do; I definitely don't yet understand why you want to do it.  But hopefully that helps somehow.

**Comment by newren** [comment]
I'll assume this answered your question and close out; let me know if that's not the case.
