### ISSUE TITLE
fatal: No such remote: 'origin'

### ISSUE THREAD

**Issue by martinjost** [newren/git-filter-repo#171]
I've created a repo using 'git svn'.
I need to kick out some log files, with too big (and unneeded) history/pack-file.
At the same time, I want to keep the opportunity to 'git svn fetch' changes from SVN.  (This rules out a local 'git clone', because it doesn't copy the SVN info)
I copied the repo locally (cp -rp) to get a backup and then ran:
`git filter-repo --invert-paths --path log/... --force`
[--force, because without, filter-repo complained about the missing upstream 'origin' and similar)
This spit out: [My emphasis]
```
**fatal: No such remote: 'origin'**
Parsed 1800 commits
New history written in 1.21 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
Updating files: 100% (2672/2672), done.
HEAD is now at c0ba2d99 CS coop: added eCPRI_FCP promote jobs to coopListJobs
Enumerating objects: 29453, done.
Counting objects: 100% (29453/29453), done.
Delta compression using up to 32 threads
Compressing objects: 100% (3833/3833), done.
Writing objects: 100% (29453/29453), done.
Total 29453 (delta 25584), reused 29056 (delta 25187), pack-reused 0
Completely finished after 30.62 seconds.
```
The 'fatal' is worrying me. At the same time I understood https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#FRESHCLONE to the effect, that the pointer to --force is "just" to ask for a backup, but the tool should work nevertheless.
Do I need to worry about the error message ?
Does git-filter-repo need to split the error msg concerning '--force' to "real" problems versus "do you have a backup ?".

**Comment by newren** [comment]
Sorry for the scare; turns out the error was innocuous.  The code was running `git remote rm origin` and that subcommand was the one reporting the error, but the command exit status was ignored and the program continued.  Since that command should have been bypassed for your case, it ended up having no effect other than to scare you unnecessarily.

Anyway, I fixed the bug in e1b7c3d1eae4 (filter-repo: handle origin refs without origin remote, 2024-08-01).

Thanks for the report; sorry for taking so long to fix it.
