### ISSUE TITLE
Can't push to new Repository after Git-Filter-Repo

### ISSUE THREAD

**Issue by MarkusMiller** [newren/git-filter-repo#177]
Hello,

I've got a huge problem that already cost me 2 weeks now. 

I've got a deep learning project on a Gitlab server that unfortunately contained the 6 GB dataset as Git LFS content. The folder structure looks like this:
- root
  - dataset/
    - combined_dataset/[a lot of].jpg/png/csv
  - src/[srcfiles].jpynb
    - archive/[templates].jpynb
  - environments/[environmentfiles].yml
  - .gitignore
  - .gitattributes
  - Readme.txt

I tried several times to remove the git lfs files with git filter-repo --path dataset/*/*.* --invert-paths and any other combination, but the repository remained pretty much untouched. I then used a git filter-repo command with basically all files I wanted to keep (which actually did, what I wanted) but I was not able to push to a new repository after that, stating Git LFS would have missing or corrupt files. I then removed the dataset folder and its content from Git LFS and pushed everything successfully to a dump repository. This repository does not contain any Git LFS files (apart from gitattributes) anymore and I ran my git filter-branch command again and ended up with the same error: 

GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".

If I try that, I get:

LFS upload failed:
  (missing) src/0_Process_Dataset_Generate_CSVs.ipynb (2de73c639007254192c41d9b3233dd27c6795d815a315199b852563b8b3acbce)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: 'git config lfs.allowincompletepush true'
Uploading LFS objects:   0% (0/2), 0 B | 0 B/s, done.

Could you please tell me what steps are necessary to remove the dataset folder and its entire content and push the repo without losing the remaining history to a new repository?

Kind regards and thank you very much.

**Comment by MarkusMiller** [comment]
Can be closed now... Don't know what I did differently but it eventually worked...

**Comment by newren** [comment]
Glad you got it working.  The error message suggests that there was a file named `src/0_Process_Dataset_Generate_CSVs.ipynb` that wasn't a normal file but was tracked by LFS.  So, you'd need to remove it too.  Perhaps that's what you did in your extra steps.

If you run into this kind of thing again in the future, you may want to run `git filter-repo --analyze`, which will generate some reports giving a listing of historical files in the repository.  Sometimes that points out surprises that you didn't expect (e.g. there was a .ipynb file here when you claimed they were all .jpynb files), and gives you something extra to filter on.

Also, the command `git filter-repo --path dataset//.* --invert-paths` wouldn't be expected to match anything because of two reasons: (1) it looks like you are trying to use a regex with `--path`; that flag means to match the pathname exactly (i.e. if you had a file whose name was literally `/.*` within the `dataset` directory then it'd match), if you want to match using regexes then you should use `--path-regex`, (2) you have two slashes there instead of one which then can't match any filenames that'd be stored in git anyway.

Anyway, hope that helps you in the future or someone else that randomly comes across this report.  Glad you figured out how to get it working.

**Comment by MarkusMiller** [comment]
Thank you for your reply. 0_Process_Dataset_Generate_CSVs.jpynb was actually a source file and never managed by Git LFS, so it didn't make any sense receiving an error from LFS at all. 

The two slashes in dataset/... were created when posting the issue: it was meant to be slash-star-slash-star-dot but it falls back to the regex anyway. 

Thank you.

**Comment by newren** [comment]
`0_Process_Dataset_Generate_CSVs.jpynb` and `src/0_Process_Dataset_Generate_CSVs.ipynb` are different both because of the `src/` prefix and because the suffixes differ -- `.jpynb` vs `.ipynb`.  Perhaps you meant the file in the error message and just typoed it, but if not, is it possible one was a regular source file and the other was not?

If you meant that your command was `git filter-repo --path dataset/. --invert-paths`, that'd also not match anything because it's illegal to name files `.` (a single dot).  If you wanted to remove everything in the dataset directory, you should use  `git filter-repo --path dataset/ --invert-paths`.

Anyway, again, I'm glad you've got it working, just hoping that the hints above come in handy or help explain things you're curious about.
