### ISSUE TITLE
An installation guide that makes sense for windows users

### ISSUE THREAD

**Issue by PaulVrugt** [newren/git-filter-repo#189]
I've been trying to use git-filter-repo on windows, but hints on how to install it on windows are scattered around the internet. It would be very nice to have a simple step by step guide on how to install this tool on windows.

I've managed to use `pip` to use python (which is not a really common tool to use for windows users) to install git-filter-repo on my machine, but I've been unable to get git to recognize the `filter-repo` command

**Comment by newren** [comment]
Did you look through the "NOTES for windows users" under https://github.com/newren/git-filter-repo/blob/main/INSTALL.md?

If so, the best I can do is ask for volunteers to write such an installation guide, as I have no windows machines myself, but the three links in that section appear to be cases where others have done so, documenting the problems and their fixes.

**Comment by newren** [comment]
[I updated the INSTALL.md file](https://github.com/newren/git-filter-repo/blob/main/INSTALL.md#simple-installation) to point out that folks can just run `python3 git-filter-repo` instead of trying to get `git filter-repo` to work.  Don't know why Windows makes it so difficult to make the short form magic work, but it's really not necessary.
