### ISSUE TITLE
Can't get it to work on Windows

### ISSUE THREAD

**Issue by Slion** [newren/git-filter-repo#193]
All I get is `error: cannot spawn git-filter-repo: Exec format error`.
Used Python as provided from Microsoft Store.
Installed git-filter-repo using pip.
Copied script to git folder.
Try run it.
Get error mentioned above.

Tried to change the shebang line, no joy.

**Comment by Slion** [comment]
Shebang: `#!crap`
Result: `error: cannot spawn git-filter-repo: Exec format error`

Shebang: `#!C:\Users\username\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe`
Result: `error: cannot spawn git-filter-repo: Exec format error`

Shebang: `#!/usr/bin/env python`
Result: `/usr/bin/env: 'python': Permission denied`

**Comment by Slion** [comment]
Shebang: `#!crap`
Result: `error: cannot spawn git-filter-repo: Exec format error`

Shebang: `#!C:\Users\username\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe`
Result: `error: cannot spawn git-filter-repo: Exec format error`

Shebang: `#!/usr/bin/env python`
Result: `/usr/bin/env: 'python': Permission denied`

**Comment by newren** [comment]
Did you read https://github.com/newren/git-filter-repo/blob/main/INSTALL.md (linked to from the main page) and particularly the NOTES for windows users?  Did you try things mentioned in the three links from there?

**Comment by Slion** [comment]
> Did you read https://github.com/newren/git-filter-repo/blob/main/INSTALL.md (linked to from the main page) and particularly the NOTES for windows users? Did you try things mentioned in the three links from there?

I did read through those yes. Did not help though. I did a rebase instead 😁

**Comment by devkoa** [comment]
Hello there, @Slion you are not right, it works in Windows. In my case i have hundred of git repositories, and i develop and test in Windows system. And i have a quite complex setup. I run python code, i generate a shell script and the shell script calls the git-filter-repo, and all this works well in Windows. So i dont see any issue here. 
@newren Thanks, great work.

**Comment by SteveBenz** [comment]
I haven't figured this all the way out, but in Python 3.9.0, which is the one I downloaded from python.org (not the windows store version), it seems that the default instructions of replacing:

#!/usr/bin/env python3

with whatever your version of python is (e.g. mine is 'py'), resulting in:

#!/usr/bin/env py

Don't quite work because I'm pretty sure that 'py' is itself interpreting the '#!' and launching another 'py' process, leaving the machine with an infinitely growing list of 'py' processes...  One would think that the way to fix it would be to add '-x' to the shebang line (which causes python to ignore the first line of the file), but I still haven't managed it.

**Comment by Andrefei** [comment]
@SteveBenz  Probably way to late to help you, but as a Windows user I also struggeled for hours trying to get this to work. I entered the same trap as you mention by changing the shebang to `#!/usr/bin/env py`. Ended up crashing the dev environment as I did not realize my mistake until it was too late... Don't know if this issue is worth adding somewhere @newren 

Anyways, what ended up working for me was changing the shebang to `#!/usr/bin/env python` and running `git filter-repo` through the **Anaconda PowerShell Prompt in Administrator mode** as mentioned in #36. I am wondering if this solution could work in a general case, as the Anaconda PowerShell _should_ reach you Python installation in a similar way regardless of installation method or version.

**Comment by ViliusS** [comment]
@Slion try changing shebang value to `#!\python.exe`
Worked for me.

**Comment by newren** [comment]
[I updated the INSTALL.md file](https://github.com/newren/git-filter-repo/blob/main/INSTALL.md#simple-installation) to point out that folks can just run `python3 git-filter-repo` instead of trying to get `git filter-repo` to work.  Don't know why Windows makes it so difficult to make the short form magic work, but it's really not necessary.
