### ISSUE TITLE
bfg-ish --filter-content-including path/to/file does not work

### ISSUE THREAD

**Issue by pberndt** [newren/git-filter-repo#204]
In the help it says
eg '*.{txt,properties}'

but I would expect the following to work, too:

path/to/file
path/to/*.txt

And maybe even double-glob:
path**txt

I believe limiting replacements to subdirectories as well as individual files is quite important and I had been hoping I could do it with bfg-ish at least. See #74

**Comment by newren** [comment]
bfg by its design only works on basename of files; you can't specify leading directories at all.  bfg-ish, since it's designed to copy bfg, does the same.  (See the first three sentences of https://github.com/newren/git-filter-repo/blob/main/Documentation/converting-from-bfg-repo-cleaner.md#basic-differences and https://github.com/rtyley/bfg-repo-cleaner/issues/79)

If you want to specify directories, use filter-repo.
