### ISSUE TITLE
History is filtered in a surprising way if range is passed to --refs

### ISSUE THREAD

**Issue by DmPanov** [newren/git-filter-repo#211]
Following script rewrites all history to `foo/bar` directory as expected:
```bash
set -e
git clone https://github.com/newren/git-filter-repo.git
cd git-filter-repo
git branch --force tmp main
git-filter-repo.py --refs tmp --force --path-rename :foo/bar/
```
But if range is specified:
```bash
set -e
git clone https://github.com/newren/git-filter-repo.git
cd git-filter-repo
git branch --force tmp main
git-filter-repo.py --refs tmp~9..tmp --force --path-rename :foo/bar/
```
then outcome is puzzling:
![image](https://user-images.githubusercontent.com/37106163/109208850-e46efa00-77bb-11eb-8b64-59526ccafa6e.png)
Some files are copied to `foo/bar` but root directory still contains files besides `foo` like `contrib`, `Documentation` etc. Is it a bug or am I misinterpreting the docs? Thanks!

**Comment by newren** [comment]
Yeah, any files modified by the commits in the range `tmp~9..tmp` would be duplicated with the contents of the file as of `tmp~9` in the old location and the contents of the file as of tmp appearing at the new file path.  Any files not modified by the commits in the range `tmp~9..tmp` would just be left where it was.  Any files new since `tmp~9` would appear in the new location only.

It's all an artifact of how fast-export and fast-import work -- see https://github.com/newren/git-filter-repo/issues/50#issuecomment-578340676, especially "So, filter-repo works well for things like removing a file entirely, but if you want to make any tweaks to any files you have to make the exact same tweak over and over for every single commit that touches that file."

**Comment by DmPanov** [comment]
I think I got it. Thank you for the explanation!
