### ISSUE TITLE
Understanding impact of use on existing tags, releases and forks

### ISSUE THREAD

**Issue by omriharel** [newren/git-filter-repo#212]
Hi there,

This seems like an incredibly useful tool for me, but I was unable to find information about the consequences of rewriting history for a GitHub project with many forks - as well as existing tags and releases.

My project has about a hundred different forks (from different points in time), and includes a gallery of community-made designs. I made the mistake of not resizing and recompressing pictures of those designs before committing them, so now I have about fifty ~4-6MB files that every using cloning my project (or one of its fork) is forced to download. My plan is to compress all of them down to reasonable sizes, but the old copies would still live in history.

So this tool would easily get the job done as far as deleting those old large copies, but:

- I'm afraid that all existing forks wouldn't retain their linkage to existing commits (or to my original project)
- I don't know how tags (and GitHub releases that auto-include source code zips from their point-in-time) would be impacted
- I don't fully understand the consequences of rewriting history for a project with a potentially large number of downstream forks

I tried searching specifically how usage of this tool would impact forks, but I was unable to find that information.

Thanks for reading, I appreciate any insights you might have!

**Comment by newren** [comment]
Are these forks as in someone just made a copy, or forks as in repository manager tool (e.g. GitHub/GitLab) treats them in some special manner?

If someone just made a copy, your rewriting of history still leaves them with their original copy.  The same can be said for anyone who cloned your repo; they still have the original, and they could fetch from your repo, merge the two unrelated histories together, and end up with a big mess where it looks like there are two copies of each commit (one that contained the old uncompressed images somewhere in their history, and the other that doesn't), and then push the result somewhere.

As for how GitHub or GitLab manage their "forks", it partially depends on how they represent it.  If they mostly just use alternates, as I suspect, then it basically just looks like you've force-pushed new history to your repository, and the forks still are using the old history until someone manually updates them.

As for tags, filter-repo rewrites those too.  If you don't push the new tags up to your repo or at least delete the old ones, then your repository will contain a copy of both the old and the new history, essentially doubling the number of commits.  If you do push up the new tags, then you still run into the problem that anyone who cloned the repo won't automatically get the new tags.  git fetch/pull ignores updated tags because it doesn't want people rewriting history without folks knowing.  See the git-tag manpage.  So you'll need to inform anyone who cloned to delete their tags before refetching.  Forks will probably just extend this problem so that you need to tell not only folks who cloned your repo, but everyone who forked your repo, and tell all the forkers to let anyone know who cloned their repo about this need to delete tags and refetch after rewriting history.

As far as GitHub releases go, I have no clue; you'd have to ask GitHub what they do if you force-push modified tags.

Much of this is discussed in the "DISCUSSION" section of the manual -- see https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION.  I think forks just means you have a lot more copies and people to sync with.

**Comment by omriharel** [comment]
Hi @newren, thank you for your detailed response.

I did mean forks in the GitHub/GitLab sense, but it's true that effectively they're just point-in-time clones of the base repository. Unfortunately I won't be able to rely on everyone who owns one of these copies to be able to re-align correctly.

I'll look into whether GitHub has any documentation pertaining to repository cleanup and evaluate my options based on that.

Thanks again for your help!
