### ISSUE TITLE
Manual is far less accessible than a README

### ISSUE THREAD

**Issue by jerkstorecaller** [newren/git-filter-repo#215]
Thanks for this great tool. It helps me make important changes without having to understand git.

Some criticism: I can't click the link to the manual from the README, Github shows it as a HTML/XML file with all the markup.

So I have to:

1. clone git-filter-repo
2. where's the bloody doc?
2. oh, I have to checkout the docs branch
3. Here we go...oh, huge dump of HTML files
4. no index.html . Oh no, what do I do? I guess I have to go through all these filenames
4. Oh, it's called user-manual.html. At the very bottom of the list.

I don't see why you'd go through all this effort of writing a manual and then make it so hard to read? Would've been better for everyone if you just had some more Markdown files we can click from your github. 

One improvement that can be done right now is renaming it to index.html. That's what people look for in a directory full of HTML files.

I know, I know, first world problems. :)

**Comment by newren** [comment]
git.git uses asciidoc for all its documentation, from which it generates manpages, pdf manuals, html copies, etc.  It also makes sure to only track _source_ code, not build artifacts in the repository -- but it creates a separate branch for hosting documentation manuals since not everyone has the necessary asciidoc tools.

I wanted to make it easy for git-filter-repo to be included in git.git and use all the same tools git.git does.  Then git's distribution channels and documentation locations would become the same ones git-filter-repo would use, and I could nuke this repository.

But then my biggest proponent of adopting this tool into git went inactive in the git community.  Others preferred to stop accepting new tools into git.git and even kick some of the existing ones out instead, and we ended up here.  Sometimes things change, though, and I didn't want to close the door to inclusion.  So, here we are...
