### ISSUE TITLE
[question] How to remove history before a specified commit?

### ISSUE THREAD

**Issue by mreiche** [newren/git-filter-repo#218]
I want to publish my project to GitHub and I did a lot of cleaning the last months, refactoring and so one.
But I cannot find a properly way to remove all commits before a specified commit id.

What I tried:
```shell
git filter-repo --replace-refs delete-no-add --refs $COMMITID..master
```

I also tried some grafting, but I think replacing commits is not what I need here.
I also tried shallow copies and rebasing, but both does not really fit my needs, since I have several branches to push.

**Comment by gmikhaile** [comment]
You should try doing it with `commit_callback` by reparenting `a specified commit id` to `[ ]` :
```
filtering_options = git_filter_repo.FilteringOptions.default_options()
filtering_options.source = b'Path to git repo'
filtering_options.target = b'Path to res output'
filtering_options.force = True
filtering_options.replace_refs = "update-no-add"

repo_filter = git_filter_repo.RepoFilter(
        filtering_options,
        commit_callback=remove
    )
repo_filter.run()


def remove(commit, metadata):
    if commit.original_id == b'a specified commit id':
        commit.parents = []
```

**Comment by newren** [comment]
What do you mean by removing history before a specified commit?  Do you mean that you want all history before that point squashed into that commit, with the rest of history being added on top?  If so:

git replace --graft $commit
git filter-repo --force

Do you mean that you want all history before that point completely expunged?  This is only possible if that commit and all commits after it do not modify any files that existed before that point.  And if this is what you want, filter-repo is the wrong tool for the job; you'd need to use git rebase.

**Comment by mreiche** [comment]
> What do you mean by removing history before a specified commit? Do you mean that you want all history before that point squashed into that commit, with the rest of history being added on top? If so:
> 
> git replace --graft $commit
> git filter-repo --force

Ja, this is exactly what I also tried already. But I expect the history to be gone. But I still can find and diff commits before `$commit`.

**Comment by newren** [comment]
Do you have branches or tags that point to commits that do not include that commit?  If you do, since they don't include that commit the rewriting don't cause those branches or tags to change.  If you don't want those branches or tags, then you'd need to delete them.  If you do want those branches and tags...what exactly should happen given that the only commit you are changing isn't in their history?

**Comment by mreiche** [comment]
I checked that commit is part of all branches and tags.
```shell
git branch --contains $commit
git tag--contains $commit
```
I also tried to delete all branches and tags except master. I can still see logs an diffs before `$commit`.

But what now changed is:
```shell
$ git replace --graft $commit
error: could not parse $commit
```

Maybe there is just a git log cache I need to rebuild?

**Comment by newren** [comment]
> Edit: It looks like that it worked. Because every diff before that commit now shows me the squash diff.

Right, git-filter-repo creates a mapping of old commits to new commits, so that people can still use old commit ids to refer to new commits.  `--replace-refs --delete-no-add` can turn that off (or you can delete all the refs/replace/* refs afterward), but it doesn't mean the repo still has the old commits, just that their ID has been mapped to new commits.

Anyway, glad it's working for you.

**Comment by mreiche** [comment]
Thanks for the hint!
