### ISSUE TITLE
git-filter-repo hangs on Windows, works on Ubuntu (WSL2)

### ISSUE THREAD

**Issue by kaby76** [newren/git-filter-repo#232]
I'm trying to split up a small git repo using this tool, and I'm having difficulty with it. Here is a script that I run that hangs on Windows Msys2 64-bit.

	set -x
	rm -rf tools

	# Split the Antlr4BuildTasks repo into
	# "tools" for dotnet tools,
	# "msbuild" for the msbuild tool.

	# tools
	time git clone https://github.com/kaby76/Antlr4BuildTasks.git tools
	cd tools
	time git filter-repo --path csxml2/ --path dotnet-antlr/ --path dotnet-antlr-test/ --path .gitignore --path clean.sh --path license
	cd ..

What I'm seeing is the "git filter-repo" command hanging. I notice that there are three processes spawned with the last git command, which is the actual command that hangs:

    c:\msys64\usr\bin\git.exe filter-repo --path csxml2/ --path dotnet-antlr/ --path dotnet-antlr-test/  --path .gitignore --path clean.sh --path license
   c:\msys64\usr\lib\git-core\git.exe pack-refs --all --prune
    git gc --prune=now

I'm not sure why the last process in this list is "git" vs "c:\msys64\usr\bin\git.exe. That seems different, and likely the problem because it may then be trying to execute the wrong git.

Other info: "which git" outputs /usr/bin/git. "git --version" outputs "2.30.0". "python --version" outputs Python 3.8.7. When I kill the process in Msys2 bash via control-c, the process tree is not entirely killed: the middle of the three processes that I list above is not killed, and it is marked "Suspended". 

On Ubuntu WSL2 this works fine. In fact, this is a great, indispensable tool. Well done.

**Comment by newren** [comment]
I don't have access to a Windows system, and the hanging sounds a bit weird to me, but looking at this ticket yet again I'm reminded of https://github.com/newren/git-filter-repo/issues/36#issuecomment-568933825.  I also know that Git for Windows fixed a few issues relating to running Python in its recent release.  Does a newer version of Git for Windows fix this for you?  If not, does the other comment I linked help at all?  (I hope so, because I don't have any other ideas...)

Glad you at least got this working under WSL, though it would be nice to have it working outside WSL as well.

**Comment by newren** [comment]
No response; I'll go ahead and close.
