### ISSUE TITLE
Undo git-filter-repo --path?

### ISSUE THREAD

**Issue by avakiai** [newren/git-filter-repo#238]
Hi, I wanted to filter a particular file from my repo but I accidentally hit enter before I added the --invert-path tag. Now I effectively filtered the whole repo aside from the file I had wanted to remove. 

Is there any way to recover the repo? 

With git filter-branch it seems that backups are created that [can be recovered via git reflog,](https://stackoverflow.com/questions/14542326/undo-git-filter-branch) but that command brings up nothing. 

Any help?

**Comment by newren** [comment]
The recovery mechanism for filter-branch was problematic if you needed to recover lots of refs, and didn't store an actual correct backup for annotated tags in various cases.  That mechanism also caused no end of frustration for folks that wanted to delete the old stuff and shrink their repositories.  filter-repo went a different route and encouraged folks to only run on fresh clones, because then it was free to just automatically shrink the repository instead of making users run lots of extra steps, and if anything went amiss users could simply reclone the repo.  And, as the very beginning of the `git filter-repo -h` help message says,

> git-filter-repo destructively rewrites history (unless --analyze or
> --dry-run are given) according to specified rules.  It refuses to do any
> rewriting unless either run from a clean fresh clone, or --force was
> given.

If you ignored this, since filter-repo automatically deletes the old history, no recovery is possible (short of trying to "undelete" all the files, particularly under .git/objects/, that the calls to git gc deleted).  But if you followed the instructions, you can just delete whatever clone you are working in and simply reclone it.

**Comment by ThePredators** [comment]
> The recovery mechanism for filter-branch was problematic if you needed to recover lots of refs, and didn't store an actual correct backup for annotated tags in various cases. That mechanism also caused no end of frustration for folks that wanted to delete the old stuff and shrink their repositories. filter-repo went a different route and encouraged folks to only run on fresh clones, because then it was free to just automatically shrink the repository instead of making users run lots of extra steps, and if anything went amiss users could simply reclone the repo. And, as the very beginning of the `git filter-repo -h` help message says,
> 
> > git-filter-repo destructively rewrites history (unless --analyze or
> > --dry-run are given) according to specified rules.  It refuses to do any
> > rewriting unless either run from a clean fresh clone, or --force was
> > given.
> 
> If you ignored this, since filter-repo automatically deletes the old history, no recovery is possible (short of trying to "undelete" all the files, particularly under .git/objects/, that the calls to git gc deleted). But if you followed the instructions, you can just delete whatever clone you are working in and simply reclone it.

You should add a big warning to new comers that the command cannot be reverted !!!! this is insane that a tool like this is out there and no backup is made by it when doing such a process !!! Shame !!!

**Comment by newren** [comment]
> You should add a big warning to new comers that the command cannot be reverted

That is what `destructively` means in the text you highlighted.

Further, if you run on a repository that does not look like a fresh clone, the command prints:
```
Aborting: Refusing to destructively overwrite repo history since
this does not look like a fresh clone.
  <further detail about why it appears not to be a fresh clone>
Please operate on a fresh clone instead.  If you want to proceed
anyway, use --force.
```
And, the `--force` flag is documented as
```
Rewrite repository history even if the current repo
does not look like a fresh clone.  History rewriting is
irreversible...
```

If I had to guess, you decided to work on a repository that you had no backup or clone of, copy & pasted an example command that used `--force`, did not check what the `--force` flag or any of the other flags were documented to do, and did not verify that the online example only made the changes that you wanted before running it.  That's gotta hurt.  It's no fun to be in that situation.  But I had three levels of big warnings that you simply bypassed.  Much like `rm -rf ${DIRECTORY}`, there exists good reasons to allow such commands to exist and they have good use, but they can certainly be misused.
