### ISSUE TITLE
False-positives in suboptimal-issues

### ISSUE THREAD

**Issue by neon-dev** [newren/git-filter-repo#243]
First thank you for this awesome tool.

I found that there are alleged commit references listed in suboptimal-issues which weren't ones in the first place.
This happens for long numbers in commit messages, but also with hashes in links to commits of another repo.

Looks like those Regex matches aren't filtered by the set of pre-rewrite commit hashes.

**Comment by newren** [comment]
Thanks for the report.  There's nothing to change here, though; filtering by the set of pre-rewrite commit hashes wouldn't be appropriate.  The inability-to-rewrite-possible-commit-hash is there both because of the possibility of collisions with abbreviated hashes, and because the original repo may have references to commits that didn't (any longer) exist within the repo.  For example, if someone is creating some patches on a branch, cherry-picks one of those elsewhere with the -x option (so that there is a "cherry-picked from <hash>" notice included in the commit message), and then either never pushes the original patch or rebases it to change its ID, then you run into a problem like this.  That's happened a lot in various repos I've seen, and this suboptimal check lets the users at least know about it and decide if they want to take further action to try to clean up the resulting commit message.

**Comment by neon-dev** [comment]
Got it, makes total sense.

**Comment by rmacklin** [comment]
An interesting set of false positives I ran into was caused by commit messages that include a link to an image hosted on githubusercontent.com (which are easily generated by uploading or pasting an image into a comment textarea on a GitHub issue or pull request), like this one:

https://user-images.githubusercontent.com/1863540/230745988-10da1561-d8f6-44dc-ae73-5864f133c7c7.png

The `suboptimal-issues` report includes four substrings from that URL (`1863540`, `230745988`, `10da1561`, and `5864f133c7c7`), which of course are all false positives.

I'm not sure how common this is for other folks, but it's a somewhat frequent thing in repos I've worked on when we feel it's helpful to reference an image/screenshot while describing a commit.

Another set of false positives I came across was in commits generated by [applying a suggestion on a GitHub pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) if the user who made the suggestion has opted into the ["Keep my email addresses private"](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) setting. In that case, the commit message will include a trailer that looks like:
```
Co-authored-by: Name Here <USER_ID+username@users.noreply.github.com>
```
where `USER_ID` is an integer id like `1863540`. So any of those `USER_ID` values will be included as false positives, too.

I understand @newren's reasoning in https://github.com/newren/git-filter-repo/issues/243#issuecomment-858106640 for the current behavior. But I do wonder if perhaps it could be valuable for git-filter-repo to accept regexes that can be ignored (such as `\d+[+][^@]+@users.noreply.github.com`) when generating this section of `suboptimal-issues`:
```
The following commits were filtered out, but referenced in another
commit message.  The reference to the now-nonexistent commit hash
(or a substring thereof) was left as-is in any commit messages:
```
