### ISSUE TITLE
--commit-callback - delete file fails

### ISSUE THREAD

**Issue by galsi** [newren/git-filter-repo#26]
Hi
i getting following error when trying to delete file file using the commit-callback

` git filter-repo --force --commit-callback "if not commit.parents:commit.file_changes.append(FileChange(b'D', b'$(git hash-object -w '.tfignore')' ,b'.tfignore', b'100644'))"`

```
Traceback (most recent call last):
  File "C:/Program Files/Git/mingw64/libexec/git-core\git-filter-repo", line 3840, in <module>
    filter.run()
  File "C:/Program Files/Git/mingw64/libexec/git-core\git-filter-repo", line 3777, in run
    self._parser.run(self._input, self._output)
  File "C:/Program Files/Git/mingw64/libexec/git-core\git-filter-repo", line 1396, in run
    self._parse_commit()
  File "C:/Program Files/Git/mingw64/libexec/git-core\git-filter-repo", line 1249, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "C:/Program Files/Git/mingw64/libexec/git-core\git-filter-repo", line 3328, in _tweak_commit
    self._commit_callback(commit, self.callback_metadata(aux_info))
  File "<string>", line 2, in callback
  File "C:/Program Files/Git/mingw64/libexec/git-core\git-filter-repo", line 583, in __init__
    assert id_ is None and mode is None
AssertionError
fatal: stream ends early
```

**Comment by newren** [comment]
FileChange expects information about the contents that the file is going to have, not what it used to have.  Since a deleted file has no hash or mode, those should not be passed.  (You may also want to check out the fast-import documentation, which shows that for filemodify it needs the M character, the filename, the mode, and the hash, but for filedelete it only needs the D character and the filename; filter-repo is basically just glue between fast-export and fast-import allowing you to quickly set up the needed fast-import stream.)  But what's worse here is that you decided to pass the hash as the second object to the FileChange constructor; that's rather perplexing.  No example does that, neither for deleted nor modified files.  And if you check out the function signature, indeed the filename is always expected to be the second parameter.

It is hard to catch all mistakes, but the few places where it is easy I have assertions in the code.  If the code dies with an AssertionError that is directly in git-filter-repo source, as has happened here, then you've violated a basic assumption.  The traceback will even tell you the line number, e.g. line 583 here.  (And if you want more context, the previous line shows in what function and line the code was at before it called the function that had the assertion error.  And the line before that shows where that function was called, and so on.)

Anyway, hope that explanation helps you not only fix this issue but understand a little bit how to debug and work out other issues.

**Comment by galsi** [comment]
i am sorry to waste your time , in any way thanks for all your explanation.

**Comment by newren** [comment]
Sorry if I came across as short; didn't mean to.  Maybe a side-effect of waking up sick this morning.

**Comment by galsi** [comment]
Hope you feel better
just wanted to thank you for a great tool
compared to filter branch
**Big Repo 11GB
125000 commits**
Add files to commits
Filter-Repo ~ 1000Sec 
Filter-Branch ~ 105000Sec
