### ISSUE TITLE
`--refs` requires references that exist

### ISSUE THREAD

**Issue by BatmanAoD** [newren/git-filter-repo#264]
I tried to use `--refs` to modify a feature-branch. In order to avoid needing `--force`, I didn't check the feature branch out, so `HEAD` was the default branch (`main`).

With a command like this:

```
git filter-repo <filters> --refs main..my_feature
```

I got an error message like this:

```
fatal: ambiguous argument 'main..my_feature': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Because `--` is suggested as a solution, I'm assuming that this error message comes from one of the built-in `git` commands.

Once I checked out the `my_feature` branch and added `--force`, the command appeared to work more or less as expected. (I had some issues with the actual rewrite, but I'm pretty sure those are user-error.)

I'm not sure how to classify this issue (i.e. bug, missing feature, or just a poor error message). But it seems to me like the `--refs` invocation should be able to handle refs that aren't currently reachable from `HEAD`, or if it can't, maybe suggest checking out the relevant branch in either the error message or the documentation. I checked through the issues list (open and closed) and didn't see anything terribly similar, so I don't think this is a duplicate.

The output of `git filter-repo --version` is `10401e45d5f0`, so unfortunately I'm not sure how out of date it is.

**Comment by newren** [comment]
Sorry for the long delay.

In this case, it sounds like you didn't have a local `my_feature` branch when you started (likely just a origin/my_feature remote tracking branch), but attempting to check one out makes git go looking for one, finding that it doesn't match anything but there is an origin/my_feature, and creates one based off of that.

In such a case, `git log main..my_feature` _also_ would have failed until you created the my_feature branch.  So, it doesn't really have anything to do with needing the branch to be checked out, just that it needs the branch to _exist_.  The reason checkout doesn't need the branch to exist before checking it out is that it has some magic for creating them -- but that magic isn't shared by other git commands like log or fast-export.  You could have used `--refs main..origin/my_feature` or fully qualified as `--refs main..refs/remotes/origin/my_feature` in order to have it working without checking out the branch.  (Same for making the `git log` command work, by just specifying the existing remote tracking branch.)

I'll go ahead and close out, but let me know if any of this is unclear.  Sorry again for taking so long to respond.

**Comment by BatmanAoD** [comment]
Yes, sorry for not making it more clear; I realize the issue is not about what the current branch is but which tag/branch names exist in the "working tree". (I guess "reachable from HEAD" isn't actually correct either, though.) I think needing to specify `<remote>/` for any non-default branch makes sense, but the issue I see is that there isn't much in the documentation or the error message to guide users to this solution. The mention of "working tree" suggests that a local tracking branch is required, which forces users to employ `--force`, and the bit about `--` is simply a red herring. Like I said, I realize these messages are coming from other `git` commands, but I was hoping they could be captured, suppressed, and replaced with something more helpful for this use-case. Even without modifying the error message for unrecognized names, I think it would be helpful for the documentation to explicitly call out that `--refs` won't automatically look for branches that only exist in remotes, but it will accept `<remote>/branch`. The sections on `--refs`, `--partial`, and "fresh clone safety" all seem to me like appropriate places to call this out.

> Sorry for the long delay.

No problem!
