### ISSUE TITLE
When removing a file it gives no errors but does not remove history (and deletes remote config on local repo)

### ISSUE THREAD

**Issue by slemme1** [newren/git-filter-repo#267]
git filter-repo --invert-paths --path VHI/mfacctreset/deploy/deploy_desc.xml --debug 
On Windows tried Git 2.31.1 and 2.32.02, using Python 3.6.0
--dry-run option shows commits for the specified file removed in fast-export.filtered but when run the history remains in the repo.
Also after it is run, git remote -v shows NO entries

**Comment by Marcono1234** [comment]
> Also after it is run, git remote -v shows NO entries

This is indirectly documented in the [manual](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#_miscellaneous_options); the description for `--partial` says:
> disables removing of the `origin` remote

And section [How filter-repo works](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#_how_filter_repo_works) has as step 3 `git remote rm origin`.

Though personally, I think this should be made clearer. Probably related to #115.

**Comment by newren** [comment]
Sorry for taking so long to get back to you.

> git filter-repo --invert-paths --path VHI/mfacctreset/deploy/deploy_desc.xml --debug On Windows tried Git 2.31.1 and 2.32.02, using Python 3.6.0 --dry-run option shows commits for the specified file removed in fast-export.filtered but when run the history remains in the repo.

That's quite curious.  How did you check that the history remains in the repo?  Did you do something like `git log --all --raw --source -- VHI/mfacctreset/deploy/deploy_desc.xml` afterwards and you were shown commits that modified the file and what versions it modified from and to?  Did you expect certain commits to be removed and they weren't (perhaps because they were necessary for the topology, e.g. if they were merge commits)?  Were you looking at the server rather than the locally rewritten clone when you said the history remained (sorry, but I have to ask since several users did assume that running locally would change the history on the server too)?  Or something else?

> Also after it is run, git remote -v shows NO entries

Yes, once you rewrite history it is incompatible with the original and likely a bad idea to push it back to where it came from.  See sections 4 and 5 under "Discussion" in the manual (https://www.mankier.com/1/git-filter-repo#Discussion).

**Comment by newren** [comment]
No response to the questions; I'll go ahead and close out.
