### ISSUE TITLE
--path-match Documentation

### ISSUE THREAD

**Issue by AWoLnik** [newren/git-filter-repo#274]
There is no documentation of how to use --path-match or what behavior is expected. In the user manual it is simply listed as an option without any explanation, and it is not present in any examples.

I wanted to remove all files of a given type from my repo and couldn't figure out for the life of me how or if I could do that without regex (i.e. can I do "git filter-repo --invert-paths --path-match .xsa" ? The results of that command seem to indicate that I cannot, but the documentation offers no indication of that).

**Comment by newren** [comment]
If you want to remove all files with an `.xsa` extension, you can do so either via
```
git filter-repo --invert-paths --path-glob '*.xsa'
```
or, if you want something that can be extended to handle much more complicated filename-based rules, then you can use
```
git filter-repo --filename-callback '
  if filename.endswith(b".xsa"):
    return None
  return filename'
```
You could also use `--path-regex`, which sits between the above two in complexity and generality.

But to answer more about `--path-match` (since `--path-match` isn't useful for this particular case):

The full manual and the inline help from -h both document `--path-match` as a synonym for `--path` (meaning that every example using `--path` serves as an example for `--path-match` as well) and both state that the usage of `--path` and `--path-match` is to specify "Exact paths (files or directories) to include in filtered history."  Thus, your example would only remove a file named `.xsa` (and also wouldn't match any files in any subdirectories since that would have to use a path like `subdir/.xsa`).  As noted, `--path-match` and `--path` are about picking *exact* paths.  If you want patterns, you need to use `--path-glob`, `--path-regex`, or `--filename-callback`.

Hope that helps.
