### ISSUE TITLE
Error in check if blob is binary causes --replace-text to apply to binary files

### ISSUE THREAD

**Issue by rndbit** [newren/git-filter-repo#276]
In `def _tweak_blob(self, blob)`

https://github.com/newren/git-filter-repo/blob/c5af37f82c259f3a72c24601978c2fbf826d1d20/git-filter-repo#L3258-L3261

I suspect the line

    not any(x == b"0" for x in blob.data[0:8192]):

was intended to test if a blob is binary and to skip doing text replacement in binary files. If so then it does not work.

I'm testing with `python3 --version` = "Python 3.6.8"

That condition does not match for any input blob. `b"0"` is a sequence of one byte and gets compared to `x` of type `int`.

I expect this is because https://docs.python.org/3.8/library/stdtypes.html says: "bytes objects actually behave like immutable sequences of integers"

If my understanding about what it is supposed to achieve is right then I would change it to:

    # not (if blob contains zero byte in the first 8Kb, that is, if blob is binary data)
    not any(x == 0 for x in blob.data[0:8192]):

I'm happy to change and create pull request, I just need confirmation if I understand the intention for that code.

Test script for git-filter-repo before applying proposed fix, shows it DOES replace text in a binary file.

    #!/bin/bash

    rm -rf test-bin.git
    git init --quiet test-bin.git
    cd test-bin.git

    # Generate a sequence of bytes 0 .. 255 to file
    printf '%b\n' $(printf '\\%03o' {0..255}) > bin

    grep -q 123456789 bin && echo "'123456789' found" || echo "'123456789' NOT found"
    grep -q 987654321 bin && echo "'987654321' found" || echo "'987654321' NOT found"

    git add bin
    git commit -m test-bin-1

    echo
    git filter-repo --replace-text <( echo "123456789==>987654321" ) --force
    echo

    grep -q 123456789 bin && echo "'123456789' found" || echo "'123456789' NOT found"
    grep -q 987654321 bin && echo "'987654321' found" || echo "'987654321' NOT found"

Thanks.

**Comment by newren** [comment]
Gah, python3 conversion strikes again.  You are totally right, and there's another problem besides the one you mention: b"0" is a byte with the value 48, not 0, because it's the ASCII representation of "0".  It should have been b"\0" to get a 0 byte.  Anyway, the fix you propose is fine, though I'd slightly prefer it to be written as
```
    not b"\0" in blob.data[0:8192]):
```
rather than
```
    not any(x == 0 for x in blob.data[0:8192]):
```

The comment you added is helpful, and the testcase example looks like it'd be great to add to the testsuite.  A patch would be very much appreciated.

Thanks for finding this, reporting, investigating, and digging it down to propose a solution.  Very cool.

**Comment by newren** [comment]
Committed, so I'll go ahead and close this out.  Thanks for reporting, and for fixing!
