### ISSUE TITLE
Can't remove directory from repository

### ISSUE THREAD

**Issue by LoganDark** [newren/git-filter-repo#278]
I keep running this command:

```
git filter-repo --use-base-name --path node_modules/electron/dist --invert-paths --force
```

I've added it to gitignore, commited its removal, run that command like 8 times, removed it from the filesystem - but it's still there. GitHub still rejects my repository because this stupid package decides to include 100mb+ binaries. No matter what I do I cannot remove this from the history.

Please help.

**Comment by LoganDark** [comment]
```
git filter-repo --invert-paths --path-glob 'node_modules/electron/dist/*' --force
```
seems to have done it. It unsigned all my commits though. An option to GPG-sign commits would be appreciated especially since they are all my own.

**Comment by newren** [comment]
Glad you found the solution.  If you would have left off the --use-base-name from the first command, that would have worked too.  --use-base-name is incompatible with using '/', it is only used when looking for e.g. all 'README.md' files or all '.svnignore' files in all directories.  There won't be a file in some directory named "node_modules/electron/dist", since files can't have a '/' in their name.

The signed commit request makes sense and it comes up periodically, but filter-repo is based on fast-export and fast-import which don't have support for GPG-signed commits.  Support would need to be added there first.

Anyway, glad you got it working.

**Comment by LoganDark** [comment]
> If you would have left off the --use-base-name from the first command, that would have worked too. --use-base-name is incompatible with using '/', it is only used when looking for e.g. all 'README.md' files or all '.svnignore' files in all directories. There won't be a file in some directory named "node_modules/electron/dist", since files can't have a '/' in their name.

Yeah, it kind of makes sense when you explain it like that. I just wish there was a tutorial or something that explained this stuff to people like me who had to deal with something screwing their history (like making it permanently unpushable to github because [some node module](https://github.com/electron/electron) included a 100mb binary) but didn't have the time to read the entire man page and the rationale and the source code and all of the markdown documents.

The closest thing I could find was the "filter-repo vs BFG" documents, which worked good enough as examples.

> The signed commit request makes sense and it comes up periodically, but filter-repo is based on fast-export and fast-import which don't have support for GPG-signed commits. Support would need to be added there first.

My repository had 100+ signed commits which I had to then use filter-tree (ew) to re-sign. It was about as slow as you'd expect. But it worked at least. Even though every commit hash is permanently changed because things were unsigned and re-signed, even commits before the problematic directory was introduced into the repository. I'm glad that I'm the only person on this project.
