### ISSUE TITLE
[Help] Repository rewriting and republishing

### ISSUE THREAD

**Issue by avatar-lavventura** [newren/git-filter-repo#282]
I have followed following guide: https://stackoverflow.com/a/55017549/2402577

```bash
pip3 install git-filter-repo
git filter-repo --path <path to the file or directory> --invert-paths
```

I get following message

`Aborting: Refusing to destructively overwrite repo history since this does not look like a fresh clone.   (expected freshly packed repo) Please operate on a fresh clone instead.  If you want to proceed anyway, use --force`

Than I force it using `--force`.

But afterwards when I do `git push origin --force --all` I get following message: `fatal: 'origin' does not appear to be a git repository fatal: Could not read from remote repository. `.

I can handle it doing, but the changes (removed commits) does not show up on the public repo where when I clone it they still exist:

```
git remote add origin https://github.com/user/repo
git push origin --force --all
```

Should I do this operation all the time I am using `git filter-repo ` ? Is it right way to do it?

**Comment by newren** [comment]
filter-repo only removes the things you are trying to filter out from your local clone, not from the public original.  The original may contain additional branches or tags that are simply filtered out by your filtering operation, it may contain additional refs that they may even prevent you from updating (e.g. refs/changes/, refs/pull/, refs/merge-request/, etc.), and even if you update the original somehow despite all that, anyone else who cloned from the same spot might merge an old copy of the history they previous obtained with your rewritten version, causing you to get all the history back again anyway.

Because of all this, git filter-repo intentionally removes the `origin` remote.  It knows that pushing back to the same repository is often a bad idea and is hoping when you notice that `origin` doesn't exist that you'll think twice or at least read the documentation before proceeeding.  See steps 4 & 5 of the "Discussion" section of the manual (https://www.mankier.com/1/git-filter-repo#Discussion) for more details.

**Comment by avatar-lavventura** [comment]
But my aim is to pushing back to the same remote repository. Since I am only one using the repo I just want to completly remove the file from remote history.

**Comment by newren** [comment]
Then I suggest you use --mirror when pushing (so that any tags or branches not in your rewritten history get nuked when you push).  If you are using GitLab or GitHub, you'll need to see their guides for updating refs that they don't permit you to directly modify or delete (e.g. refs/merge-request/ or refs/pull/).  If you're using some other hosting provider, hopefully they either allow you to modify/delete all references, or they provide a guide on how to update those through some kind of special admin UI.

**Comment by avatar-lavventura** [comment]
Thanks @newren
