### ISSUE TITLE
Running --path-match et. all deletes entire repo and history (shell corrupts arguments passed to filter-repo)

### ISSUE THREAD

**Issue by CS-Cowboy** [newren/git-filter-repo#291]
This is a serious bug.  Not  only did the tool fail to ask me about being a fresh clone, it deleted things irrelevant to my filter options.

I gave --path-match for all three directories that I wanted removed from history, as per the documentation.

I am attaching screenshots of the commands and their results.

Not to be harsh but given the difficult to follow documentation and poor use of specific language in said documentation, and the bugs in the git-filter-repo project, I don't understand why GitHub has endorsed the tool. I just don't think its ready.

EDIT: I tried this with just one --path-match entries and it deleted the entire experimental repo commit history.

![GitFilterError](https://user-images.githubusercontent.com/70616107/135763011-50c190c0-ad76-4613-944a-459fcce898d3.PNG)

![GitFilterError_2](https://user-images.githubusercontent.com/70616107/135763010-0a3fe331-02d7-432d-9490-1c1238e041fb.PNG)

**Comment by newren** [comment]
Hi,

Thanks for the report.  One of the unfortunate things about writing a tool to assist people with destructively rewriting history, regardless of what documentation warnings I add or the number of guardrails I attempt to put into place to prevent people from accidentally doing so incorrectly, is that there are going to be some folks who get bit anyway.  I am sorry that you are one of those.   Thanks for filing a report with details that might help us improve the guardrails a little.

> This is a serious bug. Not only did the tool fail to ask me about being a fresh clone, it deleted things irrelevant to my filter options.

As per your screenshot, it did warn you about not being a fresh clone, though.  You added --force to your command line with --strip-blobs-with-ids check to override it.  Obviously once you've filtered the repo it's no longer a fresh clone (even if it was to start), so it saves your override so as to not annoyingly remind people with every additional filter command they add that they've turned it into a non-fresh clone -- or, in your case, that you've already overridden.

Also, as per the documentation, the filtering in filter-repo is an inclusion filter unless you specify --invert-paths, so it is supposed to delete everything you don't specify.
 
> I gave --path-match for all three directories that I wanted removed from history, as per the documentation.

From your screenshot, it appears your shell was silently corrupting your arguments and passing to filter-repo something other than what you specified.  For example, it changed `/GunRunFMOD` into `C:/Program Files/Git/GunRunFMOD` which is really dangerous as there's no way your git repository is going to contain files with the latter name.

Further, this corruption of your command line arguments defeated the check that would have pointed out the bug in your usage; namely the one added in commit 2833ef275f52 (filter-repo: throw an error if user specifies any path starting with a slash, 2020-05-16).  If you had specified `GunRunFMOD` the commands would have been correct.  If your shell hadn't subverted your commands before handing them to filter-repo, filter-repo would have warned you that the leading `/` character was a mistake.

What shell is this you are using that is corrupting the commands you are trying to pass to filter-repo?  Is there a way to make it leave your instructions alone so that filter-repo is told what you wanted, rather than being told something else?
 
> I am attaching screenshots of the commands and their results.

Thank you, this was very helpful in identifying the problem.
 
> Not to be harsh but given the difficult to follow documentation and poor use of specific language in said documentation, and the bugs in the git-filter-repo project, I don't understand why GitHub has endorsed the tool. I just don't think its ready.
> 
> EDIT: I tried this with just one --path-match entries and it deleted the entire experimental repo commit history.

Yes, your shell seems to be very dangerous.  I don't think it's ready for general usage, or at least people should be trained in it and use it with great care.

I'm not sure how to deal with general cases of shells passing to filter-repo stuff other than what the user typed, and handle errors across the combination, but is there something obvious I could potentially search on here?

**Comment by newren** [comment]
> I had a repository with local not pushed commits. I can't push them, because I add some really big files (github doesn't accept them).

You don't need to push your files; just can just clone your clone and then operate on that copy.  That way if you mistype the command, or don't read the documentation and assume flags do something other than what they do, you have only mucked with a copy and still have the original you can go back to.

>  I run this tool to drop these big files from git history, but as a result, it drops ALL files, except specified in --path. Command I used: git-filter-repo --path classification/*.pkl --force

Yes, nuking everything but classification/*.pkl is exactly what that command is supposed to do and is documented to do.  As per the description of --path: 

Exact paths (files or directories) to ***include*** in filtered history. Multiple --path options can be specified to get a union of paths.

If you wanted to only remove certain paths, you should use --invert-paths; see its description and multiple examples.

**Comment by MihailYa** [comment]
@newren I'm really sorry for my bad manner. I was really angry that day. I must better read the documentation before use of the tool.
I should be more grateful for the effort you put into development

**Comment by mastercoms** [comment]
The shell seems to be PowerShell 5.

**Comment by newren** [comment]
I think all the questions got answered previously, I just forgot to come back and close out.  Doing so now.  Hope things are working well for you.
