### ISSUE TITLE
Follow historic renames, or undo previously used --to-subdirectory-filter

### ISSUE THREAD

**Issue by matejcik** [newren/git-filter-repo#293]
I have a [repository](https://github.com/trezor/trezor-firmware) that is a monorepo merged from several unrelated histories.

Like this:
- take a base repository
- create a commit [that moves all files to a subdirectory](https://github.com/trezor/trezor-firmware/blob/b957dfbddb4222c5f9e573f3d4dc21fcbc6ff3a9/create_monorepo.py#L46-L51)
- [merge unrelated history](https://github.com/trezor/trezor-firmware/blob/b957dfbddb4222c5f9e573f3d4dc21fcbc6ff3a9/create_monorepo.py#L67-L77) from a new repo
- move the new results to a subdirectory, continue with next repo

We also wanted to keep some of the subdirectories going, using [git subrepo](https://github.com/ingydotnet/git-subrepo).
The usecase is sort of inverse of `submodule`: do all development in a central repo, and have the sub-repo exist with its own history that mirrors what happenend in the central repo.

`git subrepo` works by keeping track of "remote parent" and basically cherry-picks all new commits that touch a given directory onto the remote parent.
This means that it's easy to continue history from before the monorepo creation (just start with "remote parent" pointing to last pre-monorepo commit and replay things on it).
It also means that for every push, we have to create a commit in the central repository, which updates the "remote parent" and "last seen commit" fields.

---

I'd like to replicate this process using filter-repo. This is my starting point:
```sh
git filter-repo --subdirectory-filter=common/
```
The generated history ends with the "MONOREPO MERGE" commit, because at that point the `common/` directory came into existence and no previous commits touch it.

What I'd like to do is, detect that this commit _moves_ files into the `common/` subdirectory, and then keep the relevant parent and its history unmodified.

ISTM this can be done by using git-filter-repo as a library, but I'm not sure where to start.

**Comment by newren** [comment]
Heh, someone (the authors of `git subrepo`) found an issue with `git subtree` and instead of trying to fix it, instead rewrote it to somehow use filter-branch, making it glacially slow for non-trivial-sized repos with various other caveats to boot?  Ouch.  Maybe there's a good reason for it somewhere, but I failed to find it while perusing through the project.  Anyway, that's a side comment.

I'm not sure I understand your problem description.  You said you created a commit that moved all files into the common/ directory, so if you want to also include all files that led to files in the common/ directory, that would include all commits and files in history...so the filtering is a no-op.  What are you trying to filter?

There is a special tool for combining modules into a monorepo while also still being able to use them as independent repositories that does stuff much smarter than filter-branch.  @christian-schilling and I talked about our similar tools a fair amount at Git Merge 2020 but filter-repo is more for one-shot conversions, whereas his is tailored for that both-monorepo-and-independent-repo usecase.  Since you seem to be interested in that usecase, you may want to look at his project.  See https://github.com/newren/git-filter-repo/issues/66#issuecomment-613841143 and https://github.com/josh-project/josh

Does that help?

**Comment by matejcik** [comment]
> if you want to also include all files that led to files in the common/ directory, that would include all commits and files in history...so the filtering is a no-op

As I mentioned, there are several unrelated histories merged into one.

I want to **keep**:
(a) the part of history originating from a specific parent `PARENT` up until a commit "move everything to `common/`")
(b) the history _after_ the above break-point commit, filtered so that contents of `common/` are in the repository root.
I want to **exclude**:
the unrelated histories, IOW, either:
* every commit touching files that were never at any part of the history moved to `common/`
* or, differently specified, any commit that does not have `PARENT` in its ancestry

Actually, the latter seems vaguely possible to accumplish via `--commit-callback`. I couldn't figure out how to return a result that excludes the commit however.

In any case ISTM I'd have to do two-pass filtering? (1) remove unrelated histories, (2) filter subdirectory on only the newer part of the history

---

I looked into `josh` briefly, but it seems to do one-thing-well (namely: if i'm starting with a monorepo, split that up reversibly) and isn't really amenable to the kind of tomfoolery I'm trying to accomplish here :)

To make the story complete: it turns out that we don't need bidirectionality after all. The process is unidirectional, we do all development in the monorepo, and allow others to consume one specific part of it separately.

**Comment by matejcik** [comment]
in case anyone is following this, the solution that I landed on is pretty much exactly what I postulated in the above.

**Step 1**: cut off all unrelated histories except the main one.

I think nobody will need to do this, unless they created the monorepo in the same weird way as we did, i.e., by merging unrelated histories. If you did, you need to use `--commit-callback` to identify the parents that should be culled.

I don't think there's any good way to identify the unrelated histories automatically, because there's probably several different ways to create them.

**Step 2**: identify the last commit **before** `--to-subdirectory` happened, i.e., the parent of commit which does `mv * subdir/`. Done by hand -- although it would be nice if `filter-repo` could detect it, at this point I am not convinced that this fits with the larger feature set.
Tag this commit for convenience, then `git filter-repo --subdirectory-filter=subdir/ `**`--refs mytag..HEAD`**

This unfortunately keeps the "rename commit" as an empty commit, which might maybe be considered a bug?

**Comment by matejcik** [comment]
Update:
It turns out that Step 1 is not necessary.
My original attempt with just `git filter-repo --subdirectory-filter=subdir/` was _almost right_, except that I needed to find the right starting commit (i.e., the parent of the "move to subdirectory" commit) which to use with `--refs`.

I am now once again thinking that filter-repo could technically do this automatically -- however, the analysis would need to run backwards in order to properly detect which commit caused the rename. This is something that seems cleaner to document instead of adding as a feature.
