### ISSUE TITLE
Remove commits older than n days

### ISSUE THREAD

**Issue by Harvie** [newren/git-filter-repo#300]
Hello,
i would like to filter my repo in way that it only keeps selected commits based on following criteria:

 * Do not delete last 32 commits
 * Do not delete commits newer than 10 days
 * Do not delete arbitrary commits specified by their hashes
 * Optionaly do not delete commits referenced by tag
 * Delete everything else

That way i can have cronjob which automaticaly removes old commits from repo saving space.
When somebody accidentaly commits large file and then deletes it in another comit, the file will be automaticaly deleted from history after 10 days. Given that i do not need actual long-term history (more than 10 days) to be kept.

Is there way to automaticaly filter commits like this using git-filter-repo ?

**Comment by newren** [comment]
Let's take a step back for a second; because I suspect there's a better solution than repeatedly rewriting history here.  In general, repositories can have hundreds of thousands of commits and still have the entire history fit in less space than an uncompressed copy of the files from just one commit.  Further, having just a few commits takes nearly all the space that having a long history would require, unless some of those commits had huge changes.  So, I don't see the point in aggressively pruning history and doing so repeatedly just to "save space".  Rewriting to remove huge files added in the past make sense, but that should be paired with hooks that reject future commits with large files rather than planning to repeatedly rewrite history.

Now, all that said, I'm sure you could put together a script that determines the appropriate commits and keeps just them, perhaps using replace refs, but there's no native support for picking commits based on the recency criteria you give.  I suspect not passing `--reference-excluded-parents` to fast-export might make it easier to do what you're asking, but filter-repo passes that unconditionally, and I see no reason to change that, which leaves the replace refs as the likely only way to achieve this within filter-repo.

I'm not sure if my alternate suggestion helps (add a hook to prevent large files in the future), or if you're still set on doing this.  If you are my replace refs suggestion might help, but as described, this isn't a usecase I'm aiming for or supporting.  Hope that helps.

**Comment by Harvie** [comment]
To be honest. My use case might be bit hacky. I want to implement continuous file synchronization. Regulary (or using inotify) commit all changes made to tree, while pulling (rebasing) and pushing. So i can use git server as central node, while my script is automaticaly synchronizing everything bidirectionaly from/to it on multiple leaf nodes.

Once this synchronization is done, i want to keep only the very recent history. That way i can even synchronize big video files (eg. few gigabytes every week through git without worrying that the history will get bloated).

I know this is a weird hack, but i don't think it is completely stupid. Because lots of people have free access to git storage, so it might be interresting to use it as central node for file synchronization.

**Comment by newren** [comment]
Ah, so not really version control; that lessens my worries considerably and the usecase does sound like it might make sense.

For your case, I think it's basically a case of combining `git replace --graft $COMMIT` (note: don't list any parents, so that you are making $COMMIT look parentless) for each of the now-oldest commits that you want to retain, make sure no branch or tag points at commits older than the now-oldest one(s), and then run `git filter-repo --force` to rewrite the history and make the replace references permanent.

filter-repo doesn't provide anything to help you find the now-oldest commits according to the criteria you listed above, but various invocations of git log with the --format flag ought to help you sift them out.  Hopefully that helps.  Good luck!

**Comment by Harvie** [comment]
My idea was to keep tags tracking last commits seen by individual clients, so they will stay in place untill they download the latest history, then they will move the tag so i know i can remove that part of history from the server.

Also if i want to use such system to be able to operate on github or similar free services, i cannot have server-side cronjob to do the cleanup of history in centralized manner for me. So i think individual clients will have to somehow do the cleanup localy and then force push the shorther history to the server to prevent hitting repo size quotas on that server.

But i still wonder whether i can remove history like this without preventing other clients to do clean pull.

Do you think this will work?

**Comment by newren** [comment]
When you rewrite the history to remove the old commits, it will change the commit hashes for all the newer commits.  That means that if only one side rewrites history, then the next attempt to pull or push history will push *everything*, because it'll appear the two sides have *zero common history*.  (I don't remember details on whether git attempts to figure out whether the blobs are shared or just resends them all; in the past, it certainly resent them all, but the pack.useSparse might have fixed that -- you'd have to test.)

So, you'd need to be careful to make sure that when you decide to rewrite, that all relevant sides rewrite and do the rewrite in exactly the same way.  If any side nukes one more or one less early commit, it'll have completely different commit hashes than everyone else.

Trying to get clients to synchronize their cleaning schedule and pieces sounds kind of daunting to me, but it'll be up to your usecase for whether you feel it is feasible or not.

**Comment by Karreg** [comment]
Hello,

We have the same need here... I'm managing a GitLab instance, and we definitely need this for our users.

Of course, this is a corner case, where git is not really the best tool to use.

And to avoid storage drifting, we have git hook that blocks too big files and too big repositories.

In this context, we have some projects that have files small enough to not being blocked, but big enough, and regularly updated, to have the repository to grow until going over the threshold and being blocked.

Since their use case is borderline, we can't really tell them to get out of GitLab, and to avoid issues, they need regular (twice a year) cleaning to remove older commits, and keep the repository size acceptable.

For information, we allow up to 800 MB for a project, and the percentile 80 repo size is 11MB, percentile 95 is 130 MB, percentile 99 is 710 MB... Increasing the repo size would only delay the issue.

Is there any hope to see this, understandably borderline, feature done someday? 😇

**Comment by newren** [comment]
Can you use:
```
  git replace --graft ${OLD_COMMIT}
  git filter-repo --proceed
```
?

The first command creates a new commit, replacing ${OLD_COMMIT}, with a commit that has an identical tree and commit message and author/committer, but which is a new root commit (since no parents are listed on the command line).  Then the second line rewrites the history to bake that replacement in permanently and removes the older commits.

The only trick her is that you need to determine what the ${OLD_COMMIT} is.

One possible drawback is that if you have a heavily non-linear history, you might not be able to identify a single ${OLD_COMMIT} on which everything else depends, in which case you might need to do multiple `git replace --graft ...` commands each with a different old commit listed before running git-filter-repo.

**Comment by BartMassey** [comment]
`git filter-repo --proceed` fails. `git filter-repo --force --path-glob '*'` worked for me

**Comment by newren** [comment]
How does `git filter-repo --proceed` fail?  (Invalid argument since that argument is only available in the most recent version?). Also, I think you could have left off `--path-glob '*'` there; the `--force` alone would have been enough.  But glad to hear that using replace refs works for you.  Are you working with @Harvie  or @Karreg , or do you just have similar needs and reporting on what you tried?

**Comment by BartMassey** [comment]
You are correct: `git filter-repo --force` alone seems to work fine. Yes, using stock Debian so no package with latest bits.

Just reporting. I had one of those gut-and-stuff repos where the old commits were pretty much irrelevant since I'd rewritten most of it. Seemed better to just get rid of them.

Really appreciate `git-filter-repo`: it's been useful both to me and to my students many times. Thank you.

**Comment by newren** [comment]
I'm not sure waiting more after giving a solution in https://github.com/newren/git-filter-repo/issues/300#issuecomment-2259846003 (which was much the same solution as given in https://github.com/newren/git-filter-repo/issues/300#issuecomment-964819410) makes sense.  I had wanted to see if there was anything else unique to their usecase that I hadn't already addressed, but I suspect @Harvie and @Karreg have moved on.  Anyway, solution is above for removing commits older than a certain date, so I'll close this out.
