### ISSUE TITLE
git filter-repo --version returns unrelated hash instead of tarball version

### ISSUE THREAD

**Issue by erickellerek1** [newren/git-filter-repo#304]
I just followed the instruction to install git-filter-repo latest version from the tagged tarball

```
docker run -i --rm bitnami/git:latest bash -x << 'EOF'
apt update && apt install --yes --no-install-recommends make xz-utils python3 man
curl -s https://github.com/newren/git-filter-repo/releases/download/v2.34.0/git-filter-repo-2.34.0.tar.xz -L --output /tmp/git-filter-repo.tar.xz
mkdir -p /git-filter-repo && tar xaf /tmp/git-filter-repo.tar.xz -C /git-filter-repo
mkdir -p /opt/bitnami/git/share/man/man1 /opt/bitnami/git/share/doc/git-doc
cd /git-filter-repo/git-filter-repo-2.34.0/ && make prefix=/opt/bitnami/git pythondir=/usr/local/lib/python3.7/dist-packages install
mandb
git filter-repo --version
EOF
```
this installed the tool yet when calling:
```
root@efe4536be950:~# git filter-repo --version
22826b5a68b6
```

I get this odd hash which is also not corresponding to the tagged release.
I would have expected `2.34.0`

**Comment by usinelogicielle** [comment]
Same for me with the same version and the same hash

**Comment by newren** [comment]
Thanks for the report.  This has already been reported as issue #81; see that issue for the explanation.

**Comment by simple2** [comment]
I had the same problem: I have version of git-filter-repo (which is a great tool btw.) and I want to know if it is the most recent version or how old it is. So knowing that the has printed on --version, I've looked a git-command to find this git-object in the repository.
If you have cloned the repository, you can search for the versionHash with:
```
git log --pretty='format:%H' -- git-filter-repo | while read commithash; do if git ls-tree $commithash | grep 10401e45d5f0 > /dev/null; then echo $commithash; fi; done
```
It shows the first commit that includes the given object-hash.
Instead of just echo'ing the commit-hash you can also show the commit summary (which shows you the date of the version):
```
git log --pretty='format:%H' -- git-filter-repo | while read commithash; do if git ls-tree $commithash | grep 10401e45d5f0 > /dev/null; then git show --summary --stat $commithash; fi; done
```

With this command you can create a whole version-table, so you don't have to check-out the repository if the table is published somewhere:
```
git log --pretty='format:%H' -- git-filter-repo | while read commithash; do objhash=$(git ls-tree $commithash | grep -e "git-filter-repo$" | awk '{print $3}'); echo "Commit: $commithash includes version: $objhash"; done
```
