### ISSUE TITLE
Symbolic link not working on Windows

### ISSUE THREAD

**Issue by peterleif** [newren/git-filter-repo#307]
These 2 files are commited as symbolic links

- git_filter_repo.py (https://github.com/newren/git-filter-repo/blob/main/git_filter_repo.py)
- filter-branch-ish (https://github.com/newren/git-filter-repo/blob/main/contrib/filter-repo-demos/filter-branch-ish)

However, these symbolic links are not treated as symbolic links on Windows (they are substituted by text files instead).

Could you consider stop commiting these files as symbolic links?

Thanks

**Comment by CervEdin** [comment]
you can enable symlinks in windows

**Comment by newren** [comment]
If I make them be copies of the file in question, then I have to update them both whenever I update the main file.  That makes history rather ugly.  If you don't want to enable symlinks on Windows, just make them be copies yourself and they'll function just fine.

### Additional Background

I would have preferred to not have git-filter-repo.py exist at all, but python made importing files that don't end in .py really painful and makes all the contrib examples super ugly.  But I could just use git-filter-repo.py because `git X` will work and call `git-X` without the extension.  So, I need both to exist, but I don't want to update both.  Symlinks are a super nice solution, but others can switch it to a copy locally if they want.

filter-branch-ish only exists so that people can find "filter-branch" and how to replace it.  The really name of the script is "filter-lamely" because filter-branch is a horrendous design that is going to cause people problems and I want the name of the script to warn people against its use.  They symlink also makes it clear that the file has a real name elsewhere.

So, both serve good purposes, and I'll keep both as symlinks.  You can turn them into copies on your end if you please; nothing relies on them remaining symlinks.
