### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by skorokithakis** [newren/git-filter-repo#308]
Since most people looking to use gfr will have one of a few use cases in mind, I think it would be very worthwhile to add a few examples for things like:

* Purging large files from history.
* Purging sensitive files from history by filename.
* Purging file contents.

Examples like these would help people get things done very quickly.

**Comment by happyTonakai** [comment]
I think this should work for the first and second usage:
```
git filter-repo --invert-paths --path path/to/file
git push origin --force --all
```

**Comment by newren** [comment]
### Purging large files from history

How do you determine which files are large?  Are you just purging based on size?  If so, doesn't the first example in the manual under the "EXAMPLES" section in the "Content based filtering" subsection cover this?  (Direct link: https://www.mankier.com/1/git-filter-repo#Examples-Content_based_filtering)  If based on knowing the names of the large files, then the section below answers it.

### Purging sensitive files from history by filename

You mean like the examples in the "Path based filtering" subsection of the EXAMPLES section of the manual?  Direct link: https://www.mankier.com/1/git-filter-repo#Examples-Path_based_filtering

### Purging file contents

You mean like the example under the "Content based filtering" subsection of the EXAMPLES section that shows using `--replace-text`?


### Additional examples

There are also additional examples of all of these types of things at https://github.com/newren/git-filter-repo/blob/main/Documentation/converting-from-bfg-repo-cleaner.md#cheat-sheet-conversion-of-examples-from-bfg as well.


Let me know if I'm missing anything in the above answers and we can reopen; otherwise I'll close this out.
