### ISSUE TITLE
Support for Bash completion

### ISSUE THREAD

**Issue by carbongreat13** [newren/git-filter-repo#315]
Would it be possible to support Bash completion?

**Comment by newren** [comment]
It's possible, I just don't think it's a good idea.  Bash completion is for reducing typing for frequently used commands? Since git-filter-repo is for rewriting history, which should be done sparingly, the idea that it'd be frequently used suggests a deeper problem somewhere else.

If that doesn't dissuade you: Someone could add the necessary bash or zsh completion rules via some kind of script, much like git did for all its commands via contrib/completion/git-completion.bash in the git.git repo.  One could even depend upon the function in that script when writing the git-filter-repo-completion.bash, since folks who want filter-repo completion almost certainly are using git completion as well.

Anyway, I'm unlikely to do this myself, as I just don't see the point for a rarely used command.  And I'd probably not merge it if someone else wrote it.  But I can leave this issue open to see if others are interested enough to implement it and throw a pointer to others who really want it.
