### ISSUE TITLE
Getting error  line 3277     **extra_items}  syntax error. on git filter-repo.py --invert-paths --path include/xyz.php

### ISSUE THREAD

**Issue by AnupamKhosla** [newren/git-filter-repo#317]
I have python 3.10 on windows10. I was getting `python3` file/folder not found. So I changed the first line of `git-filter-repo.py` file to change `python3` to `python`. If I run `git filter-repo` I get error:  

```
git: 'filter-repo' is not a git command. See 'git --help'.

The most similar command is
        filter-repo.py
```

So I run `git filter-repo.py --invert-paths --path include/xyz.php` and get the following error:  

```
 File "C:/Anupam/Softwares/Git/Git/mingw64/libexec/git-core\git-filter-repo.py", line 3276
    'original_ancestry_graph': self._orig_graph, **extra_items}
                                                  ^
SyntaxError: invalid syntax
```

I need to fix my github repos history asap, any alternatives would be appreciated.

**Comment by newren** [comment]
This suggests you might have python 3.10, but it isn't being used.  Some version of python that is too old is being used instead.  Possibly because the git version you have is trying to force an old python to the front of your PATH?

Try calling the script directly instead of having git invoke it.  e.g.
  `git-filter-repo.py --invert-paths --path include/xyz.php`
(Note the dash rather than the space between `git` and `filter-repo`)

**Comment by Mdkhan1518** [comment]
support all

**Comment by Mdkhan1518** [comment]
steamkar topup all id,573918761

**Comment by Mdkhan1518** [comment]
suppoet
