### ISSUE TITLE
Feature:  Partial/update filtering

### ISSUE THREAD

**Issue by ehem** [newren/git-filter-repo#329]
It would be highly valuable to be able to update filtered repositories.  If instead of expecting to grab portions of an outside repository **once**, there could be a need to routinely update to match with someone else's repository.

Roughly my ideal would be something like this

```
git remote add theirproject https://git.example.org/uber-library.git
git fetch theirproject
git filter-repo --src-branch theirproject/main --dest-branch theirproject --path public/include --tag-rename=:theirproject/
git merge --allow-unrelated-histories theirproject
git mv public/include include/theirproject
git commit --amend
```
Then on a routine basis:
```
git fetch theirproject
git filter-repo --src-branch theirproject/main --dest-branch theirproject --path public/include --tag-rename=:theirproject/
git merge theirproject
```

The point being rather than expecting filtering to be a one-time operation, filtering could be a routine task.  If this is an external library, I may want to keep a local copy of headers.  For such a task it would also likely be useful to add "original-commit: 6c551c48ae37ce15d6bc7397b0556a599d6f5ff6" to commit messages so we can attribute the change back (so if their headers get broken, we can point out where in our bug report).  I suspect the current commit hash of theirproject/main would also need to be recorded in the tip commit message of the theirproject branch.

If you want to be ambitious, make it possible to do filtering during `git fetch` so we don't need their full history at any point.

**Comment by ehem** [comment]
Ideally this would be resolved by `filter-repo` being 100% perfect and bug-free.  Then subsequent updated retrieving more history would perfectly overlay the old history.  Unfortunately this is difficult to achieve, so the issue is `filter-repo` needs to be able to meld updated history onto an older filtering job.

**Comment by newren** [comment]
Thanks for the report.  There are a number of people that want this; see issue #66, issue #93, issue #293, and https://github.com/josh-project/josh.

Someone might be able to tweak filter-repo to solve this usecase (though I think they'd want to use --preserve-commit-hashes, because as you add more history, you eventually are guaranteed to have abbreviated commit hashes become ambiguous, and then future rewrites modify the history differently and give you different hashes), but I'm pretty focused on the one-shot rewrite.  josh is very much focused on this particular usecase, and likely can do it for you today, so I don't see the need to make filter-repo solve it.

Hope those pointers help.  I'll close out, but feel free to reopen if what I said doesn't make sense or you have further questions.
