### ISSUE TITLE
Add commit hash to each commit message

### ISSUE THREAD

**Issue by KiperUladzislau** [newren/git-filter-repo#348]
Hi, I'm wondering how to add an original commit hash to each commit message with a help of `git filter-repo --commit-callback`
What I've tried is `git filter-repo --commit-callback script.py --force`, where `script.py` contains
```
def commit_callback(commit):
	commit.message = commit.message + b'\n' + commit.original_id
```
But it has no effect, also I've tried to change author name via `commit.author_name`, it does not have any effect either

**Comment by ePaul** [comment]
According to the [docs](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#CALLBACKS), the commit callback needs to be directly the body of the function, not a file name.

So it would be something like this:

```shell
git filter-repo --commit-callback "
   commit.message = commit.message + b'\n' + commit.original_id
"
```
You can of course put the function body into a file (but without the `def` line), but then you'd need to use your shell to inline it, using e.g. command substitution:

```shell
git filter-repo --commit-callback "$( cat commit-callback.py )"
```

(I've omitted `--force` as you normally should not need it, and it shouldn't be included in examples which might be copied byy other people.)

**Comment by newren** [comment]
Ever since 5256c99e496b (Allow callback body to be loaded from a file, 2021-04-27), you can actually specify a filename rather than the inline callback.  However, the file is supposed to contain the function body, not the function definition.  I.e. script.py should contain just the
```
	commit.message = commit.message + b'\n' + commit.original_id
```
line, because git-filter-repo.py already self-includes the function declaration line.  By trying to include that line yourself, you essentially have a function that looks like:
```
def commit_callback(commit):
        def commit_callback(commit):
	        commit.message = commit.message + b'\n' + commit.original_id
```
Since the inner commit_callback() is not called by the outer, it's just dead-code and you've defined a no-op.

Anyway @ePaul was on the right track, he just may have been unaware that callbacks can specify a filename nowadays (thanks for helping answer @ePaul!)

**Comment by ePaul** [comment]
@newren I'd suggest to mention this feature in the documentation – the [callback section](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#CALLBACKS) doesn't mention that one can pass file names at all.
