### ISSUE TITLE
Option for purging all commits except the last one?

### ISSUE THREAD

**Issue by RichardBenes** [newren/git-filter-repo#363]
Hello,

I just finished some work in our company repo, these were the requirements:

1. Remove all files with given extension from the whole history
2. But don't touch the content of the last commit

Although I didn't try it, [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner) states that
it does just that by default; so maybe it wasn't just our exceptional requirement.

Of course there are various workarounds available; one can always save the last commit
somewhere & re-upload it with `--amend` to get that result (its checksum won't be kept anyway).

I also tried to instruct the `git-repo-cleaner` by various options (esp. `--refs`), but I didn't find
any way to make it work the required way.

Anyway, thanks for such handy tool!

**Comment by newren** [comment]
Glad you found the tool helpful.

You may want to take a look at the contrib/filter-repo-demos/bfg-ish script in this repository, which is a re-implementation of BFG Repo-Cleaner using git-filter-repo.  You could just use that script with the `--delete-files` and `--preserve-ref-tips` options to satisfy your two criteria.  (Note, though, that "last commit" is ill-defined, you'll need to specify the last commit of which branches when you use --preserve-ref-tips.)

And yeah, the --preserve-ref-tips was just an ugly workaround, where it saves info from the commits before running, does the fast-export/fast-import work, and then does some manual touch-up work afterwards to modify the commits at the tip (see the get_preservation_info() and revert_tree_changes() functions in that script if you're curious).  I won't be adding the --preserve-ref-tips to git-filter-repo itself, since it's incompatible with other types of history rewrites (more details available over at https://github.com/newren/git-filter-repo/blob/main/contrib/filter-repo-demos/bfg-ish#L32-L56).  But hopefully these pointers help make things easier for you.
