### ISSUE TITLE
How to change Author line of certain commits, without changing every single hash in the repository

### ISSUE THREAD

**Issue by LeeAlephium** [newren/git-filter-repo#365]
For some reason, I cannot stop every, single, commit from being rehashed. I've begun contributing to a project a couple months ago and simply want to change all my Author lines to something else... I've tried --partial, --source & --target... Neither work as I thought they would. Any advice?...

**Comment by newren** [comment]
Short answer:

Sorry, but what you are asking for is something that Git was designed to make impossible, and as such no tool can do this. 
 *Especially* not tools like git-filter-repo that use Git commands like fast-export and fast-import to do the real work.

The longer answer...

Git works by naming commits with the hash of the commit object's contents.  Commit objects include toplevel tree, parent commits, committer names and date, commit log message, and critically, the author names and date.  Thus, if you change the commit object by changing any of those fields, then the hash of the commit object will change and thus the name of the commit (i.e. the hash) changes.

You can't make Git record an object with a name not matching the hash of its contents.  This idea was totally fundamental and core to Git's design.  (One of the motivating factors in the creation of Git was some history of some bad actors breaking in to the kernel servers and modifying the repositories other's cloned from.  Had CVS or SVN or other version control systems been in use, that would have gone undetected and they would have gotten away with it.  Bitkeeper had slightly weaker guarantees, than Git has, but still had enough of a checksum that the modified objects were flagged as errors and people investigated and found the servers had been hacked.  So, Git has baked into it the idea that if someone mucks with any of the objects in history, then all the hashes change and everyone notices.)

Since git-filter-repo just uses Git's fast-import tool, you're basically asking git's fast-import tool to write fundamentally broken objects.  Also, even if we were motivated to bypass git-fast-import and manually write objects ourselves and violate the basic design principle of Git, then the resulting history would be useless.  Git would flag it as an error the minute you attempted to push/fetch/clone such a history.

**Comment by sepsol** [comment]
@newren Is it correct that if you were to modify a commit with `git-filter-repo`, other than recalculating the hash of the modified commit, it should only recalculate the hashes of the descendent commits and not alter the hashes of its ancestors?

**Comment by newren** [comment]
@sepsol: yes, that's correct.

**Comment by me-and** [comment]
I've just done a little digging, as I was surprised to be able to reproduce this. At least for this repository, it appears filter-repo strips signatures from commits even when nothing about the commit is changing. That means that commit hash changes, and so does the hash of all subsequent commits, even though the signature would have remained valid. 

In particular, in this repo, https://github.com/newren/git-filter-repo/commit/9cf87ae036ffd6c45075278e03c473e49a43b339 is signed. That's the first commit that's changing, and as a result every subsequent commit also changes.

**Comment by me-and** [comment]
That's weird. It looks like Git is computing different hashes for commits with identical `git log --format=raw` output. I'm not sure how that can happen! I'd thought the commit hash was a combination of the tree hash, the author and committer information, and the commit message, but none of those have changed here, even though the commit hash is changing.

`git fsck` isn't reporting any data integrity issues, so I _assume_ it's not a Git bug, but it's definitely not behaviour I'd have expected.

Short repo script below:

```bash
#!/usr/bin/env bash

dir="$(mktemp -dt "$0".repo.XXXXX)"
trap 'rm -rf "$dir"' EXIT

repo_dir="$dir"/repo
oldlog="$dir"/oldlog
newlog="$dir"/newlog

git clone -q https://github.com/LibreGames/jumpnbump "$repo_dir"
cd "$repo_dir"

root_commits="$(git log --max-parents=0 --pretty=format:%H --all)"
git show --format=raw --no-patch $root_commits >"$oldlog"

git filter-repo --quiet --name-callback 'return name'

root_commits="$(git log --max-parents=0 --pretty=format:%H --all)"
git show --format=raw --no-patch $root_commits >"$newlog"

git diff --no-index "$oldlog" "$newlog"
```

And the output I'm seeing:

```
New history written in 0.26 seconds; now repacking/cleaning...
Completely finished after 0.74 seconds.
diff --git a/tmp/demo.sh.repo.00Q6S/oldlog b/tmp/demo.sh.repo.00Q6S/newlog
index bf97000..7c326ec 100644
--- a/tmp/demo.sh.repo.00Q6S/oldlog
+++ b/tmp/demo.sh.repo.00Q6S/newlog
@@ -1,4 +1,4 @@
-commit fbdea29f6d478a58bee66a1ec53b0ca59d853c4d
+commit 1cf555aed5fd0d23bd3c2d115a2673c4dded8e92
 tree 8be3d2422fccd8d5ac792864033bd06121f26d33
 author Florian Schulze <crow@icculus.org> 1013600908 +0000
 committer Florian Schulze <crow@icculus.org> 1013600908 +0000
```

**Comment by newren** [comment]
@me-and : `git show` doesn't really show you the original commit.  Try cat-file -p instead:
```
$ git cat-file -p fbdea29f6d478a58bee66a1ec53b0ca59d853c4d
tree 8be3d2422fccd8d5ac792864033bd06121f26d33
author Florian Schulze <crow@icculus.org> 1013600908 +0000
committer Florian Schulze <crow@icculus.org> 1013600908 +0000
encoding ISO-8859-1

Initial revision
```

Now, as per the manual:
```
--preserve-commit-encoding

Do not reencode commit messages into UTF-8. By default, if the commit object specifies
an encoding for the commit message, the message is re-encoded into UTF-8.
```

Anyway, re-encoding the commit from ISO-8859-1 to UTF-8 obviously changes the commit's contents, even if you can't "see" the differences based on "git show" or "git log" output.  And since this commit is changing, as I stated above, all commits that depend upon a modified commit will also get new hashes.
