### ISSUE TITLE
`git filter-repo --invert-paths --path single_file.zip` deleted my entire repo???

### ISSUE THREAD

**Issue by LukeWood** [newren/git-filter-repo#373]
git filter-repo --invert-paths --path experiments/annotations_2017 deleted my entire repo.  I had about a days work on there I wanted to push to github - but couldn't push because I accidentlaly added that massive annotations file.

why did this happen???  Does git filter-repo create a backup anywhere locally I can restore from?

**Comment by newren** [comment]
git filter-repo very carefully instructs users to make a fresh clone before running, because that means what you originally cloned is your backup and you can just nuke the extra clone if the repository filtering goes awry.  So, simply re-clone your original and you'll be good.

I'm surprised you say it deleted your entire repo.  What do you mean by that?  Did you really have the entire working directory deleted?  Did `git status` or `git log` fail after you ran?  Did those commands work but show fewer commits than expected?

Any more details about your setup?  Were you working on a detached HEAD by chance?  How many refs?  Was experiments/annotations_2017 the only path in your repository?  What else existed?  Could you provide the output by chance?

**Comment by LukeWood** [comment]
Unfortunately this was too long ago to remember.

i was mainly surprised it removed the files in place/. Feel free to close as I don’t have any more information anymore.
