### ISSUE TITLE
Can't make it working on Github

### ISSUE THREAD

**Issue by Zeus64** [newren/git-filter-repo#391]
Hello,

On a fresh cloned repository from Ghitub I do :

git filter-repo --strip-blobs-bigger-than 5M
git remote add origin <url>
git push --force --all origin

I can see on my local repository that all files > 5mb have been successfully deleted. But nothing change in the remote repository. If I go on https://github.com/Me/MyRepository I can still see the files that I deleted

So what is the correct flow to clean my repository on github ?

**Comment by me-and** [comment]
See the discussion section in the documentation at https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html; this is difficult due to the nature of Git and GitHub.

Your best bet, for a large variety of reasons covered in that documentaion, is to create a whole new GitHub repository and push your rewritten repository there, then delete the original GitHub repository once you're satisfied you have all the backups and data you need.

**Comment by pmartindev** [comment]
As @me-and mentioned, adding to a new source is the most straight forward approach. You can rename to some other name, then delete or archive the original repo, and rename the newly pushed repository to the original repo name. If that's not possible, you will need to contact contact [GitHub Support](https://support.github.com/contact?tags=docs-generic).
