### ISSUE TITLE
Need to decode repo_working_dir before calling CreateProcess()

### ISSUE THREAD

**Issue by rmanibus** [newren/git-filter-repo#4]
Hello,

I had an error on windows 10 :
```
TypeError: CreateProcess() argument 8 must be str or None, not Byte
```
I solved the problem by decoding the repo_working_dir line 1437.

**Comment by newren** [comment]
Oh, cool, my first Windows user!  I don't have Windows to test on, so this is great feedback.  Was this the only change you needed?

It looks like I've got a little bit of inconsistency in how source and target directories are handled, with either potentially ending up as a cwd argument to subprocess.Popen.  I suspect there are a few more that would be needed depending on the arguments you pass; I should probably go through and clean those up.  But I believe I also mixed and matched regular strings and byte strings in command arguments; do those all work for you on windows despite it not liking a cwd that was a bytestring?  E.g. does

subprocess.check_output(["git", b"--version"])

work?

**Comment by rmanibus** [comment]
No sorry I created this a bit too fast.

Each time you call check_output use 
repo_working_dir.decode('utf-8') if isinstance(repo_working_dir, bytes) else repo_working_dir

Somehow if I just use decode it it's not working, because sometime it's a string and sometime a bytes.

I don't have my patch available right now, but I will submit a PR asap.

**Comment by rmanibus** [comment]
Thank you, it's working perfectly (I tried --path and --path-rename). 

The only thing is that by default the python binary is called python and not python3.

**Comment by newren** [comment]
Wow, that's all that was necessary to get it to work on Windows?  I'm a bit surprised, but I'll go ahead and merge that commit in.  If you do run into further issues, go ahead and report them.

As far as "python" vs "python3" -- yeah, I kind of expect that.  For years the python devs gave the advice that "python" should refer to python2, and the executable for python3 should be named differently.  They are starting to relax that with the impending EOL of python2, which means we'll be stuck with some systems calling it "python" and some calling it "python3".  However, it's safer for me to use "python3".  If someone has "python" which is a python3 implementation, then they probably get a simple error message saying there is no "python3" executable.  In contrast, if I were to use "python" assuming that meant python3, then those who have a "python3" will probably also have a "python" that refers to python2 -- and the error messages from attempting to run python3 code under python2 will be far less clear.  So, because of that, it'll be a long time before I switch over the shebang.
