### ISSUE TITLE
Remove now ignored files from git history

### ISSUE THREAD

**Issue by jmpanfil** [newren/git-filter-repo#415]
I have a repo that is close to 1GB that I am trying to clean up. I know that most of the issue is I had previously committed large files. Those files are now ignored through `.gitignore` but they are still in my .git history. I ran `python git-repo-filter --analyze` which gave me a list of files in `.git\filter-repo\analysis\path-deleted-sizes.txt'`. I am going through those one by one and running ` python git-filter-repo --invert-paths --path path --force`. That seems to be reducing the directory size a lot.

Is there a better, more automated way to remove all now ignored files from my history?

**Comment by newren** [comment]
I'm glad it's working for you, but I'm a little surprised.  Why did you come up with the idea to you run N processes of `python git-filter-repo --invert-paths --path path` instead of just one with `python git-filter-repo --invert-paths --path path1 --path path2 --path path3 --path path4`?  

As for easier ways, besides putting all paths on one command line, you could just list the paths you want to expunge in a file and run `python git-filter-repo --invert-paths --paths-from-file file-with-paths-you-want-nuked.txt`?

But even easier than that would be using the `contrib/filter-repo-demos/clean-ignore` file in this repository.  It's meant to do exactly what you want: delete all files from history that match _current_ .gitignore rules.

**Comment by jmpanfil** [comment]
Thanks I didn't know about that usage. I'm looking at the clean-ignore file. What arguments does it expect? I am running it in the directory that needs to be cleaned.

```
python .\clean-ignore.py          
No arguments specified.
```

**Comment by newren** [comment]
It actually makes use of filter-repo's parsing so that you can also combine it with any normal options that git-filter-repo takes.  But, since filter-repo errors out if nothing is specified, you need to use `--force` to tell it to ignore the fact that there isn't any additional filtering you want beyond the cleaning of now-ignored files.

**Comment by jmpanfil** [comment]
I think that clears everything up for me. Thanks again.
