### ISSUE TITLE
Directory content not removed, only parent(s)

### ISSUE THREAD

**Issue by helmesjo** [newren/git-filter-repo#416]
`git-filter-repo 2.38.0` installed with brew.

Hi! So I was giving this a spin, but checking the results I'm not sure why I'm still seeing files in the directories I specified to delete.

I use this script (found somewhere on the webs) to list files sorted by size:
```
git rev-list --objects --all |
  git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
  sed -n 's/^blob //p' |
  sort --numeric-sort --key=2 |
  cut -c 1-12,41- |
  $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

Running above prior to `filter-repo` I see this (snippet of a single row):
`43860c363b07  2.1MiB src/external/boost/boost-repo/boost/typeof/vector200.hpp`

I then run this:
`git filter-repo --path 'src/external/' --invert-paths`

If I run my script again I still see `vector200.hpp`, but now without it's leading (parent) `src/external/`:
`43860c363b07  2.1MiB boost/typeof/vector200.hpp`

Given the results I'm seeing, I assume this is just a trivial error done by me, but looking at all examples I can't just see it... (:

**Comment by helmesjo** [comment]
Doing a dry-run and comparing original/filtered it does suggest to have done what I wanted, so is there some other command that needs to be run to fully complete the process (that is, so it no longer can be found)?

**Comment by newren** [comment]
I think you've misunderstood the command you found on the webs.  Let's say you have a file somewhere, `some/big/file.data`.  And then you later rename it to `subdir/some/big/file.data`.  The output you'd get from your `git rev-list --objects` pipeline would be something like
```
deaddeadbeef  3.0MiB subdir/some/big/file.data
```
and in particular, you would NOT see
```
deaddeadbeef  3.0MiB some/big/file.data
deaddeadbeef  3.0MiB subdir/some/big/file.data
```
...despite the fact that the file existed at both paths.  The reason you only see one line of output is that `git rev-list --objects` is just trying to show you all unique objects, and the thing is that some/big/file.data and subdir/some/big/file.data have the exact same hash, so it only shows one of the two.  When you delete one, it'll show the other.

A much better command to use to find big objects you don't want is `git filter-repo --analyze`, and then look at the generated reports.  It would tell you all the names associated with those big files, and allow you to make sure you filter all the ones you want, instead of only filtering one of them out.

**Comment by helmesjo** [comment]
@newren Thank you for the reply!
> ...despite the fact that the file existed at both paths.

From what you describe, I rather believe my problem is that I misunderstand `git filter-repo`, because what I actually want to do is to delete all files from `src/external`(completely from the repository). Hence why I expect to not see a mention of the file(s) at all. Also the size of the repo does not reduce in size as expected.

**Comment by newren** [comment]
Note that if you have the same content stored at multiple different paths, Git only stores one copy of it.  So, if you delete one of those paths from history, since the other path still exists, the repository size isn't going to shrink at all.

Anyway, you did delete `src/external` from the repo, completely.  If you want to reduce the repository size, you'll need to make sure to delete copies of that content that live under alternate paths as well, something your script is ill-suited to informing you of.

**Comment by helmesjo** [comment]
Ok, thanks. I ended up adding a bunch of filters until I had enough to cover the stray files. I'll consider this closed.
