### ISSUE TITLE
[need advice]: remove commits of single file in public master branch

### ISSUE THREAD

**Issue by SimonB97** [newren/git-filter-repo#458]
Hi there, 

i am trying to remove the commit messages/ history of a single .env file that i accidentally pushed to a public repo (i have temporarily made it private)..
i tried using the command (windows user):

`$ C:/Users/sbene/miniconda3/envs/GitChat/python.exe git-filter-repo --invert-paths --path src/.env` 

but i am receiving this error:

`fatal: not a git repository (or any of the parent directories): .git
fatal: Command '['git', 'show-ref']' returned non-zero exit status 128.`

I added the path variabe and the command has been executed from within the project folder (with git).
I have also tried a lot of different path definitions, e.g.
```sbene@DESKTOP-NO7MSQ7 MINGW64 ~/projects/gitchat (master)
$ C:/Users/sbene/miniconda3/envs/GitChat/python.exe git-filter-repo --invert-paths --path GitChat/src/.env
C:\Users\sbene\miniconda3\envs\GitChat\python.exe: can't open file 'C:\Users\sbene\projects\gitchat\git-filter-repo': [Errno 2] No such file or directory

sbene@DESKTOP-NO7MSQ7 MINGW64 ~/projects/gitchat (master)
$ C:/Users/sbene/miniconda3/envs/GitChat/python.exe git-filter-repo --invert-paths --path c/users/sbene/projects/GitChat/src/.env
C:\Users\sbene\miniconda3\envs\GitChat\python.exe: can't open file 'C:\Users\sbene\projects\gitchat\git-filter-repo': [Errno 2] No such file or directory

sbene@DESKTOP-NO7MSQ7 MINGW64 ~/projects/gitchat (master)
$ C:/Users/sbene/miniconda3/envs/GitChat/python.exe git-filter-repo --invert-paths --path c/users/sbene/projects/GitChat/.env
C:\Users\sbene\miniconda3\envs\GitChat\python.exe: can't open file 'C:\Users\sbene\projects\gitchat\git-filter-repo': [Errno 2] No such file or directory

sbene@DESKTOP-NO7MSQ7 MINGW64 ~/projects/gitchat (master)
$ C:/Users/sbene/miniconda3/envs/GitChat/python.exe git-filter-repo --invert-paths --path c:/users/sbene/projects/GitChat/.env
C:\Users\sbene\miniconda3\envs\GitChat\python.exe: can't open file 'C:\Users\sbene\projects\gitchat\git-filter-repo': [Errno 2] No such file or directory```


Thanks for any advice on how to solve this!

**Comment by newren** [comment]
Um, you are trying to run
```
C:/Users/sbene/miniconda3/envs/GitChat/python.exe git-filter-repo ....
```
with extra arguments for the `...`, but that's irrelevant because the code isn't ever getting past the first argument.  The error it is showing you is:
```
C:\Users\sbene\miniconda3\envs\GitChat\python.exe: can't open file 'C:\Users\sbene\projects\gitchat\git-filter-repo': [Errno 2] No such file or directory
```
which means that you told python.exe that you want to run a script called `git-filter-repo`, which it seems to be guessing is found in `C:\Users\sbene\projects\gitchat` (is that your current directory?) and it is not finding it.  So, where did you download git-filter-repo to?  Can you replace your command lines with the full path, e.g.
```
C:/Users/sbene/miniconda3/envs/GitChat/python.exe C:\Users\sbene\THE\DIRECTORY\WHERE\YOU\DOWNLOADED\git-filter-repo ...
```
so that python.exe knows where to find it?  Also, from the earlier error, can you make sure that you can run git first?  I.e. can you run commands like

```
git --version
```
and
```
git rev-parse HEAD
```
?  If you can't run those, then git-filter-repo won't be able to run git commands either.

**Comment by newren** [comment]
No response to questions; closing.
