### ISSUE TITLE
filter-repo removes my remotes

### ISSUE THREAD

**Issue by paulpach** [newren/git-filter-repo#46]
I am splitting a subtree,  then I want to use filter-repo to rename and delete some files in the new branch.   Here is my script:

```
$ git remote -v
origin	https://github.com/MirrorNG/MirrorNG (fetch)
origin	https://github.com/MirrorNG/MirrorNG (push)

$ git subtree split --prefix=Assets/Mirror -b $BRANCH
1/3257 (0) [0]
2/3257 (1) [0]
...
d262bbf6fd2262d3a551aa3e7cf72ea41d0f8b53
Created branch 'upm_test'

$ git remote -v
origin	https://github.com/MirrorNG/MirrorNG (fetch)
origin	https://github.com/MirrorNG/MirrorNG (push)

$git gc
Computing commit graph generation numbers:   0% (1/4981)
Computing commit graph generation numbers:   1% (50/4981)
...
Computing commit graph generation numbers: 100% (4981/4981), done.

$ git remote -v
origin	https://github.com/MirrorNG/MirrorNG (fetch)
origin	https://github.com/MirrorNG/MirrorNG (push)

# remove the Tests folder
$ git filter-repo --force --invert-paths --path Tests --refs $BRANCH
Parsed 51 commits
Parsed 265 commits
Parsed 794 commits
Parsed 1251 commits
Parsed 1597 commits
Parsed 1724 commitsHEAD is now at 9f326ba9 What happened to origin?
New history written in 0.66 seconds...
Completely finished after 0.91 seconds.

$ git remote -v
origin	https://github.com/MirrorNG/MirrorNG (fetch)
origin	https://github.com/MirrorNG/MirrorNG (push)


$ git filter-repo --force --path-rename "Examples:Samples~"
Parsed 533 commits
Parsed 1242 commits
Parsed 1906 commits
Parsed 2489 commits
Parsed 3088 commits
Parsed 3567 commits
Parsed 4145 commits
Parsed 4546 commits
Parsed 4924 commitsHEAD is now at d680d139 What happened to origin?

New history written in 0.91 seconds; now repacking/cleaning...
Repacking your repo and cleaning out old unneeded objects
Completely finished after 2.68 seconds.

# origin is not there anymore,  why is this messing with my remotes?
$ git remote -v
```

After the command `git filter-repo --force --path-rename "Examples:Samples~"`  there are no remotes anymore.

**Comment by paulpach** [comment]
I think I am missing `--refs $BRANCH` in that last command,   maybe that has something to do with it.

It should still not lose the remotes though

**Comment by newren** [comment]
Yes, absolutely, filter-repo defaults to rewriting the whole repository and as such it creates history incompatible with the original.  There are *lots* of things that can go wrong with pushing a rewritten history back up to the original location, something that other tools did not discuss or warn about in detail and which will trip up many people.  Removing the origin remote helps avoid these errors; it is encouragement for folks to stop and read the docs to make sure they are prepared and understand the ramifications (and take appropriate preventative steps) before they do something that may bite them.  (They can still push to the remote by just setting it back up, can just re-fetch, etc., so it's easy to circumvent, but I want them to at least notice something is different).

This is all documented in the following places:
  * Step 4 of [Discussion](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION) in the manual
  * Steps 2 & 3 of [Internals -- How filter-repo works](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#INTERNALS)
  * And in the documentation of both the --partial and --refs options.

As noted in the documentation for --refs and --partial, those options are designed to only make changes on a piece of history while intending to keep the rest of history as-is.  As such, those options disable the steps to map the remote tracking branches to normal branches and disable the removing of the origin remote.  Looks like you already noticed that you forgot to include --refs in the last step.

**Comment by 0xBADDCAFE** [comment]
It's not good design.

1. `git remote rm` exists for remove remote tracking branch, not for prevent `git push`. I don't want to use a function to other purpose.
2. It is documented, but only documented. Not all users see the all of document before use the command. And logs does not show that command removes remote tracking branch, it confuses users. I want to see the message like `Remote tracking branch has removed to prevent some accidents.`
3. No way to keep remote repository. If removed suddenly, need some steps to recover (failed to push, check remote URL, `git remote add <URL>`). `--refs` and `--partial` keeps remote, but it seems side effect. Can I use like `--keep-remote` at my own risk?

**Comment by ryuheechul** [comment]
My current workaround to this issue is [to use `github remote rename`](https://gist.github.com/ryuheechul/bc8a6c32f7a50bde183d1b61dbf71867).

**Comment by jcollum-nutrien** [comment]
It would be nice if there was a warning like "hey, you really should read the docs [here] before you do this, are you ready to commit? Things might go wrong. [y/n]" 

I took some advice from SO, ran a command and now my remote is gone which makes me think I did something VERY WRONG but in fact it's fine, I just didn't know it would remove my remote. 

Have you heard of Principle of Least Surprise? This violates that. Removing remotes **is a surprise** with no warning in front of it.

**Comment by newren** [comment]
> It would be nice if there was a warning like "hey, you really should read the docs [here] before you do this, are you ready to commit? Things might go wrong. [y/n]"

The premise behind your suggestion, that git-filter-repo undertakes dangerous actions without warning, is incorrect.  First of all, if git filter-repo detects the repository is not a fresh clone, it'll abort unless the user has specified `--force`.  The fact that you got to the point of it removing remotes either suggests you started with a fresh clone (in which case you lose nothing if remotes are removed since you can simply clone again), or that you explicitly overrode safety checks with `--force` (in which case, you told it to go ahead anyway).  Either of those cases make little sense in combination with your suggestion.

But that's not all.  The removal of remotes was added precisely as a way to warn users that things might go wrong if they attempt to use the results in common but dangerous ways.  git filter-repo has no control of what you decide to do with the repository after it is done running.  And, in particular, I've seen users take repository rewrites done with other tools and merge the rewritten history with the original and end up with a MUCH bigger mess than they started with.  That kind of thing takes weeks to recover from.  Since the rewritten history is incompatible with the original history, and merging the two together tends to be highly problematic, providing some mechanism which requires the user to take extra steps before they might make such a mistake is thus warranted.  Taking a step which users can override with a simple command when they understand the consequences seems like a good choice.  And, in fact, that is _exactly_ what removing the remotes does.

Also, have you heard of the principle of alert fatigue?  When you always (or frequently) display warnings, users just start ignoring them, and users get exceptionally annoyed.  Your suggestion to always show such a warning definitely runs afoul of that principle...and it does nothing to help with the potentially even bigger mistakes users might make after the tool is done running to boot.  Even if I did add such a warning, users would complain and ask for a flag for the message to be bypassed (and possibly make `--force` imply such a flag).  And all future answers on Stack Overflow would just use that new flag (and likely many of the existing ones would be edited to add that flag), and then users who just blindly follow Stack Overflow questions would just copy one of those suggestions and then come here and complain that no warning was shown.  So, the flag's only use would be to annoy users.

> Have you heard of Principle of Least Surprise? This violates that. Removing remotes is a surprise with no warning in front of it.

Of course I've heard of it.  In fact, I designed this feature with that principle in mind, and alluded to it above.  Now, with the use of this tool, it turns out it's impossible to avoid a Principle of Least Surprise violation for all users: I can either allow users to run into an extremely nasty surprise when they accidentally merge rewritten history with original history, taking them weeks to recover from; or I can give other users an entirely innocuous surprise when they really do want to force push their history over the original, taking them 15 seconds to carry on.  You seem to be suggesting that weeks of recovery time for others trumps your 15 seconds to re-add the remote?

> You could also help the user by emitting "hey here's your remotes, you'll need to add them when this is done..."

That would leave users to believe that pushing back to the remote is the right thing to do, and cause users to blindly re-add them.  That's exactly the problem I want to avoid.  People should read the documentation before re-adding them so they are aware of the pitfalls.  Anyone who has read the documentation would likely understand why this is a bad suggestion.

> This sounds so smug.

Two things:

(1) Your entire comment sounds kind of petty, to me.  I don't see how saving you from 15 seconds of work (to re-add the remotes) can possibly be more important than saving others from royally screwing up their history and requiring weeks worth of effort to recover.  I've got enough cases where people messed things up (e.g. https://github.com/newren/git-filter-repo/issues/291#issuecomment-964483206 and https://github.com/newren/git-filter-repo/issues/461#issuecomment-1529985261).  Your suggestion would add a bunch more.  I much prefer getting the "Life is so unfair that I have to run `git remote add origin ${ORIGINAL_URL}`, that takes so much time." messages.

(2) With the benefit of hindsight, I think I can say that my original response wasn't what I'd use today.  Allow me to modify it:

My decision to remove remotes was not good design. It was **_GREAT_** design, and one of the things I'm most happy about choosing when coming up with filter-repo.

**Comment by newren** [comment]
> > 3\. It is documented, but only documented. Not all users see the all of document before use the command. And logs does not show that command removes remote tracking branch, it confuses users. I want to see the message like `Remote tracking branch has removed to prevent some accidents.`
> 
> That's fair; it looks like I currently only show a message in this case in debug mode; we could make those messages always show instead.

I modified git-filter-repo to always show the message about the remote being removed, and for good measure, the message mentions a new section in the manual that explains why the remote was removed so people who don't read the docs beforehand (even with explicitly dangerous tools) can more directly find out why.  Done in a12d74249f5d (filter-repo: notify users when we remove the origin remote, 2024-07-30); example:
```
NOTICE: Removing 'origin' remote; see 'Why is my origin removed?'
        in the manual if you want to push back there.
        (was https://github.com/newren/git-filter-repo)
```
