### ISSUE TITLE
English, do you speak it.

### ISSUE THREAD

**Issue by Infro** [newren/git-filter-repo#461]
If you are filtering something, you are by definition removing something.  As such, you're naming is backwards and you're documentation should reflect that. I'd suggest replacing "filtered history" with "new history" for a start.

Also no where does it'll delete your files, it only mentions history. "writes new commits, trees, tags, and blobs" which is either an intentional lie or a really stupid omission.

ref: https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html

**Comment by Infro** [comment]
Also no where does it'll delete your files, it only mentions history. "writes new commits, trees, tags, and blobs" which is either an intentional lie or a really stupid omission.

**Comment by newren** [comment]
Hi,

Thanks for the report. One of the unfortunate things about writing a tool to assist people with destructively rewriting history, regardless of what documentation warnings I add or the number of guardrails I attempt to put into place to prevent people from accidentally doing so incorrectly, is that there are going to be some folks who ignore the warning to do the filtering on a fresh clone and then get bit by using an incorrect command.  From your report, I'm guessing you are one of them.  Sorry about that.

> If you are filtering something, you are by definition removing something. As such, you're naming is backwards and you're documentation should reflect that. I'd suggest replacing "filtered history" with "new history" for a start.

That's actually a good point.  Surprisingly, you're the first person in 5 years to bring it up.

> Also no where does it'll delete your files, it only mentions history.

That doesn't parse, but I think you meant "no where does it mention that it'll delete your files".

I'm afraid I don't understand this statement, though.  The files are obviously part of the history; that's why you add, commit, push, and pull them, so by stating that it deletes history that implies files.  However, even beyond that, including just a little more context around the quote you provided, from the first paragraph of the manual, we read:

```
Rapidly rewrite entire repository history using user-specified filters. This is a destructive operation
which should not be used lightly; it writes new commits, trees, tags, and blobs corresponding to (but
filtered from) the original objects in the repository, then deletes the original history and leaves only
the new. See [DISCUSSION] for more details on the ramifications of using this tool. Several different
types of history rewrites are possible; examples include (but are not limited to):

   * stripping large files (or large directories or large extensions)
   * stripping unwanted files by path
   * extracting wanted paths and their history (stripping everything else)
```

So the first three examples of kinds of operations that can be performed explicitly talk about deleting files, and it even opens with `This is a destructive operation which should not be used lightly`.  Also, the first two code examples in the [EXAMPLES](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#EXAMPLES) section of the manual are explicitly about deleting files -- either the filenames specified on the command line, or all but the ones listed on the command line.

Also, the small phrase you quoted actually mentions it as well: `writes new commits, trees, tags, and blobs corresponding to (but filtered from) the original objects in the repository, then deletes the original history and leaves only the new.`  That sentence refers to the four types of objects in git's data model: tags, commits, trees, and blobs.  Most users intrinsically understand the first three of those, though perhaps I could add an `(i.e. files)` hyperlinking to https://git-scm.com/book/en/v2/Git-Internals-Git-Objects right after the word `blobs`.  That may also help non-native speakers.  So we can make an improvement here.

> English, do you speak it.

Since you've taken the time to file this report, let me just take a brief moment to help you as well.  I'm guessing from this comment that you may be a non-native speaker.  This appears to be phrased as a question, but in English, questions tend to end with a question mark, so this would be better written as `English, do you speak it?`.  However, the word order is rather non-standard, a more natural ordering would be `Do you speak English?`

>  you're naming is backwards and you're documentation

A common error to fall into is mixing up homophones.  `you're` is a contraction which means `you are`, which makes no sense in either place in this sentence.  The correct word to use in your sentence is the possessive pronoun `your`.  If you want to read up more on this, see https://www.oxfordinternationalenglish.com/you-and-youre-whats-the-difference-and-when-to-use-them/ .  A similar set of homonyms that is frequently confused is there/their/they're; see e.g. https://www.grammarly.com/blog/there-their-theyre/ to learn more about those.

> which is either an intentional lie or a really stupid omission.

This kind of charged language is what leads me to believe you likely ignored the warnings to operate on a fresh clone of your data, and didn't have a backup, and entered the wrong command -- watching your files get deleted.  Much like an ill-placed `rm -rf <wrongdir>`, it gives a strong sinking feeling.  That's no fun to go through; my condolences.

Can I make a request though?  Although it's certainly natural to feel angry when you use a destructive command incorrectly and contrary to the manual, there is no need to use charged statements like this.  Leaving it out doesn't actually remove anything substantial from your report.  Further, it avoids making the other person pigeonhole on correcting the multiple errors in that specific statement, and makes it easier for them to concentrate on the underlying problem and the other good comments that you made in your report.  While not as important in this specific context, leaving out such charged statements is also good practice in general since it is part of establishing an open and respectful communication culture, and reframing failures and mistakes as learning opportunities -- two of the steps in establishing [psychological safety](https://www.babbelforbusiness.com/blog/how-to-create-psychological-safety-at-work/).  The benefits of psychological safety are huge for teams, so if you ever get a chance to take a class on it, I'd highly recommend it.  But suffice it to say that just concentrating on respectful communication can help immensely.

**Comment by Infro** [comment]
:) Loving it.
The whole thing was partly in jest which I was hoping you'd get from the title which, I thought, was iconic Not Safe For Work: https://www.youtube.com/watch?v=a0x6vIAtFcI :NSFW and demonstrated over-the-topness.  Yeah, I lost about an hour's worth of work *shrug*, go fast and break things is someone's philosophy, after all :P.

For the "writes new commits, trees, tags, and blobs" being apart of the history ok, but for files I'd slightly contest that and say that the commits, trees, tags, and blogs, are all stored in the .git folder, while the files (ignoring .gitignore and changed files) are reconstructable from the commits/trees/tags/blogs, but are also outside the commits, trees, tags, and blogs, which is why you can do things like git restore --source=HEAD. Trees are maps to the actual files, folders, and yes, tree structure, but in the context of the other words and the fact that trees have a meaning for git that is slightly different than the folder structure stored in the file system.

Psychological safety is well and good, and I believe it should be forced to contend with playfulness and psychological fortitude building.  The charged language was intentional as I use that tactic to figure out if I should be helping someone.  I believe narcissists love it, so if I get no complaints, *obviously* I'll not help them (Feel free to double check that last sentence).  

Honestly, I'm sorry if I made you feel like you had to create a detailed response and I made a huge mistake missing the word "say" in "no where does say it'll delete your files"... Anyhow, I'll be suggesting some edits to the documentation, and hopefully you'll find the edits/suggestions useful and granting greater clarity.














PS.
It's not like someone would use you're to avoid making it personal, as a just in case.... leaving hints like "you are" twice before you're, or using "your" in the next sentence.... :) Not like the unconscious would notice that and make it sting less right?... Missing the word say in "no where does *cough*say*cough* it'll delete your files"... that's cause I'm a mf-ing retard which is way worse than the omission of files being deleted :P
