### ISSUE TITLE
replace-text does not accept temporary files from shell `<(echo 'FROM==>TO')` argument: no such file or directory '/proc/XXXX/fd/XX'

### ISSUE THREAD

**Issue by andry81** [newren/git-filter-repo#467]
Example from `git extensions` console (CTRL+G):

**update-file-text.sh:**

```shell
#!/bin/bash

function call()
{
  local IFS=$' \t'
  echo ">$*"
  "$@"
}

call git filter-repo --path "$1" --replace-text "$2" "${@:3}"
```

```shell
update-file-text.sh README.md <(echo '<p/>==></p>') --refs t1~1..master
```

```
>git filter-repo --path README.md --replace-text /dev/fd/63 --refs t1~1..master
Traceback (most recent call last):
  File "c:\Python\x64\310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Python\x64\310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\x64\310\Scripts\git-filter-repo.exe\__main__.py", line 7, in <module>
  File "c:\Python\x64\310\lib\site-packages\git_filter_repo.py", line 3997, in main
    args = FilteringOptions.parse_args(sys.argv[1:])
  File "c:\Python\x64\310\lib\site-packages\git_filter_repo.py", line 2207, in parse_args
    args.replace_text = FilteringOptions.get_replace_text(args.replace_text)
  File "c:\Python\x64\310\lib\site-packages\git_filter_repo.py", line 2110, in get_replace_text
    with open(filename, 'br') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2283/fd/63'
```

**Comment by newren** [comment]
This looks to me like an operating-system/shell/python issue, not a git-filter-repo issue.

In particular, your example works just fine on Linux.  But I have noticed that bash process substitution (i.e. the `<(CMD args)` stuff) seems to have trouble running on other OSes.  Some of my scripts that used it broke when trying to run them on Mac.  I think process substitution must just be too new or something.  But there's really nothing a script like git-filter-repo can do about it; it's passed a filename, and if it can't open and read that filename, then what else could it possibly do?

If you can find out which of bash, python, or your OS to file a bug with, you can go that route.  Otherwise, I'd just have to suggest you avoid process substitution.

**Comment by andry81** [comment]
> This looks to me like an operating-system/shell/python issue, not a git-filter-repo issue.

If compare filter-branch vs filter-repo, in the latter you can not use shell substitution, which is downgrade.

**Comment by newren** [comment]
> If compare filter-branch vs filter-repo, in the latter you can not use shell substitution, which is downgrade.

I don't understand this comment.  An example might be helpful.   In particular...

You've changed from talking about process substitution, to talking about shell substitution.  Shell substitution doesn't seem well-defined to me; but I've seen it used in context to talk about either (1) parameter substitution, or (2) command substitution, or perhaps more rarely (3) the entire set of possible shell expansions (brace expansion, tilde expansion, parameter and variable expansion, command substitution, arithmetic expansion, word splitting, filename expansion, and process substitution).  But I really think that any of those, other than process substitution, should work just fine on most any OS with bash and likely at any substitution level.

Further, if you read the bash manual about [shell expansions](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Expansions) and [process substitution](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Process-Substitution), you'll note that it says things like

> On systems that can support it, there is an additional expansion available: process substitution.

Suggesting you can't expect it to work everywhere (which I'll comment more on below), and also that

> If the <(list) form is used, the file passed as an argument should be read to obtain the output of list. 

Which is precisely what git-filter-repo is doing; it's trying to open the file passed to read it.  Since filter-repo is doing exactly what is documented as the way to use it, I don't see how this is a filter-repo issue.


Now, getting back to the comment about process substitution limitations.  I noted above that your example works just fine on Linux and my code does exactly what the manual says should be done with the process substitution output, so it's hard for me to figure out what I *could* even change here.  But I'll also note, since I have the misfortune of having access to a Mac (work mandates its usage), that process substitution seems to not work so well on it either.  I have a `mydiff` script that is specifically designed to be used with process substitution, and it _always_ works on Linux but it occasionally fails on Mac whenever the level of substitution is a bit higher than normal, and I've never found a workaround besides either (a) not using process substitution, or (b) copying everything from the Mac to a sane system and running the command there.  If the Windows issue is anything like the Mac issues I experienced, your use of the update-file-text.sh intermediate script could be part of the problem.

Anyway, my experience in attempting to figure out how to work around platform-specific limitations with process substitution is not encouraging, and leads me to believe other platforms have broken process substitution that only works in very simple cases.  Since I also have no access to a Windows system to boot, unless you or another contributor have some good leads on how to work around platform bugs, I don't think there's anything I can do here.

If you or someone does have some good leads, feel free to reopen, but with the info currently present, there is no action I can take.
