### ISSUE TITLE
Suggestion to change the default replacement text

### ISSUE THREAD

**Issue by phanan** [newren/git-filter-repo#47]
First off, thanks for this amazing tool. I can't really say how much I appreciate your work on this!

Now to the issue's main point: I'm suggesting to change the default replacement text `***REMOVED***`, as `*` is more than often _treated as a special character_. For example, in Symfony's config files, `*` denotes a reference to another variable, thus simply replacing a credential with `***REMOVED***` would potentially break the app.

I know that we can change the replacement text into something safer e.g. `___REMOVED___` by appending each line in the input expression file with `==>__REMOVED___`, but I'd argue that it's rather clunky and a better solution would be either:

* Changing the default text from the library level altogether, or
* Making this a CLI option e.g. `git-filter-repo --replace-text expressions.txt --replacement=___REMOVED___`

What do you think?

**Comment by newren** [comment]
I actually copied this piece of functionality, including the default, from BFG Repo Cleaner (https://rtyley.github.io/bfg-repo-cleaner/); --replace-text was one of their really awesome ideas.  They used this default for years and years without changing it.  Honestly, I came close to making the replacement be an empty string or just erroring out if no replacement was specified (I mean, when does some random replacement *ever* make any sense??), but deferred to their experience and made things more similar for those coming from that tool.  If I were to make a change to the default, which I'm not sure if I want to do, it'd be to change it in one of those two ways.

But, having a --default-replacement flag of some sort to allow the user to switch the default without having to specify it on every line might make sense.

**Comment by phanan** [comment]
Totally agreed. A default-replacement option would be nice.

Elijah Newren <notifications@github.com> schrieb am Mi. 22. Jan. 2020 um
21:56:

**Comment by newren** [comment]
Actually, I went a slightly different route.  I stored the default replacement text in a variable that an accessing script can modify.  Also, I create a new contrib example named "no-op-example" (see commit bd2c9c4d4d (contrib: new simple no-op-example, 2020-06-06)) which provides identical behavior to filter-repo by doing the right import and calling the right high-level functions, so that people have a simple starting point for modification.

If you take the no-op-example and just add the line of code
```
fr.FilteringOptions.default_replace_text = b'NEW DEFAULT REPLACEMENT TEXT'
```

after the definition of fr and before the call to filter.run(), then you can run
```
no-op-example <filter-repo args>
```

and you'd get the same behavior as
```
git filter-repo <filter-repo args>
```

except that the default replacement text would be `NEW DEFAULT REPLACEMENT TEXT` instead of `***REMOVED***`
