### ISSUE TITLE
--invert-path does not invert path beginning a commit

### ISSUE THREAD

**Issue by andry81** [newren/git-filter-repo#473]
I wanted to remove a file starting from a commit on a range of commits.

There 2 variants:

```
master
o (3)
|` "test.txt" is changed
|
| t1
o (2)
|` "test.txt" is not changed
|
|
o (1)
 ` "test.txt" is added
```

Commits range is 1 commit - (2):

Commit range (`rev-list`) examples: `t1^!` or `t1^@..t1` or `t1 ^t1^@` or `t1 --not t1^@`

1. Completely remove path irrespective to all children:

The `test.txt` will be removed beginning from commit (2) including commit (3). The file is removed in commit (3) irrespective to a commits range.

2. Partially remove path respective to children:

The `test.txt` will be removed beginning from commit (2) and ending commit (2), excluding all the rest commits beginning commit (3). The file left existing and changed in commit (3).

Example:

```
git filter-repo --partial --invert-paths --path test.txt --refs t1^!
```

https://github.com/andry81-tests/git-filter-repo-test-2

I am trying to remove `test.txt` file from commit (2), but the script does nothing.

Is that a bug or intention? And how to distinguish variant 2 from 1?

**Comment by newren** [comment]
A couple things here:

First, let's pretend commit (2) did modify test.txt, i.e. that your history started looking like the following:
```
$ git log --graph --name-status --oneline
* 0850e3f (HEAD -> master) commit 3
| M     test.txt
* ca3d166 (t2) commit 2
| M     test.txt
| A     whatever
* ba17628 commit 1
  A     test.txt
```

In such a case, your command, as written, would change your history to the following:

```
$ git log --graph --name-status --oneline --all
* 0850e3f (HEAD -> main) commit 3
| M     test.txt
* ca3d166 commit 2
| M     test.txt
| A     whatever
| * 5a4a545 (t2) commit 2
|/  
|   A   whatever
* ba17628 commit 1
  A     test.txt
```

So, master would continue referencing the _original_ "commit 2" (the one that added a file named "whatever" as well as modified "test.txt"), while the t2 branch references the new "commit 2" (the one that only adds a file named "whatever").  So, you'd have two "commit 2"'s in your history.  Is that your intent?  If not, you should probably avoid using `--partial` and `--refs`.

Second, I think you'd benefit from understanding a bit more how `git fast-export` works.  Try this; run the following command (which will not change anything in any repo, it just prints information out):
```
git fast-export --no-data | less
```
and look through the data.  If you run that on your test repo, you'll note that the second commit does not make any mention of test.txt, because the fast-export stream does not mention all files in a commit, but just the ones that have changed since the commit's (first) parent.  Since filter-repo operates on the stream of data from fast-export, it doesn't know there's something to delete in that commit.

Third, based on the second item, note that fast-export can be told to operate on the full list of files in each commit by passing it the `--full-tree` option.  I added that option to fast-export many years ago, and considered adding support for it within filter-repo, but decided against it because I've never run across another case outside the original convoluted one that needed it.  You'd be the first, and maybe only.  You could add that option to your local copy, though; just open up git-filter-repo and search for `--show-original-ids`, and add `--full-tree` to the list of arguments being passed to fast-export.

Finally, I wouldn't be using refs to limit the range of commits (since that just gives you one new copied commit instead of rewriting the other commits to depend upon your new rewrite), but instead using logic to determine which commits to apply the change to.  So, something like:
```
git filter-repo --commit-callback '
    if commit.original_id == b"a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3":
        commit.file_changes = [x for x in commit.file_changes if x.filename != b"test.txt"]
'
```
Replacing `a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3` with the hash of the commit in question.  If you combine using this commit callback with having filter-repo pass `--full-tree` to fast-export, then I think that'd solve your usecase.

Does that help?

**Comment by andry81** [comment]
> So, master would continue referencing the original "commit 2" (the one that added a file named "whatever" as well as modified "test.txt"), while the t2 branch references the new "commit 2" (the one that only adds a file named "whatever"). So, you'd have two "commit 2"'s in your history. Is that your intent? If not, you should probably avoid using --partial and -

I have made it through the `git filter-branch` and it works as expected:

https://github.com/andry81/tacklelib/blob/master/bash/tacklelib/tools/git/git_filter_branch_remove_path.sh

> git_filter_branch_remove_path.sh test.txt -- t1^!

It works as expected. And I want to use the `git filter-repo` the same way without knowning the depths of `fast-export` or anything else behind the `git filter-repo`.

> Replacing a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3 with the hash of the commit in question. If you combine using this commit callback with having filter-repo pass --full-tree to fast-export, then I think that'd solve your usecase.

This is a clumsy way to do a simple file remove. I just want to set a range of commits to filter them out, not just a single commit and search as search the `find` utility with glob pattern something like `find . -name README* -type -f` (to remove all readme's everythere). The `git filter-repo` just drops out all these shell things and I have to recode everything.

Why not to integrate something like [plumbum](https://plumbum.readthedocs.io/en/latest/) + [xonsh](https://xon.sh/) + shell utilities builtin replacement [cmdix](https://pypi.org/project/cmdix/) + [sh](http://amoffat.github.io/sh/) for external calls. And you can code like for the shell and port `git filter-branch` to `git filter-repo`. Wouldn't it be much better?

**Comment by newren** [comment]
> > So, master would continue referencing the original "commit 2" (the one that added a file named "whatever" as well as modified "test.txt"), while the t2 branch references the new "commit 2" (the one that only adds a file named "whatever"). So, you'd have two "commit 2"'s in your history. Is that your intent? If not, you should probably avoid using --partial and -
> 
> I have made it through the `git filter-branch` and it works as expected:
> 
> https://github.com/andry81/tacklelib/blob/master/bash/tacklelib/tools/git/git_filter_branch_remove_path.sh
> 
> > git_filter_branch_remove_path.sh test.txt -- t1^!
> 
> It works as expected.

It does??  It's behavior certainly isn't what I thought you wanted based on your description in this ticket, or even based on the description within the script itself.

Perhaps the problem is that you were vague in your expectations, and we both presumed different things in the vagueness, but let me first just verify if it's behavior is what you really want, using the example you gave above.  First, the description of your simple testcase:

* You have a repo with 3 commits.
* master points to commit 3
* commit 3's parent is commit 2
* commit 2's parent is commit 1
* t1 (also a branch) points to commit 2
* master thus contains t1.

Now, if you run the command you suggested on this repo:
```
git_filter_branch_remove_path.sh test.txt -- t1^!
``` 

Then you'll end up with:
  * four commits in your repository
  * two copies of commit 2, with one "commit 2" being the original and one being the modified version
  * t2 uses the modified "commit 2"
  * master uses the original "commit 2"
  * master no longer includes t2 in its history.  They have diverged.
  
> > Replacing a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3a0b1c2d3 with the hash of the commit in question. If you combine using this commit callback with having filter-repo pass --full-tree to fast-export, then I think that'd solve your usecase.

If duplicating and modifying commits previously shared by multiple branches in just one branch (or just the listed branches) really is your intent, then that does simplify things a bit.  All you'd need to do is modify filter-repo to pass `--full-tree` to fast-export.  I haven't done that, because I couldn't imagine any usecases for it.  I still can't, because I don't understand why you'd want this.

> This is a clumsy way to do a simple file remove. I just want to set a range of commits to filter them out, not just a single commit and search as search in the `find` utility with glob pattern something like `find . -name README* -type -f` (to remove all readme's everythere). The `git filter-repo` just drops out all these shell things and I have to recode everything.

The thing is, if you are trying to modify "commit 2", then you either have to also modify "commit 3" to depend upon the modified "commit 2", or else you'll end up with two "commit 2"'s, one slightly different than the other.  You've got a "simple" 250-line script which in my opinion just creates a mess.  I was presuming you didn't want that mess, and was guiding you on how to avoid it in filter-repo.  But if you do want the mess, it is easier to get, as I noted above. 

But there's another question I have now too.  Why have you generated all these filter-branch scripts?  You should only use a tool like filter-branch or filter-repo once in a blue moon on special flag days.  (Are you using it as a `git rebase` replacement or something??)  And then it's likely to be special-case enough that the script won't resemble what you've used before anyway.  So, if you're using these enough to be writing a bunch of scripts, it makes me wonder if there might be something wrong with the workflow.

> Why not to integrate something like [plumbum](https://plumbum.readthedocs.io/en/latest/) + [xonsh](https://xon.sh/) + shell utilities builtin replacement [cmdix](https://pypi.org/project/cmdix/) + [sh](http://amoffat.github.io/sh/) for external calls. And you can code like for the shell and port `git filter-branch` to `git filter-repo`. Wouldn't it be much better?

I can't fathom a single way in which such a thing would be better, but can see several ways where it's likely to be worse, and perhaps far worse.  But what's more surprising to me, is I can't even see why you'd think it'd be better.  You're complaining about having to rewrite your scripts, and these suggestions would still make you rewrite your scripts.  If you really want something to behave like filter-branch, why not just use filter-branch?

But, if you really want another tool that just acts like filter-branch (similar to how I wrote filter-branch-ish as a demonstration of how filter-repo could be used as a library to write a filter-branch-like tool), feel free to go ahead. 
 Personally, I think making another tool like filter-branch means just copying one or more of the fundamental design flaws, duplicating its severe [performance](https://git-scm.com/docs/git-filter-branch#PERFORMANCE) and perhaps even [safety](https://git-scm.com/docs/git-filter-branch#SAFETY) issues.  If that's what you want, though, go for it; I won't stop you.  But, much like filter-branch-ish, don't be surprised if I consider the result ["an abomination of user interfaces"](https://github.com/newren/git-filter-repo/blob/main/contrib/filter-repo-demos/filter-lamely#L6-L7)

**Comment by andry81** [comment]
> If duplicating and modifying commits previously shared by multiple branches in just one branch (or just the listed branches) really is your intent, then that does simplify things a bit. All you'd need to do is modify filter-repo to pass --full-tree to fast-export. I haven't done that, because I couldn't imagine any usecases for it. I still can't, because I don't understand why you'd want this.

I don't understand it either why you think I want the flag I-don't-how-it-works-without-knowing-the-internals.

> The thing is, if you are trying to modify "commit 2", then you either have to also modify "commit 3" to depend upon the modified "commit 2", or else you'll end up with two "commit 2"'s, one slightly different than the other.

I am not trying to specifically modify the `commit 2`. This is just example, when it does work in `filter-branch` as expected and does not work as expected in `filter-repo`. In the common case it would be a different command up to the head: `git_filter_branch_remove_path.sh test.txt -- master --not t1^@`
Of cause I have limited it to show the significant difference.

> You've got a "simple" 250-line script which in my opinion just creates a mess. I was presuming you didn't want that mess, and was guiding you on how to avoid it in filter-repo.

Actually, the script is example of more predictable implementation and shows the difference with the mess produced from `filter-repo`.

> But if you do want the mess, it is easier to get, as I noted above.

You don't prove it. I just proved counter verse. Show the minimal example the opposite, until when the script does not produce the "mess" you are talking about.

And I think the `filter-branch` is just much more tested. And while I have to test both, I have got more unpredictable things from the `filter-repo`, not from `filter-branch`. The only bad thing I have got from the `filter-branch` is a slowness.

> But there's another question I have now too. Why have you generated all these filter-branch scripts?

To ease the usage of a repo rewriting. Without them the rewrite procedure been a pain in arse.

> You should only use a tool like filter-branch or filter-repo once in a blue moon on special flag days. 

This is not true. The rewrite procedure in the git is a quite often thing. And more likely the git still does not have has convenient tools to do it anytime. But of cause it must have has it.

> But what's more surprising to me, is I can't even see why you'd think it'd be better.

Because writing shell scripts easier than coding in Python or any other language. This is just a fact

> But what's more surprising to me, is I can't even see why you'd think it'd be better. You're complaining about having to rewrite your scripts, and these suggestions would still make you rewrite your scripts. 

There is must be a good reason to rewrite it, for example, a bug or issue. But tests show quite the opposite. One of these a test in this post.

> If you really want something to behave like filter-branch, why not just use filter-branch?

Slowness.

> and perhaps even [safety](https://git-scm.com/docs/git-filter-branch#SAFETY) issues

You have to prove a safety issue IS a safety issue. There is no examples or traces of it. For example, even the first bullet from the [link](https://git-scm.com/docs/git-filter-branch#SAFETY) simple is not true. When you run a command with not compatible or not supported commands, then the shell returns not zero return code, which stops the command. In most cases you will get an error without a repository rewrite. What's the safety that the documentation url talking about?

> But, much like filter-branch-ish, don't be surprised if I consider the result ["an abomination of user interfaces"](https://github.com/newren/git-filter-repo/blob/main/contrib/filter-repo-demos/filter-lamely?rgh-link-date=2023-06-06T07%3A45%3A34Z#L6-L7)

This is simply not true and I don't want to argue. Either you show a convincing example or a test, or is not proven.

**Comment by newren** [comment]
So, let's step back for a second.  If you want me to help explain how to solve your usecase, you need to actually fully describe your usecase.  You provided an example input at the beginning, both in words and via a repository that can be cloned (very helpful!), but you did not describe the expected output in much detail.  I asked about what output you wanted in both of my responses so far, but you've focused on everything else that was written instead.  So, let's focus on just this bit and we can discuss the other parts later.  So, let me repeat from my last post:

----------------

Perhaps the problem is that you were vague in your expectations, and we both presumed different things in the vagueness, but let me first just verify if it's behavior is what you really want, using the example you gave above. First, the description of your simple testcase:

  * You have a repo with 3 commits.
  * master points to commit 3
  * commit 3's parent is commit 2
  * commit 2's parent is commit 1
  * t1 (also a branch) points to commit 2
  * master thus contains t1.

Now, if you run the command you suggested on this repo:

```
git_filter_branch_remove_path.sh test.txt -- t1^!
```

Then you'll end up with:

  * four commits in your repository
  * two copies of commit 2, with one "commit 2" being the original and one being the modified version
  * t2 uses the modified "commit 2"
  * master uses the original "commit 2"
  * master no longer includes t2 in its history. They have diverged.

--------

Now, my question is, given the repository you provided, and the git_filter-branch_remove_path.sh script your provided, and the command line you suggested, did I correctly describe the behavior you want?  In other words, do you want (a) two versions of "commit 2" and master and t2 suddenly diverging, or (b) to just use the new "commit 2", with master "commit 3" be rewritten to have the new "commit 2" as its parent, or (c) something else entirely?


You did partially respond to what I had written above, so it might not be clear to you why your previous answer didn't at all answer my questions.  Let me attempt to highlight the relevant bits:

> I am not trying to specifically modify the commit 2.

This is rather confusing to me.  commit 2 is the commit that the branch t1 points at, and you explicitly told filter-branch to only look at that commit (via the `-- t1^!` arguments), so if you aren't trying to modify commit 2, then what exactly are you trying to do with your sample command?  I ran your script on your test repository, and it modifies commit 2, and you claim that git-filter-branch "works as expected", but now you claim you didn't want to modify that commit?

> This is just example...Of cause I have limited it to show the significant difference.

It's an ill-specified example; can we correct that?  Yes, I know you've shown a difference, but I could give you multiple different solutions within filter-repo that change the one thing you highlighted in this usecase (namely remove a file from a commit that didn't change it) and yet give different behaviors than each other.  When a problem has multiple distinct solutions which yield _different_ results, the problem is ill-defined.  That's why I'm asking what your actual desired behavior is.  It's not at all clear to me, and I don't feel your scripts answer it either.

**Comment by andry81** [comment]
> So, let's step back for a second. If you want me to help explain how to solve your usecase, you need to actually fully describe your usecase. You provided an example input at the beginning, both in words and via a repository that can be cloned (very helpful!), but you did not describe the expected output in much detail. I asked about what output you wanted in both of my responses so far, but you've focused on everything else that was written instead. So, let's focus on just this bit and we can discuss the other parts later. So, let me repeat from my last post:

I am already described the input and how to get the expected result:

> I have made it through the `git filter-branch` and it works as expected:

> but now you claim you didn't want to modify that commit?

I didn't say that.

> That's why I'm asking what your actual desired behavior is. It's not at all clear to me, and I don't feel your scripts answer it either.

Just do that the `git filter-branch` does.

**Comment by newren** [comment]
> > So, let's step back for a second. If you want me to help explain how to solve your usecase, you need to actually fully describe your usecase. You provided an example input at the beginning, both in words and via a repository that can be cloned (very helpful!), but you did not describe the expected output in much detail. I asked about what output you wanted in both of my responses so far, but you've focused on everything else that was written instead. So, let's focus on just this bit and we can discuss the other parts later. So, let me repeat from my last post:
> 
> I am already described the input and how to get the expected result:
> 
> > I have made it through the `git filter-branch` and it works as expected:

But you didn't describe the expected result.  I took your input, ran your program, with your arguments, and asked you to verify whether my description was the expected result or not.    I already pointed out that your input, your program, and your arguments do NOT answer the question.  So, does my description match the results you expect or not?  If not, what are your expected results?

> > but now you claim you didn't want to modify that commit?
> 
> I didn't say that.

Really?  Here's literally the exact wording you did say:

> I am not trying to specifically modify the commit 2

If that's not saying you didn't want to modify the commit, then what exactly do you mean by that sentence?  It's part of what I don't understand about your usecase.

> > That's why I'm asking what your actual desired behavior is. It's not at all clear to me, and I don't feel your scripts answer it either.
> 
> Just do that the `git filter-branch` does.

If you want something that functions exactly identical to `git filter-branch` in each and every aspect, then `git filter-branch` is the only thing in the world that will do that.  Someone asked years ago if it was possible to 

> turn git-filter-branch into a fast, compatible,
> and (maybe) safe wrapper for git-filter-repo?  That would "fix"
> filter-branch and (if done carefully) not break existing uses.

The answer is basically no: https://lore.kernel.org/git/CABPp-BEDOH-row-hxY4u_cP30ptqOpcCvPibwyZ2wBu142qUbA@mail.gmail.com/

But, we can certainly solve most usecases.  To do so, we need the usecases described, though.  Meaning, we need to understand what output are expected with given inputs.  I've asked you three times to explain what output you want.  I cannot solve a problem that is not explained.  Would you like to attempt to actually answer this fundamental question instead of brushing it off a fourth time, or shall we close the ticket?

**Comment by andry81** [comment]
> But you didn't describe the expected result. I took your input, ran your program, with your arguments, and asked you to verify whether my description was the expected result or not. I already pointed out that your input, your program, and your arguments do NOT answer the question. So, does my description match the results you expect or not? If not, what are your expected results?

Why ask if the result is always unique? The file is removed and there is nothing else to expect. What is more to explain here?

> Really? Here's literally the exact wording you did say:

I said I am trying to remove the file on purpose and didn't said I don't want to modify a commit. If is required a commit in range to be modified because has that file, then go ahead and modify.

There is context behind the sentence you are ignoring:

> I am not trying to specifically modify the commit 2. This is just example, when it does work in filter-branch as expected and does not work as expected in filter-repo. In the common case it would be a different command up to the head: `git_filter_branch_remove_path.sh test.txt -- master --not t1^@`
> Of cause I have limited it to show the significant difference.

The expected result: the file is removed using any commits range you want and not matter which one commit is changed or not as long it inside the commits range. The exact commits range is just an example.

> If you want something that functions exactly identical to git filter-branch in each and every aspect, then git filter-branch is the only thing in the world that will do that. Someone asked years ago if it was possible to

So you are saying the filter-repo could not remove a simple file from the example above?

> The answer is basically no: [lore.kernel.org/git/CABPp-BEDOH-row-hxY4u_cP30ptqOpcCvPibwyZ2wBu142qUbA@mail.gmail.com](https://lore.kernel.org/git/CABPp-BEDOH-row-hxY4u_cP30ptqOpcCvPibwyZ2wBu142qUbA@mail.gmail.com/)

Well, good. There is guys which wants the same as I.

>  I've asked you three times to explain what output you want. 

And I already answered you three times that the file must be removed.

**Comment by andry81** [comment]
> Your "if" is false, that's why: the result is not always unique. You keep avoiding the question. Yes, the file is removed...but from what? What is in the repository, in both master and t1, after the operation?

This is going ridiculous. You keep asking that already answered. And keep generating that bullshit AI generator text.

**Comment by newren** [comment]
> > If you really want something to behave like filter-branch, why not just use filter-branch?
> 
> Slowness.

And yet you are requesting 3 things that *cause* filter-branch's horrible slowness: usage of shell, a checked out repository to operate on with every commit, and operating on the full set of changes in a commit rather than just the things that changed.

If you give up one or two of those, you can have improved speeds.  If you give up none of them, you'll end up with a tool that merely copies filter-branch's slowness with very minor performance improvements at best.

> > and perhaps even [safety](https://git-scm.com/docs/git-filter-branch#SAFETY) issues
> 
> You have to prove a safety issue IS a safety issue. There is no examples or traces of it. For example, even the first bullet from the [link](https://git-scm.com/docs/git-filter-branch#SAFETY) simple is not true.

Oh, it's totally true.   It claims that some filter-branch commands, when run on a different OS, will yield dramatically different results.  I saw multiple developers experience it and come to me for help.   Further, I documented a specific example of OS-specificness of filter-branch commands on the [main page for the filter-repo project](https://github.com/newren/git-filter-repo).  Further, that whole bulleted list was peer reviewed by multiple core developers in the Git community.

And your reaction is to deny that any examples exist anywhere, and state that all of those core Git developers are wrong?

Wow.

**Comment by newren** [comment]
> This is going ridiculous. You keep asking that already answered. And keep generating that bullshit AI generator text.

You know, I totally agree.  I've asked five times and tried to make it very excruciatingly clear that I am asking you to answer simple questions about what the output looks like.  Some times you ignore the question and answer in terms of operations that should be performed, other times like this you simply ignore the questions entirely.  There wasn't a single time you answered the actual questions I asked.

Clearly, trying to ask you to answer the questions I have that I need answered in order to provide a solution for you is a waste of my time.  Since you don't want to bother helping me to help you, let's end this here.  I'll ask you to just continue using filter-branch rather than interacting with this project further.  Thanks.
