### ISSUE TITLE
"fatal: cannot lock ref" when issuing filter-repo command

### ISSUE THREAD

**Issue by chambers-y** [newren/git-filter-repo#48]
Hi,

I'm trying to move one subdirectory out of my git repo like but I keep getting a "fatal cannot lock"

```
chambers:~/tmp/baker (master) $ git filter-repo --path baker/assets
fatal: cannot lock ref 'refs/heads/remote_branch': Unable to create '/Users/chambers/tmp/baker/.git/refs/heads/remote_branch.lock': File exists.
```

I checked the dir and verified that "remote_branch.lock" is not present.

I am running git@2.23.0 & python 3.7.4 on Mac OSX Mojave.

**Comment by newren** [comment]
What's the output of `git show-ref` and, if that output is big, then perhaps the output of just `git show-ref | grep -i remote_branch`?

**Comment by chambers-y** [comment]
Thank you for responding.  As you predicted, `git show-ref` outputs quite a bit.
The output of `git show-ref | grep -i remote_branch` is:

```
chamber:~/tmp/baker (master) $ git show-ref | grep -i remote_branch
d83eb71ac940c0dc6188865ddc5560b9863eaf3d refs/remotes/origin/remote_branch
2ad485fc5fbd8b886a8609b283217a221a77844f refs/remotes/origin/remote_branch
```

Is there a conflict between these two refs?

**Comment by newren** [comment]
Um, that's not two refs, that's just one.  I expected to see two branches that differed in case only (e.g. refs/remotes/origin/remote_branch and refs/remotes_origin/Remote_Branch) and point out that you're probably on a buggy (case insensitive) filesystem, but now I'm left wondering how you ended up with a single ref that points at two different places.  It might still be some kind of case insensitive insanity but perhaps with more steps to get to this point.  So a few more questions:

What's the output of `grep -i remote_branch .git/packed-refs` and `find .git/refs -iname remote_branch`, and `git ls-remote origin | grep -i remote_branch`?

**Comment by chambers-y** [comment]
Sorry for the confusion. I just realized that the first branch started with a capital case and the second one started with a lower case: it looks like case insensitivity is the culprit after all. 

I have included the full output with the (real) branchname below to be clear:

``` 
chambers:~/tmp/baker (master) $ git show-ref | grep -i API_changes_to_surface_all_named_layer
d83eb71ac940c0dc6188865ddc5560b9863eaf3d refs/remotes/origin/API_changes_to_surface_all_named_layer
2ad485fc5fbd8b886a8609b283217a221a77844f refs/remotes/origin/api_changes_to_surface_all_named_layer

chambers:~/tmp/baker (master) $ grep -i API_changes_to_surface_all_named_layer .git/packed-refs
d83eb71ac940c0dc6188865ddc5560b9863eaf3d refs/remotes/origin/API_changes_to_surface_all_named_layer
2ad485fc5fbd8b886a8609b283217a221a77844f refs/remotes/origin/api_changes_to_surface_all_named_layer

chambers:~/tmp/baker (master) $ find .git/refs -iname API_changes_to_surface_all_named_layer
chambers:~/tmp/baker (master) $
# no output

chambers:~/tmp/baker (master) $ git ls-remote origin | grep -i API_changes_to_surface_all_named_layer
d83eb71ac940c0dc6188865ddc5560b9863eaf3d	refs/heads/API_changes_to_surface_all_named_layer
2ad485fc5fbd8b886a8609b283217a221a77844f	refs/heads/api_changes_to_surface_all_named_layer
```

Should I run `git filter-repo` on a linux operating system?

**Comment by newren** [comment]
Ahah, since git will store branches by default in files based on the name of the ref (e.g. `.git/refs/remotes/origin/API_changes_to_surface_all_named_layer` and `.git/refs/remotes/origin/api_changes_to_surface_all_named_layer`), any repository with branches/tags that differ in case only cause problems on a case-insensitive filesystem.  The reason you can sometimes work with it is that git tries to move refs that you haven't used for a while from their individual files to combine them all into one big `.git/packed-refs` file (and puts everything in there for new clones).  So things work until you attempt to touch both branches, and history rewriting touches both branches.

As to the way forward, you have a few choices:
  * Run on linux (on a case sensitive filesystem, though the default filesystems all are)
  * Create a case sensitive filesystem on your Mac; it may not be the default, but macs do support it
  * Delete or rename one of these conflicting branches before doing any history rewrites.

Which of these you choose is up to you; I'm a fan of using linux, but the others should be able to solve your problem as well.

**Comment by chambers-y** [comment]
Thank you for the in-depth response. I'll give it a shot and update this thread with the results.

Fingers crossed!

**Comment by chambers-y** [comment]
Your suggestion fixed my issue.

Thanks for the wonderful tool. I appreciate being able to copy-paste one file and edit it to fit my needs.

Great job, Maintainer!

**Comment by rggammon** [comment]
I'd just add that, if you are on windows, you can install Windows Subsystem for Linux (WSL2) - I hit this issue, installed WSL2+Alpine, and was able to get a case sensitive filesystem this way.

**Comment by ruben-cit** [comment]
For future people: I ran into the same issue and trying to solve using a Docker Debian image didn't work. What ended up working was creating a case-sensitive volume on my Mac (via the article [here](https://brianboyko.medium.com/a-case-sensitive-src-folder-for-mac-programmers-176cc82a3830)) and running the commands in there.

**Comment by josephmate** [comment]
Another workaround if you don't need all those branches was to clone with:
```
git clone --branch staging --single-branch git_uri
```
since there is only one branch, there is no way two branches are the same when ignoring case!
