### ISSUE TITLE
fatal: No configured push destination.

### ISSUE THREAD

**Issue by longgb246** [newren/git-filter-repo#497]
I use this command to delete all submissions of dataset/demo/logistic_data.csv files in history:

git filter-repo --force --path dataset/demo/logistic_data.csv --invert-paths

But this error occurred, what is the reason?

fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

**Comment by newren** [comment]
git-filter-repo intentionally removes the `origin` remote after running, because the history is no longer compatible with the original history, and if you are not careful about forcing everyone to reclone and taking special effort to clean up "hidden" refs used by git forges, then you run a high risk of combining the incompatible histories and ending up with an even bigger mess.  Pushing to a new URL avoids many potential pitfalls here, but using a new repository to push to requires you to manually set it up and you have not done so yet.

Please carefully read https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION (and note this was documented directly in the the first bullet under item 5 in that section).

**Comment by drjasonharrison** [comment]
It's interesting that tutorials on using git-filter-repo don't discuss this:
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository
- https://support.atlassian.com/bitbucket-cloud/docs/maintain-a-git-repository/
