### ISSUE TITLE
How to install git-filter-repo in an existing Git installation

### ISSUE THREAD

**Issue by nomennescio** [newren/git-filter-repo#5]
Title says it all. Documentation seems to be missing on how to install git-filter-repo.

**Comment by nomennescio** [comment]
I noticed that it requires at least Git 2.22 (2019 Aug), so this is probable not useable for me for some time until that version has propagated throughout all distributions. Back to filter-branch for the time being.

**Comment by newren** [comment]
Yep, I've been sending several fast-export and fast-import patches upstream that are needed for filter-repo, and so a fairly recent version of git is needed.  A quick clarification, though: Git 2.22 was from June, not August.  (2.23 was from August, and you only need 2.23 if you pass the --preserve-commit-encoding option.)

**Comment by nomennescio** [comment]
As for 2.22 I was referring to the latest bugfix 2.22.1, which is from August, should have mentioned that.

**Comment by newren** [comment]
There is now an INSTALL file at the top of the repo with instructions.

**Comment by swordligit** [comment]
How to auto complete the command? copy the git-filter-repo to git --exec-path, 
but cannot use auto completion.

**Comment by newren** [comment]
@swordligit: Isn't bash completion to reduce typing for frequently used commands?  Since git-filter-repo is for rewriting history, which should be done sparingly, why would it be frequently used?

Anyway, someone could add the necessary bash or zsh completion rules via some kind of script, much like git did for all its commands.  One could depend upon the functions in contrib/completion/git-completion.bash to help since folks who want filter-repo completion almost certainly are using git completion, but the rules still need to be defined.  I'm unlikely to do that myself, as I just don't see the point for a rarely used command.

Also, please note that completion is an entirely separate issue from the existing one, so open a new issue if you want to discuss further.

**Comment by swordligit** [comment]
OK，got it, Thanks.
Just confused, before installing the fiter-repo, the filter-branch auto-completion works, 
after installed filter-repo, even the filter-branch auto-completion fails, maybe the are
ambiguous.
Anyway, I can add a bash completion.

**Comment by celroid** [comment]
Installation instruction for Windows would be helpful.

**Comment by kunom** [comment]
@celroid To be able to run `git filter-repo -h` from a standard command line on Windows 10 1903, I had to
* Manually add the Python interpreter location and the scripts folder to the path.
```
set path=%path%;C:\Users\YOURLOGIN\AppData\Local\Programs\Python\Python38
set path=%path%;C:\Users\YOURLOGIN\AppData\Local\Programs\Python\Python38\Scripts
```
* Deactivate the installation-on-demand handling for _Python.exe_ and _Python3.exe_ under _Start > Manage app execution Aliases_

**Comment by stevensrf11** [comment]
god dam sob gitbass missing about mth fcker git command needed to stuff everything

**Comment by stevensrf11** [comment]
starting to wonder if gitbash is just a pile of trash
