### ISSUE TITLE
git-filter-repo complained about lock file in large repos (~1.9GB)

### ISSUE THREAD

**Issue by txvu100** [newren/git-filter-repo#512]
Hello, I hope you can shed light on an issue I'm having when I use the script. It complained about a lock file existing in a branch but when I checked, that file did not exist. So I suspect it was a race condition when Git hadn't deleted the lock file but already moved on to another Git operation. I tried with other smaller repos and it worked perfectly.

Here's the command I ran:
`python ../git-filter-repo.py --force --path <path> --to-subdirectory-filter <parent_folder>`

And this is the error:
```
fatal: cannot lock ref 'refs/heads/DEV/RT-9957': Unable to create 'C:/Users/<user>/<repo_name>/.git/refs/heads/DEV/RT-9957.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git update-ref failed; see above
```

**Comment by newren** [comment]
This is almost certainly a case where you have two branches that differ only in name.  E.g. if you had one branch named `DEV/RT-9957` and another named `dev/RT-9957`.  In packed form, Git stores several branches in a single file, but in unpacked form, git stores one branch per file, named after the branch.  Since git-filter-repo uses fast-export and fast-import to do its work, and those will write loose references, and you are unfortunately using a filesytsem not capable of handling files that differ in case, you get this error.  There's no race either; you'll hit it deterministically, 100% of the time (though when fast-import hits the error, it cleans up after itself and you no longer see the problems).

To work around this, either do the filtering on a more capable filesystem that can handle filenames differing in case only (e.g. run it on Linux), or find the relevant references and rename them before doing the filtering.

**Comment by newren** [comment]
You can find more in #48 (and #156 and #325), of which this is a duplicate.  Anyway, hope that helps.

**Comment by harshita-gupta** [comment]
I'm running into this issue on a volume that does seem to be case sensitive. I verified this via:

```
ubuntu@ip-172-31-46-68:/data3/myrepo.git$ touch helloworld
ubuntu@ip-172-31-46-68:/data3/myrepo.git$ less HellOWORLD
HellOWORLD: No such file or directory
```
