### ISSUE TITLE
remark: Pity that this tool can't run scripts/programs and it is not clearly stated

### ISSUE THREAD

**Issue by Challanger524** [newren/git-filter-repo#544]
Only place where it is mentioned - is the bottom of [Documentation/converting-from-filter-branch.md](https://github.com/newren/git-filter-repo/blob/main/Documentation/converting-from-filter-branch.md) with the words:

> filter-repo decided not to provide a way to run an external program to do filtering, because most filter-branch uses of this ability are riddled with [safety problems](https://git-scm.com/docs/git-filter-branch#SAFETY) and [performance issues](https://git-scm.com/docs/git-filter-branch#PERFORMANCE).

Would be nice to add on frontal `readme.md`  next paragraph:
## What `git-filter-repo` can't do versus `filter-branch`

**Comment by newren** [comment]
If you continue reading in the same page, under https://github.com/newren/git-filter-repo/blob/main/Documentation/converting-from-filter-branch.md#running-a-code-formatter-or-linter-on-each-file-with-some-extension, you'll see that an example is provided of using this tool and running scripts/programs.  You'll also find examples in the discussion in issues (e.g. https://github.com/newren/git-filter-repo/issues/296) and in PRs (e.g. https://github.com/newren/git-filter-repo/pull/464).  Further, I wrote a full replacement for git-filter-branch that passed the testsuite doing everything that git-filter-branch did as a plugin/script on top of git-filter-repo (see https://github.com/newren/git-filter-repo/blob/main/contrib/filter-repo-demos/filter-lamely), showing that git-filter-repo can do basically everything that filter-branch can do.

git-filter-repo certainly doesn't make it as easy as a simple command line parameter to do this, precisely because most uses of this in filter-branch were an ill-considered abuse that resulted in all kinds of safety problems and performance issues.

But, it can totally do it, and stating that it can't would be erroneous.  So, I'll have to close this issue out.
