### ISSUE TITLE
FR: Filter into new repo

### ISSUE THREAD

**Issue by dronus** [newren/git-filter-repo#562]
It would be useful if git-filter-repo could directly output into a new (bare) repo. 

For example, extracting a small subproject or code from a content-heavy repository currently requires the full local non-cloning step, which may take a long time and doubles the amount of storage space needed.

As far as I understand, the filtering works by fast-export and fast-import, so may be a transfer into a new, empty repo is possible in the same step? So the initial cloning could be left out, and git-filter-repo would just write a new repo with all changes applied.

**Comment by newren** [comment]
> It would be useful if git-filter-repo could directly output into a new (bare) repo.

You can create a new (bare) repo yourself, and then pass its path to the `--target` option to have git-filter-repo write to it; so this is already basically supported.

> For example, extracting a small subproject or code from a content-heavy repository currently requires the full local non-cloning step, which may take a long time and doubles the amount of storage space needed.

If you write to a separate bare repository, then filter-repo has to filter all data as well despite the fact that most filters usually can avoid that step -- and this can take a really long time.  Plus, if your filter is only a few things, this essentially doubles the amount of storage space needed.  So, I'm not sure it really saves anything.  But I made it an option because it was relatively easy to do and people might have special filtering needs where it just makes sense for them to use.

> As far as I understand, the filtering works by fast-export and fast-import, so may be a transfer into a new, empty repo is possible in the same step?

Yep, entirely possible, and there's tests in the testsuite to make sure it continues working.
