### ISSUE TITLE
Remove filtered paths from original repo

### ISSUE THREAD

**Issue by m1nkeh** [newren/git-filter-repo#58]
Still working on re-structuring some of our repositories.. what is the best way to effectively remove the filtered portion from the original repo?

Considered this, but i've not tried it at all:-
```
git clone <path to clone> my-fresh-repo
git filter-repo --path 'Some.Path/' --force
git remote add origin <path to new origin>
git push -u origin --all
```
Then, to tidy the original..
```
git clone <path to clone> my-fresh-repo-inverse
git filter-repo --path 'Some.Path/' --invert-paths --force
git pull <original remote> master
git remote add origin <original remote>
git push -u origin master
```
I am concerned that re-writing of the history is going to do some very unpleasant things to the original repo though.. **especially as people are still working on it**.. is am looking for a clean split as if it were never there and kinda thinking out loud .. recommendations welcome, ty!

**Edit**: I tried it on a test repo, and all my history got duplicated... so i guess there is a 'better' way? Maybe I'll simply delete the split paths by hand, and merge it as a 'normal' change.

**Comment by newren** [comment]
Have you read https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION, particular the parts about "recovering from upstream rebase" and item 4?

**Comment by newren** [comment]
I'll go ahead and close this, assuming the links above answered the question.  Let me know if you have further questions about this, though.

**Comment by m1nkeh** [comment]
Oops, apologies, didn't see the earlier reply!

I shall review 🙂

**Comment by m1nkeh** [comment]
> Have you read https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION, particular the parts about "recovering from upstream rebase" and item 4?

Right, given that a reply, and i am concluding that what i am considering is quite a bad idea?

The use case I am trying to cater for here is (re)moving sections of my target repo in to other ones a piece at a time over a period of weeks.. so what i'll probably do is just script what i want to move to new repos, run that over a few days, and then when done invert all the commands on the original repo and push somewhere new.

Ty.

**Comment by newren** [comment]
Yeah, making people go through repeated history rewrites sounds very problematic, and it is also a bad idea to just push a rewrite without informing other people using the repo.  It's a big flag day event kind of thing.  Your new plan sounds like a better idea, but you'll still need to be careful to coordinate with folks so that they don't keep adding to directories that you have extracted in the mean time or you'll risk losing those changes when you do the final cutover.

Yes, coordination is painful and history rewrites requiring them can thus be very painful.  But the need behind such coordination was totally part of the design goals behind git; they wanted to prevent situations where someone just broke into the server and modified history and no one was any the wiser when folks tried to download updates.  The reason they designed for such a scenario was that someone tried this exact thing with the linux kernel before git was invented -- and the perpetrator would have succeeded had the kernel been using cvs or svn, but the problem was noticed due to some integrity checks that bitkeeper performed.
