### ISSUE TITLE
Can you please help me avoid adding parameters when the local files become fewer after executing the command

### ISSUE THREAD

**Issue by hklinux2010** [newren/git-filter-repo#621]
git filter-repo  --path . --commit-callback '
from datetime import datetime
cutoff_time = 1704038400
commit_time = commit.committer_date.decode()
print(commit_time.split(" ")[0])
if int(commit_time.split(" ")[0]) < int(cutoff_time):
    commit.skip()
'

This is the command I am executing to clear the previously submitted history of 1704038400
How to use this tool to delete historical commit records without deleting local files, in order to reduce the size of Git

**Comment by newren** [comment]
The subject of the issue makes no sense; I don't understand it.

The parameter `--path .` never makes any sense.  See https://github.com/newren/git-filter-repo/blob/main/Documentation/FAQ.md#How-should-paths-be-specified

commit.skip() is a almost always a bad idea.  See https://github.com/newren/git-filter-repo/blob/main/Documentation/FAQ.md#Removing-specific-commits-or-filtering-based-on-the-difference-aka-patch-or-change-between-commits and https://github.com/newren/git-filter-repo/issues/534#issuecomment-2264344722

Reading your callback, I suspect you are trying to delete all commits older than a certain date, squashing all their changes into later ones.  If so, https://github.com/newren/git-filter-repo/blob/main/Documentation/examples-from-user-filed-issues.md#Remove-commits-older-than-N-days might be of interest to you, though I think it's a bad solution in general.  Especially if you're just trying to reduce the size of your history, which is usually predominantly due to a few big files rather than the total sum of history.

> How to use this tool to delete historical commit records without deleting local files

When you rewrite history to nuke particular files, the files in the local directory should be modified to match.  If you want a copy of those local files, make a copy somewhere else first.  

> in order to reduce the size of Git

Read the manual.  Look into the --analyze option.  Odds are you want to use the --path option, together with --invert-paths, to get rid of the large portions of history.

**Comment by hklinux2010** [comment]
Is there a detailed tutorial on how to reduce the size of a warehouse？ 
Please help me！

**Comment by newren** [comment]
Did you read any of the links I posted, or look into the --analyze option I suggested?

**Comment by hklinux2010** [comment]
This is generated after my execution

![image](https://github.com/user-attachments/assets/1577dd03-1079-47e2-84a6-908b04106910)

I don't quite understand the meaning of each file

**Comment by hklinux2010** [comment]
git replace --graft ****************************
git filter-repo --force

**Comment by hklinux2010** [comment]
```
git replace --graft ****************************
git filter-repo --force

```
I used this command, but the size did not decrease significantly

**Comment by newren** [comment]
> This is generated after my execution
> 
> ![image](https://github.com/user-attachments/assets/1577dd03-1079-47e2-84a6-908b04106910)
> 
> I don't quite understand the meaning of each file

Did you consider reading the README in the directory?

> I used this command, but the size did not decrease significantly

Yeah, that means you were taking a wild guess at what was "big" in history, and your guess was wrong.  As I stated before in this ticket about this solution of removing everything older than a certain commit:

> ...though I think it's a bad solution in general. Especially if you're just trying to reduce the size of your history, which is usually predominantly due to a few big [files/directories/extensions] rather than the total sum of history.

So, you need to find out what is big from the output of the --analyze command, and then pick filter-repo commands that will remove the bits that are big that you don't need.

**Comment by hklinux2010** [comment]
Thank you for your patient answer
