### ISSUE TITLE
Question: --replace-text only on certain files

### ISSUE THREAD

**Issue by ilya-gritsenko** [newren/git-filter-repo#74]
Is there any way to apply --replace-text only to files with certain extensions? I can't seem to find a solution in the documentation.

The tool is awesome by the way, very fast in comparison to filter-branch.

**Comment by newren** [comment]
Oddly enough, I added this functionality to bfg-ish (with the flag --filter-content-including), but never circled back around and added it to git-filter-repo.  Does bfg-ish (from contrib/filter-repo-demos/) work for you?

I could perhaps lift the code from bfg-ish and put it in git-filter-repo.

**Comment by ilya-gritsenko** [comment]
So instead of --replace-text in got-filter-repo I should use bfg-ish --replace-text with --filter-content-including flag, correct?

**Comment by newren** [comment]
Yes.

But there is one other slight difference: if you are using replacement strings, bfg-ish uses $1, $2, etc. for replacement strings whereas filter-repo uses \1, \2, etc.  The reason is that filter-repo is built upon python and thus defines regex strings in terms of python regex functions.  bfg-ish, however, was meant to mimic bfg, which was implemented in scala, which because of that used syntax based upon what java regex functions declared.

**Comment by ilya-gritsenko** [comment]
Got it, thank you!

**Comment by newren** [comment]
I implemented a new flag for filter-repo to handle this over in two commits on the [replace-text-limited-to-certain-files branch](https://github.com/newren/git-filter-repo/tree/replace-text-limited-to-certain-files).  This does the basic work and has tests, but there's a couple things I'm still mulling over or need to clean up:
  * I'm not sure if I like the name --replace-text-filename-callback or not.  I kind of like that it has "--replace-text" as part of the name because it makes it clear what it applies to, but the name is so long it feels kinda clunky.
  * I'm not sure I like the cat-file --batch additional process being forked off.  It's needed in this case, but just seems slightly ugly on the implementation side.  I think I handled cleanup okay, but there might still be some ugly special cases.  I'm leaving it in a branch to give myself a little time to think over this.  If I haven't come up with any in a few weeks, it's probably okay.
  * And finally, a minor issue that should be easy to clean up: I noticed just before pushing that it doesn't work together with --source, because the cat-file --batch process should run within the directory of the --source argument if one is supplied.

**Comment by totph** [comment]
Could the file content of a `Blob` (which has no filename attached) be reached or made reachable via `Commit.file_changes[]`, and the `FileChange.blob_id`? Possibly as an optional step because it is expensive?

This would cover a lot of cases which otherwise only the `git-filter-branch` option `--tree-filter` can process. Or is this explicitly a non-goal (see [Running a code formatter](https://github.com/newren/git-filter-repo/blob/main/Documentation/converting-from-filter-branch.md#cheat-sheet-additional-conversion-examples))?

**Comment by Challanger524** [comment]
### Solution
`git filter-branch --tree-filter "find . -path './src/*' -regextype egrep -regex '.*\.(hpp|cpp)' -exec perl -0777 -pe 's{\n\n\n+}{\n\n}g' -i {} \;" <branch/HEAD/hash..HEAD>`
Was replacing ">1 blank lines" with single one

**Comment by newren** [comment]
This is covered by the new --file-info-callback added in commit 615720731589 (filter-repo: add a --file-info-callback, 2024-10-23), which adds a callback allowing you to specify whether to apply the replacement text to a file based on its name and/or contents.

**Comment by genwyse-michel** [comment]
Hello. I must be completely stupid, it's a pity to understand that at my age, but I cannot understand at all how the --file-info-callback works to apply a replacement only on  certain files. Actually the whole tool is beyond comprehension including --dry-run. I tried --dry-run --replace-text with a replacement file that will match nothing, just to see, and I get absolutely irrelevant differences such as double quotes removed from files where nothing should change. How could I use this to know ho my command worked or not ?? I feel like I'd be better off studying the git repo system and doing the changes by hand. Ok I did understand something though, the hard way. --path is a sure way to lose all your files. And the manual is not helping, since in spite of saying that this is use to apply a replacement file onto some files only, they explain all usages (renaming files, changing the mode) but this one. I assume that it must be obvious and that I am stupid, as I said. OK I understood that I probably completely messed up my copy of the repo, though, by using --replace-text. Thank you.

Edit: I found the hint (in issue #237) about how to use the outputs of --dry-run to know what could happen. I am crying now.

So I did the 'dry-run procedure in order to get a clean comparison file. If I run filter-repo with replace-text, I can see the replacements, I have no information at all about the changed files here, but who cares. At least I have the changes.

So I try with --dry-run --file-info-callback='return (filename, mode, blob_id)'
because I am really not sure of what it would do with an actual change, and I expected that nothing is changed, right ? Stupid me. The diff gives thousands of changes. Like the "return (filename, mode, blob_id)" changed everything. 

It's insane.
