### ISSUE TITLE
How to use git-filter-repo to merge one repo as subdirectory into another

### ISSUE THREAD

**Issue by return-tosleep** [newren/git-filter-repo#79]
While trying to use `git filter-branch` to merge repos using this [gist][1]. Adding just the relevant snippet in question:

```
git filter-branch -f --prune-empty --tree-filter '
        mkdir -p "${REPO_NAME}_tmp"
        git ls-tree --name-only $GIT_COMMIT | xargs -I{} mv {} "${REPO_NAME}_tmp"
        mv "${REPO_NAME}_tmp" "$REPO_NAME"
    '
```

I got a warning from git stating the following:

```
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as 'git filter-repo'
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
```

So, I took a look at `git filter-repo`, the [description][2] states the following:

>restructuring the file layout (such as moving all files into a subdirectory in preparation for merging with another repo, ...

This showed that this issue can be resolved with `git filter-repo`, but even after checking the documentation and given [examples][3] I could not find a way to achieve this. Can someone please help me with the same.

  [1]: https://gist.github.com/icholy/6491787bbb6894dbf4fe69a743975332
  [2]: https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DESCRIPTION
  [3]: https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#EXAMPLES

**Comment by newren** [comment]
Yeah, it's not an example in the manual, in part because it features so prominently as _the_ example of the README: See https://github.com/newren/git-filter-repo#simple-example-with-comparisons (though that considers three things rather than just one)

The basic translation of your filter-branch command is
   git filter-repo --to-subdirectory-filter ${REPO_NAME}

But I should warn you that both your filter-branch command and this filter-repo command don't handle cases where you are concerned with tags from your old repo.  If you have tags in your old repo and want them also to be included in the history after merging into the bigger repo, and if any of the tag names conflict, then you may want to rename the tags in your repo before merging into the bigger repo.  filter-repo has a nice --tag-rename flag for handling that for you (again, see the link to the example from the README).

Hope that helps; let me know if it's not clear enough.
