### ISSUE TITLE
Extract feature to library

### ISSUE THREAD

**Issue by davestewart** [newren/git-filter-repo#80]
After quite a bit of trial and error, I worked out how to extract a feature (folder) to a library.

```bash
# from
/some-project/src/some-folder/some-feature/*

# to
/some-package/src/*
```

The tricky bit was because both source and target folders started with `src` but a temporary folder and rename step fixed it. 

For anyone needing to do the same, I documented the rationale, steps and code in a gist:

https://gist.github.com/davestewart/1273ca0d1615c79879a9e61167961210

**Comment by newren** [comment]
Why'd you use
```
git filter-repo \
    --path src/some-folder/some-feature \
    --to-subdirectory-filter tmp \
    --path-rename tmp/src/some-folder/some-feature:src \
    --force
```
instead of
```
git filter-repo \
    --path src/some-folder/some-feature \
    --path-rename src/some-folder/some-feature/:src/
```
In other words, why'd you need the temporary folder insertion?  (Or was it just that trial and error led you to a slightly more complicated result than you needed)  Also, your description for --force ("use the force flag because we removed the origin") makes no sense to me, and suggesting it without proper rationale seems risky.  --force is there to override the fresh clone check; if people run filter-repo on a repository that isn't a fresh clone and get their command wrong or ran from the wrong directory (as I did once), then the fresh clone checks can flag them to let them know they are running on a copy that the might not have a backup of.  With --force, there is no safety check and their data is irrecoverably modified and overwritten.  I suspect you used --force because you made some changes during your trial and error, but you knew it was a clone that you had a backup of so you just used --force anyway.

Also, sidenote, but I prefer to put trailing slashes on directory names in --path-rename, otherwise if I have unfortunately named files then something like
   --path-rename sources/jump:sources
could result in renaming paths like `sources/jumpy` to `sourcesy`.

**Comment by newren** [comment]
I'll assume you either didn't have questions or that my above comment answered all questions.  Let me know if this isn't the case.

**Comment by davestewart** [comment]
Hey,

Sorry - I'm getting a lot of email at the moment and didn't see this!

So, to tackle your comments:

Yes, there was a lot of trial and error, so I'd be happy to go back and review! I'll do that now, then I can check your suggestions as I respond.

OK, in order:

```bash
# clone repo
git clone https://github.com/---/---.git extract-test
cd extract-test

# switch branches
git checkout 0198-feature-tour

# run simpler code
git filter-repo \
    --path src/modules/tour/content/ \
    --path-rename src/modules/tour/content/:src/
```
```
Aborting: Refusing to overwrite repo history since this does not
look like a fresh clone.
  (expected at most one entry in the reflog for HEAD)
To override, use --force.
```

I need to check out the branch, because that's the only place the folder exists.

Next, add `--force`:

```bash
git filter-repo \
    --path src/modules/tour/content/ \
    --path-rename src/modules/tour/content/:src/ \
    --force
```

OK - this worked!

So you were right about the trial and error. Last time I got something like the following path, where the target folders were appended onto each other (not this, but similar):

```
src/modules/tour/content/src/modules/tour/content
```

Perhaps because I was using `--to-subdirectory-filter` ?

When you're new to a lib and it's not completely clear what the result of the commands is, it's a lot of experimentation, cloning, logging, etc. It took me about 3 hours to get to this point and I was beginning to lose my marbles.

I really appreciate your help, and I'll update the  gist.

The branching issue might need attending to though.

Thanks,
Dave

**Comment by newren** [comment]
I'm glad it's working for you.  Hooray!

> I need to check out the branch, because that's the only place the folder exists.

filter-repo rewrites all branches and tags, not just the current branch.  There's no need to check out a different branch to get it to be rewritten.

Also, you can pass --branch to the clone command if you want it to check out some branch other than the default one; that would also have obviated the multiple entries in reflog for HEAD issue.

Deciding to use --force for yourself is fine.  Recommending it to others without careful context is going to lead to someone irrecoverably losing their history, so please, please be very careful about doing that.

> Perhaps because I was using --to-subdirectory-filter ?

Yeah, I keep being surprised by people using --subdirectory-filter and --to-subdirectory-filter wrong.  Issue #73 is open about this so I can try to improve the wording and maybe add some examples.

> the docs which are technical and non-formatted (you may consider markdown?).

The "user manual" link from the "How do I use it?" section of the README takes you to https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html.  So just click on the "Read the user manual" link from the README.

The docs will remain written in asciidoc since that's what git uses and I'm still leaving open the option for being merged into core git.  asciidoc can be output to a variety of formats (man, html, etc.), and I provided that link to a pre-formatted version so folks can read it if they want a nicely formatted version.

**Comment by davestewart** [comment]
All great comments.

Thanks again! It's a great tool, I'm sure it will get added to the project.

:D
