### ISSUE TITLE
print release version with git filter-repo --version

### ISSUE THREAD

**Issue by glensc** [newren/git-filter-repo#81]
it's confusing to even advanced users to print [hash object] as a version. here's the output of two systems, having the same version installed.

```
➔ rpm -q git-filter-repo
git-filter-repo-2.26.0-1.noarch
➔ git filter-repo --version
8d8a4fdd14e0

➔ git filter-repo --version
bdda151959a9
➔ brew info git-filter-repo
git-filter-repo: stable 2.26.0
```

[hash object]: https://github.com/newren/git-filter-repo/blob/v2.26.0/git-filter-repo#L1617

for example: am I running the latest version? I have no idea what is the version behind `8d8a4fdd14e0` or `bdda151959a9`

neither of them resolves actual commit in this repo, because typically installs munge shebang and the [undo], does not work on these cases:

```
➔ head /usr/local/bin/git-filter-repo
#!/usr/local/opt/python@3.8/bin/python3
➔ head /usr/libexec/git-core/git-filter-repo
#!/usr/bin/python3
```

[undo]: https://github.com/newren/git-filter-repo/blob/v2.26.0/git-filter-repo#L1610-L1615

while this hash object may be useful to git-filter-repo developer and bug reports, typical user would like to see 2.26.0 in version output. so please include canonical version in the release tarballs (tar.xz).

**Comment by newren** [comment]
Yeah, maybe I should just remove the --version option from git-filter-repo.

There is no build process to embed the version number into the built artifact, I don't much care for the idea of a turd commit whenever I want to bump the version, and I also don't see why the version of the file in the tarball should be different than what you get when you clone (besides, if others make changes to the package, then it really isn't e.g. "2.26.0" anymore, is it?  But they're unlikely to bump the version field when they tweak things.)  Or I could just hide the --version option (and maybe make it ignore the whole shebang line instead of just python vs. python3 on that line).

**Comment by glensc** [comment]
If you drop the version, I'm sure people will come to complain that there's no --version option or version command :D

probably things you already know:

you could have in the `master` branch `___version__ = 'dev'` in the module, and when you create a release, you create a single commit detached from the `master` that has the actual release version, say `2.26.1`, so the turd commit is left off from `master` branch.

this way you have exact file in tag as in release tarball.

**Comment by newren** [comment]
> you could have in the `master` branch `___version__ = 'dev'` in the module, and when you create a release, you create a single commit

I appreciate that you are hoping my real issue was something different than I stated and that you are attempting to provide a solution that avoids that problem, but this is just creating a turd commit and is the actual problem I already mentioned that I didn't like.

**Comment by newren** [comment]
I made it so that differences in the shebang line won't result in different output.  I know that only addresses version equality, not version comparison, but that's all I'm willing to do right now.

If filter-repo is ever included within git upstream, then it has a full build system which even acts on script files so that it can replace things like @@SHELL_PATH@@, @@LOCALEDIR@@, etc. and we could make it possible handle more.  Of course, the whole question would become moot at that point since people would just run 'git --version' rather than 'git $SUBCOMMAND --version'.

**Comment by glensc** [comment]
cross ref the commit: https://github.com/newren/git-filter-repo/commit/7c877cd7508ce8d8de9f9651fdcce3a15f5b1799
