### ISSUE TITLE
deadlock in sanity_check_args

### ISSUE THREAD

**Issue by Mumeii** [newren/git-filter-repo#86]
Deadlock experienced on MacOS Mojave 10.14.6

Here is the excerpt from my current Homebrew environment : 

```
> brew list --versions
...
git 2.26.2
git-filter-repo 2.26.0
...
python 3.7.7
python@3.8 3.8.2
...
```

I've checked it's the `python@3.8 3.8.2` version that is used by adding `print(platform.python_version())` ( print debugging, what else ? 😄 ) just before the line of code causing the deadlock : 

https://github.com/newren/git-filter-repo/blob/c0c37a7656404dcefff55e55b8f7a9662f9d959d/git-filter-repo#L2037

I'm not familiar at all with Python, but according to the [wait function documentation](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait), I guess that : 
* either the output of `git fast-export -h` in version 2.26.2 is now exceeding the PIPE buffer capacity, which lead to the deadlock mentioned in the doc
* or there is something badly configured in my environment, but I don't have a clue what it can be in that case.

Anyway, I tried to replace 

```
    p.wait()
    output = p.stdout.read()
```

with : 

```
    output, errors = p.communicate()
```

as mentioned in the documentation, and from what I've managed to test so far, that is, only the `--analyze` option, it seems to solve the deadlock trouble.

I'll keep this modified version in my Homebrew cellar for my next tests tomorrow and will keep you informed if I encounter other troubles, but regarding a PR creation, I'd rather have your enlightened point of view about this trouble before submitting one in a language I don't know at all. 

More specifically, I can't really tell if the proposed modification impact : 
* the code behavior or not
* performances in any way

Ok, ok, they are tests, and a [contributing.md](https://github.com/newren/git-filter-repo/blob/master/Documentation/Contributing.md) file, but it's getting much too late here for I can get into configuring a fully functional development environment 😝

**Comment by newren** [comment]
Sweet!  Thanks for reporting this and even for going the extra mile and digging in to find a possible fix.

While the switch to use p.communicate() works, it's a bit overkill; that's meant for when you both need to write to stdin and read from stdout/stderr and don't want one or the other to fill and block.  These processes don't have any stdin, so all we really need to do is read all the stdout before something blocks on it, so the real fix is in removing the p.wait() line (or at very least not calling it until _after_ the output has been read).  Since we're not using the process returncode for anything, we lose nothing by just dropping it.  I've posted a proposed fix over at https://github.com/newren/git-filter-repo/commit/87f85eca51892f5f0142d2869867ee63deddefac .  Could you verify it works for you?

**Comment by Mumeii** [comment]
I've checked it by performing the recommanded modification directly into the script hosted in my Homebrew cellar :

I've simply commented out the `.wait()` call on the initial version of the code, and it's working fine too for me this way 👍

**Comment by newren** [comment]
Awesome, thanks for testing.  I pushed the fix.
