### ISSUE TITLE
Expand comparison to BFG in Readme for users coming from BFG

### ISSUE THREAD

**Issue by nomasprime** [newren/git-filter-repo#90]
I've used BFG in the past to remove files. Thought I'd try using `git-filter-repo` instead but got a warning referring me to this library.

Came here and in the comparison BFG is mentioned simply saying it can't do what `git-filter-repo` does. Unfortunately it doesn't tell you the most import thing for people coming from BFG: how to use `git-filter-repo` to remove files from history.

I've tried `git filter-repo --invert-paths --path 'node_modules' --use-base-name` from the docs but doesn't appear to have changed anything, directories still in log.

I'll search through the docs to try and figure it out but would be really helpful for people coming from BFG to have it right there in the Readme, the current comparison seems redundant.

PS I'll add it when I figure it out.

**Comment by nomasprime** [comment]
I've confirmed this is the correct command from docs, other issues, and resources (eg Stack Overflow). Bug?

**Comment by newren** [comment]
Yeah, BFG operates on each file and each leading directory within a tree, only allowing you to match via the basename of the path at each point but giving you a chance to match any of those.  In contrast, filter-repo provides a list of full paths to filenames (and omits the directories since they are implicitly included).  So --use-base-name will only ever give you the basenames of _files_, not of directories, and thus isn't helpful in your case.

To remove a directory named node_modules at the toplevel, what you'd want is

```
git filter-repo --invert-paths --path node_modules/
```

If you want to remove all node_modules directories found somewhere below the toplevel, you'd want (note that the asterisk can match slashes too, so this isn't limited to one directory down):

```
git filter-repo --invert-paths --path-glob '*/node_modules/'
```

Could you point out where in the docs or other issues that "confirmed" that your command was correct, so I can correct them?

Also, I had been thinking of making a cheat sheet for helping people coming from filter-branch.  Based on your example and request, I think I agree with you that I should make one for BFG too.

**Comment by nomasprime** [comment]
Hi @newren, thanks for the help.

I got the original command from [here](https://github.com/newren/git-filter-repo/blob/master/Documentation/git-filter-repo.txt#L554).

Maybe I'm missing something about the general usage though because even after I run `git filter-repo --invert-paths --path-glob '*/node_modules/'` the `node_modules` directories are still showing up in `git log --stat`.

There's no security issue here so I'm just going to remove and push but would be great to know how I could use this in a similar way to BFG for future reference.

**Comment by newren** [comment]
The original command you highlight was for removing a file, in which case the --use-base-name usage is correct.  I wrote a document to help folks converting over from BFG: https://github.com/newren/git-filter-repo/blob/master/Documentation/converting-from-bfg-repo-cleaner.md

Let me see if I understand correctly.  You run
```shell
   git filter-repo --invert-paths --path-glob '*/node_modules/'
```
in your repository, and then afterwards run `git log --stat` and see some node_modules/ directories somewhere other than the toplevel of the repository.  Is that correct?  (If you had node_modules directories at both the toplevel and below some subdirectory, then you should have either used both commands I mentioned previously or combined them into a single command like `git filter-repo --invert-paths --path-glob '*/node_modules/' --path node_modules/`)

If I'm correct that you still have node_modules directories somewhere below the toplevel after running that command, could you show me some of the lines of output from git log --stat?  Is there any chance there are uppercase letters in the history and/or other funny symbols that would make it not match your glob exactly?  You've got me surprised.

**Comment by newren** [comment]
Ping?  Should I assume the leftover node_modules/ directory was at the toplevel (i.e. that you just needed to correct your command) and close this issue?  If not, let me know and I'll investigate, but if I don't hear back I'll assume that was the issue.

**Comment by newren** [comment]
I'll assume you were just missing the `--path node_modules/` as mentioned above and close out since I haven't heard back for a while.  If that's a bad assumption and you do still see a problem even with that flag added, by all means please do reopen and provide more details.
