### ISSUE TITLE
Not able to use `--prune-degenerate never` option

### ISSUE THREAD

**Issue by gauravkanoongo** [newren/git-filter-repo#92]
I've a large repository and I want to move one folder `CededDB` from this repo into a new repository. I am using following command: 

`git filter-repo --path CededDB/ --prune-degenerate never `

It is giving me below error message: 

> Parsed 1 commitsTraceback (most recent call last):
>   File "\git-filter-repo\2.26.0\git-filter-repo", line 3913, in <module>
>     filter.run()
>   File "\git-filter-repo\2.26.0\git-filter-repo", line 3850, in run
>     self._parser.run(self._input, self._output)
>   File "\apps\git-filter-repo\2.26.0\git-filter-repo", line 1414, in run
>     self._parse_commit()
>   File "\git-filter-repo\2.26.0\git-filter-repo", line 1267, in _parse_commit
>     self._commit_callback(commit, aux_info)
>   File "\git-filter-repo\2.26.0\git-filter-repo", line 3406, in _tweak_commit
>     self._insert_into_stream(commit)
>   File "\git-filter-repo\2.26.0\git-filter-repo", line 3825, in _insert_into_stream
>     self._parser.insert(obj)
>   File "\git-filter-repo\2.26.0\git-filter-repo", line 1392, in insert
>     obj.dump(self._output)
>   File "\apps\git-filter-repo\2.26.0\git-filter-repo", line 718, in dump
>     file\_.write(b'%s\n' % parent)
> TypeError: %b requires a bytes-like object, or an object that implements \_\_bytes\_\_, not 'NoneType'

Without the `--prune-degenerate never` option, it is working successfully but skipping some merge-commits which I want to retain in the history. 

I checked the code and understand that in line #718 `file_.write(b'%s\n' % parent)` the variable `parent` has value `None` for one specific commit which is causing this problem. 

Kindly look into this issue and let me know if there is any workaround available.

**Comment by newren** [comment]
I've got a guess at what might be causing this and the fix.  Could you try with the proposed fix over at https://github.com/newren/git-filter-repo/commit/b4391762a6ebfd3c65e25a9eac35aac36e06cf3b ?

**Comment by gauravkanoongo** [comment]
Thanks @newren - I tried the proposed fix at [b439176](https://github.com/newren/git-filter-repo/commit/b4391762a6ebfd3c65e25a9eac35aac36e06cf3b). It is not showing the error message anymore but the topology of the new repository is not correct, some observations: 

1. The initial commit with the given path in source repository is a non-merge commit, however in the output repository it is a merge-commit, same behavior is observed without `--prune-degenerate never` option. 

2.  The result is showing some consecutive empty merge-commits, without any regular (non-merge commits) between them. 

3. The result also has some non-consecutive empty merge commits that were not affecting the given path in source repository. 

With some manual cherry-pick, it can work but it would be best if we get the desired topology using `--prune-degenerate never` option. In next few fays, I'll try to prepare a repository that can be shared and where this issue can be reproduced.

**Comment by newren** [comment]
I'll look forward to your example repo, but it's possible I can help a little based off your descriptions, or at least give you some hints about explaining it in a way that might make more sense to me.

> 1. The initial commit with the given path in source repository is a non-merge commit, however in the output repository it is a merge-commit, same behavior is observed without `--prune-degenerate never` option.

An initial commit is defined as a commit with no parents.  A merge commit is defined as a commit with two or more parents.  This state is therefore impossible.

Perhaps what you mean is that all ancestors of what used to be a merge commit were pruned since none of them modified any paths under the directory you specified, but the merge commit not only merged the two sides but had some evil additional modifications including some to the directory you specified?  In such a case, yes, you'd end up with an initial commit that probably has a commit message that says something like "Merge branch foo into master", even though the rewrite turned it into a non-merge commit.

If this is indeed the situation, there's absolutely nothing filter-repo can do automatically -- if you really want to prune commits that don't touch the relevant path and the merge commit is the first one that does so and you don't tell it how to change the commit message or modify the contents of the merge commit or something, then its hands are tied.  As per the "Intrinsic limitations" sections of the manual, filter-repo writes a note to .git/filter-repo/suboptimal-issues noting such commits whenever it runs across such merge-became-a-non-merge scenarios.  If you want to "fix" those situations, you'll need to do extra filtering rules of some sort to specify what to do (e.g. include the changes in an earlier non-merge commit so it isn't deleted, modify the commit message of the merge commit so it doesn't sound like a merge commit, etc.)

If you mean something else entirely, then hopefully your example repo can demonstrate what you mean.

> 2. The result is showing some consecutive empty merge-commits, without any regular (non-merge commits) between them.

What do you mean by consecutive empty merge-commits?  When there is a single path forward and backward, then "consecutive" makes sense, and since non-merge commits have a single parent and thus a single path you can talk about consecutive non-merge commits.  But merge commits have multiple paths they can follow, so I don't know what consecutive empty merge commits mean.

(I'm assuming by empty you mean the merge commits have no differences relative to their first parent, in which case the answer to what you mean by consecutive empty merge commits probably needs to involve information about the relationship of the second parents of all these merge commits.)

> 3. The result also has some non-consecutive empty merge commits that were not affecting the given path in source repository.

Isn't that quite common in non-filtered repositories as well?  You merge some older hotfix branch whose changes have been obsoleted by other changes so the net effect is that there is no code change from the merge.  But the merge isn't there because of code changes, it's there to show that the old changes haven't been forgotten or left out; in other words, the merge commit is a statement that the current code includes all considerations from that other branch.  Dropping the merge commit would also detach and throw away all the other commits on the side branch (unless some other merge commit included them as one of their additional parents).

> With some manual cherry-pick, it can work but it would be best if we get the desired topology using `--prune-degenerate never` option. In next few fays, I'll try to prepare a repository that can be shared and where this issue can be reproduced.

A possible random shot in the dark: I just noticed that I forgot to include the --no-ff option in the manual, even though it was documented in the built-in help.  Perhaps what you are seeking is closer to `--no-ff` (combined with default `--prune-degenerate auto`), rather than actually using `--prune-degenerate never`?

**Comment by newren** [comment]
Any luck creating an example repo?

**Comment by gauravkanoongo** [comment]
Sorry for delay in my response. I can confirm that the reported error was resolved with the proposed fix at [b439176](https://github.com/newren/git-filter-repo/commit/b4391762a6ebfd3c65e25a9eac35aac36e06cf3b). 

I understand that topology related problems are different issue altogether and should be discussed in separate thread, however just giving an update here that I created a sample [repo](https://github.com/gauravkanoongo/git-filter-repo-issue) to investigate the topology problems. 

This is the original topology of commits: 

![image](https://user-images.githubusercontent.com/1622656/82912961-b3674d80-9f3b-11ea-95b8-ddc5bcec0ef7.png)

I ran `git filter-repo --path folder-1` to keep only `folder-1` and its contents in the repository. This command gave the following output topology: 

![image](https://user-images.githubusercontent.com/1622656/82913881-d6463180-9f3c-11ea-989b-cde770908d40.png)

Here you'll notice that the merge-commit `3bd2c3d3` is missing - this always happens with the first merge-commit that introduced the given `path` to the repo, I tested on multiple repo and found this issue in each of them. 

I tested with different option values for `--prune-degenerate` and understand that `--prune-degenerate` was not needed in my case. 

Thanks for letting me know about `--no-ff` option in your previous comment. I did not combine it with `--prune-degenerate` and got the desired output only with `--no-ff` option i.e. `git filter-repo --path folder-1 --no-ff` gave this output:

![image](https://user-images.githubusercontent.com/1622656/82915087-4c976380-9f3e-11ea-8b7f-329e98ad8be8.png)

However when I tried the same option in my original repo, I did not get the desired result and the merge commit introducing the path to the rpeo was missing in output. 

As a workaround, I've done it in two steps: 

1. First filtered two paths, path1 which is want and path2 as a dummy : i.e. `git filter-repo --path path1 --path path2 --no-ff` 
2. Pushed output to a local repo and clone a new repo from it. 
3. Filter again with the desired path only i.e. `git filter-repo --path path1 --no-ff`

With these steps, I was able to get the desired output topology in the original repo also.

**Comment by newren** [comment]
I'm glad you've got a workaround...but unfortunately that doesn't help me know how to fix things any further.  Since you mention that --no-ff works with the test repo you generated, is there any chance you can generate a more complicated test repo that generates the issue you see with your real repo?

**Comment by gauravkanoongo** [comment]
Sure, I'll try to do that over the weekend.

**Comment by newren** [comment]
I'm guessing you never found the time to create a test repo.  Some intervening change over the years may have fixed the original issue, but if not, I'd need more details to investigate.  Do feel free to reopen (or open a new ticket) if you can find a good testcase.

Thanks for the report!

**Comment by gauravkanoongo** [comment]
Hey @newren - thanks for your response, I never got chance to create a more complicated example than what I originally explain in previous comments and in the [repo](https://github.com/gauravkanoongo/git-filter-repo-issue) but the fix you provided with [b439176](https://github.com/newren/git-filter-repo/commit/b4391762a6ebfd3c65e25a9eac35aac36e06cf3b) worked for my example. I'll raise a new ticket if I observe anything similar in future. Thanks a lot for all your effort.
