### ISSUE TITLE
Common way to filter-repo incrementally

### ISSUE THREAD

**Issue by nereusuj** [newren/git-filter-repo#93]
I'd like to create filtered repo from the upstream repo incrementally.
What would be the common way to filter-repo incrementally from the upstream repo?

The steps I did.
1. clone and filter-repo(subdirectory filter, I like to do) and push to the new filtered repo.
2. fetch new changes from upstream and filter-repo again and push to the filtered repo.

I expected that step 2 create a new history on top of the history that was created in step 1. But step 2 created a whole new history and I could not push to the new filtered repo because it broke fast forward.

**Comment by newren** [comment]
You're operating a bit outside of filter-repo's design space; as I mentioned towards the end of the manual, "I assume that people use filter-repo for one-shot conversions, not ongoing data transfers."  As such, there is no common way to do what you are asking.  If you happen to use the exact same filtering rules every time with your repository, then you'd probably end up with the first commits being identical between rewrites so that fast-forwarding would work.  I say "probably" there, because I make no guarantees; changes to fast-export or new versions of filter-repo might change default rewrite rules in a way that causes some commit to be rewritten differently.  The fact that you didn't get a history that you could fast forward suggests though that you are modifying the filtering rules between runs already and need that for your usecase.

It's possible that the josh project (https://github.com/esrlabs/josh) does what you are looking for.  It doesn't allow generalized rewrite rules like filter-repo (instead just focusing on giving you a subset of a monorepo), but does keep track of what has been exported so far so that you can do incremental exports.

Alternatively, you could build a tool on top of filter-repo that keeps track of what has been exported so far, and remember that from run to run so that you can feed fast-export and fast-import the appropriate import-marks as a starting point so that it only exports the new history and imports that new stuff on top of the previous rewrite.  There would probably need to be some way of limiting the full generality of filter-repo, or else you'd need to add a lot of care around how to handle working with multiple source or target repos, figure out how to deal with manually inserted objects in user's rewrite streams, and figure out whether the --refs drawbacks with pruning become-empty commits are a problem for you or not.  I looked at that once, but it didn't look easy.

That's probably not the answer you wanted to hear; sorry about that.  Hopefully something I said helps, though.
