### ISSUE TITLE
`--paths-from-file` can't handle renames 

### ISSUE THREAD

**Issue by nagreme** [newren/git-filter-repo#96]
My repo's structure is (with files omitted):
```
root
  |- .gitignore
  |- src/
      |- main/
            |- resources/
            |- java/
                  |- com/org/
                         |- foo/
                         |- bar/
```

I want to keep all of: 
- `.gitignore`
- `src/main/resources`
- `src/main/java/com/org/foo`  renamed `src/main/java/com/org`

Using `git filter-repo --paths-from-file include_paths.txt` with     
`include_paths.txt` :
```
.gitignore
src/main/java/com/org/foo/==>src/main/java/com/org/
src/main/resources/
```
Leaves me with only the .gitignore and the resources folder: the entire java subtree having been deleted.

If I removed the rename I get to keep all the paths I want, as expected.  
I can just do the rename in a separate step but it would be nice to have it here.

I am running this on Git for Windows on Windows 10 (git version 2.23.0.windows.1) and followed the manual installation instructions in the README (did not install the python file since I don't think I'll be using that, didn't install the manpage, and couldn't find the .html file in this repo)

**Comment by nagreme** [comment]
Note that I am trying to do this because the documentation implies that you can.  
(https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.htm)

**Comment by newren** [comment]
This sounds like a bug I had in older versions of filter-repo, where the fact that you were renaming the directory to another name that already exists in the repository triggers that bug.  Since you're using an old version of git, could you clarify what version of filter-repo you are running?

**Comment by nagreme** [comment]
I cloned master of this repo on 2020-05-19

If it's useful information:
```
$ git filter-repo --version
9d591410ba18
```

**Comment by newren** [comment]
Thanks for the report; it turns out that combining filtering and renaming instructions is what triggers this bug, i.e. you could also get it by combining e.g. --path and --path-rename.  Anyway, I added a simple testcase mocking up your code layout to the testsuite and pushed a fix for this, available in commit df6c8652a2 (filter-repo: fix ugly bug with mixing path filtering and renaming, 2020-05-25).

To be honest, it's kind of an embarrassing bug, especially since it's been there so long.  But much better to know about it so I can fix it.  Thanks again!

**Comment by nagreme** [comment]
Excellent, thank you for your prompt response and the fix!

**Comment by newren** [comment]
Actually, no my fix was wrong and I just reverted it...and added some better documentation and tests to make sure I don't forget and that others don't fall into this little trap.  Path renaming should not also do filtering, so if you want to keep all of
  * .gitignore
  * src/main/resources
  * src/main/java/com/org/foo
and rename
  * src/main/java/com/org/foo -> src/main/java/com/org

then your --paths-from-file should be
```
.gitignore
src/main/resources/
src/main/java/com/org/foo/
src/main/java/com/org/foo/==>src/main/java/com/org/
```

Allowing path renaming to also do path filtering results in craziness such as the one big example I use in my README.md completely breaking.

**Comment by JoshOBrien** [comment]
@newren So if I'm not mistaken, based on the above, the first example in section "Filtering based on many paths" in git-filter-repo.html needs an edit. Where it currently reads

```
# An example of renaming a path
tools/==>scripts/
```

... it should instead read ...

```
# An example of filtering to keep and then renaming a path
tools/
tools/==>scripts/
```

**Comment by polarathene** [comment]
@JoshOBrien I think the mentioned docs is about this part?:

> Note that path renaming does not do path filtering, thus the following command
> `git filter-repo --path src/main/ --path-rename tools/:scripts/`
> would not result in the tools or scripts directories being present, because the single filter selected only src/main/. It’s likely that you would instead want to run:
> `git filter-repo --path src/main/ --path tools/ --path-rename tools/:scripts/`

The following section `Filtering based on many paths` after that using `--paths-from-file` doesn't make mention of the issue though.

---

> Path renaming should not also do filtering

@newren Could you please clarify this for us a bit better? The issue described here is based on the order of the lines? The `main/resources` line was moved above the the `main/java` line(s), was that intentional to place renames last or just as a best practice?

Did it have anything to do with sharing `main/` or did `main/java` just need to be filtered on it's own line first, followed by the rename line at any point after that?

How does this affect the example in the docs with `tools/==>scripts/` as @JoshOBrien points out? Is it because `tools/releases` was filtered prior that the rename (which would give us `scripts/releases/`) is handled properly?

The prior section seems to touch on this, but as a user who was interested in the `--paths-from-file` I didn't see the earlier section and the given example didn't indicate this could be a problem, I only became aware of it during a search on the method in github issues before carrying it out :sweat_smile:

**Comment by azamali9968-stack** [comment]
> I
> ```

**Comment by azamali9968-stack** [comment]
[](ur
https://github.com/newren/git-filter-repo/issues/96#issue-621796014l)

**Comment by azamali9968-stack** [comment]
### ### 

> `_**Duplicate of #740 


**_`

> `Duplicate of #`
