### ISSUE TITLE
Replacement for BFG's object-id-map.old-new.txt

### ISSUE THREAD

**Issue by TobiX** [newren/git-filter-repo#98]
Hi,

first, thanks for the awesome tool!

A question: Would it be possible to provide a replacement for BFG's `object-id-map.old-new.txt`, which just seems to be a complete map from all old blob IDs to all new blob IDs?

This is useful, for example, to fixup internal structures in GitLab after a repository rewrite: https://gitlab.com/help/user/project/repository/reducing_the_repo_size_using_git.md#using-the-bfg-repo-cleaner

**Comment by jamesramsay** [comment]
I started looking at updating this documentation today and realized the same.

Basically we are using the list of old object ids to prune any `refs/keep-around` that we use for making sure that commits referenced by comments particularly aren't pruned. This avoids the situation where comments reference objects that doesn't exist anymore, but makes clean up challenging.

@newren if you have any ideas for how to get a list of modified commits, that would be very helpful!

**Comment by newren** [comment]
If you just want a list of modified commits, that's pretty easy.  Could you verify that's what you want?  @TobiX described object-id-map.old-new.txt as a complete map from all old _blob_ IDs to all new blob IDs, but in my testing it never contains any blob IDs at all.  It only ever includes commits, trees, and tag objects.  I can assume that mentioning blobs was a mistake, and the linked GitLab doc suggests gc reasons which also implies neither blobs nor tags would matter, but is it just modified commits that you need?

Anyway, what you're looking for is basically the commit-map.  At the end of filter-repo's run, it creates a .git/filter-repo/commit-map file -- and also a .git/filter-repo/ref-map file.  The former contains the mapping of how all commits were (or were not) changed, while the ref-map contains the mapping of how all local references were (or were not) changed.  I think you want the commit-map, but I mention the ref-map for two reasons: (1) to make sure you're aware of it and don't accidentally grab the wrong file, (2) if there is any chance you keep references to non-lightweight tags on the server that the user doesn't force push over then you might need some info from the ref-map, and (3) even though server-side you'd be more interested in the commit-map, I think the end-users would be more interested in the ref-map (because then they can easily see how their refs changed instead of trying to look through the massive list of all commits changed).

A couple notes about the commit-map format: (1) the first line just explains the meaning of the two columns (with the text "old" and "new" on it) and isn't a mapping itself, (2) the commits appear in no particular order (based on the order that python happens to iterate over a dict), and (3) the commit-map will contain all commits in the range of the rewrite, even commits which end up not being changed (e.g. because the commit pre-dated when the large file(s) were introduced to the repo).

Also, it's worth noting that I have told users in the documentation a few times that multiple runs of filter-repo are kosher, but the .git/filter-repo/commit-map file is unconditionally overwritten with each run, so you'd need to either suggest users don't use multiple invocations or else make a copy of each written commit-map file and upload them all (and perhaps tell you the order).

Anyway, that's a long winded answer.  The short form is that I think `.git/filter-repo/commit-map` already has the info you want, and you'd just need to parse it and throw away the first line and any lines where the two hashes are the same.  Does that help?

**Comment by jamesramsay** [comment]
> If you just want a list of modified commits, that's pretty easy. 

Yes. Thanks, the `.git/filter-repo/commit-map` does the job based on my testing.

> the commit-map will contain all commits in the range of the rewrite, even commits which end up not being changed (e.g. because the commit pre-dated when the large file(s) were introduced to the repo).

I'm trying to wrap my head around this. When the `new` commit is:

- `0000000000000000000000000000000000000000`, this means the commit was removed?
- different to the `old` commit, this means the commit was rewritten
- same as the `old` commit, this means it was in range but not modified

Is that accurate? And would you accept a pull request to document the `commit-map`?

**Comment by newren** [comment]
> I'm trying to wrap my head around this. When the `new` commit is:
> 
> * `0000000000000000000000000000000000000000`, this means the commit was removed?

Correct.  Common case where this happens is if the user specifies to remove a file, and there is at least one (non-merge) commit that modifies that file but no other files.  In such a case, those commits will be removed entirely.  The usage of an all zero hash is similar to how git hooks work with ref updates and such.

> * different to the `old` commit, this means the commit was rewritten

Correct; something about it changed -- different tree, different file contents for some file, or even just different parent(s).  (Thus, once a commit changes, all its descendants will change too.)

> * same as the `old` commit, this means it was in range but not modified

Yep.

> Is that accurate? And would you accept a pull request to document the `commit-map`?

Sure!

**Comment by newren** [comment]
It looks like you put up some documents over at https://docs.gitlab.com/ee/user/project/repository/reducing_the_repo_size_using_git.html; very nice!  A few small things about those docs:
* Would it be possible to streamline step 6 (`tail -n +2 filter-repo/commit-map | grep -E -v '^(\w+) \1$' >> commit-map.txt`) by modifying your server side process to strip out the "old new" line and any lines with matching hashes?  Seems like that'd make it easier for the users, since then they'd be able to just upload the commit-map file as-is.  Not a big deal, just mentioning it as an idea.
* Your `git push origin ...` steps will fail, because filter-repo does an `git remote rm origin` when it runs (see [step 3 of internals](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#INTERNALS) and the [discussion section's lengthy discussion of pushing back to the original repo](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#DISCUSSION) and how it requires careful flag-day major collaboration with all other contributors and recommends pushing to a new repo instead).  You may want to add a step to run `git remote add origin <original url>` first.
* I'm thinking of adding a subsection to the discussion section of the git-filter-repo manual that says that if you still want to push back to the original URL despite my warnings, then you should get instructions from your hosting provider on how to ensure that all server-side references are also cleaned up, and then link to your document as an example (since you're the first hosting provider to my knowledge to update docs to reference filter-repo).  Sound okay to you?

Anyway, if Is there anything else you need here or are we good to close out?

**Comment by jamesramsay** [comment]
> Would it be possible to streamline step 6

Definitely. I started work on this last week https://gitlab.com/gitlab-org/gitaly/-/merge_requests/2247

> Your git push origin ... steps will fail

Good catch. That tripped me up when I was testing, but seems to have been lost in my final re-org of the page before it was merged. I'll address this in a follow up MR next week when I am back from vacation.

> Sound okay to you?

Works for me 😄  And happy to have this issue closed. Thanks for making this great tool @newren 🚀
